// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config20_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer18_out_dout,
        layer18_out_num_data_valid,
        layer18_out_fifo_cap,
        layer18_out_empty_n,
        layer18_out_read,
        layer20_out_din,
        layer20_out_num_data_valid,
        layer20_out_fifo_cap,
        layer20_out_full_n,
        layer20_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [1279:0] layer18_out_dout;
input  [1:0] layer18_out_num_data_valid;
input  [1:0] layer18_out_fifo_cap;
input   layer18_out_empty_n;
output   layer18_out_read;
output  [511:0] layer20_out_din;
input  [1:0] layer20_out_num_data_valid;
input  [1:0] layer20_out_fifo_cap;
input   layer20_out_full_n;
output   layer20_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer18_out_read;
reg layer20_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer18_out_blk_n;
reg    layer20_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [15:0] select_ln51_fu_623_p3;
reg   [15:0] select_ln51_reg_1412;
reg    ap_block_state1;
wire   [15:0] select_ln51_8_fu_647_p3;
reg   [15:0] select_ln51_8_reg_1417;
wire   [15:0] select_ln51_9_fu_671_p3;
reg   [15:0] select_ln51_9_reg_1422;
wire   [15:0] select_ln51_10_fu_695_p3;
reg   [15:0] select_ln51_10_reg_1427;
wire   [15:0] select_ln51_11_fu_719_p3;
reg   [15:0] select_ln51_11_reg_1432;
wire   [15:0] select_ln51_12_fu_743_p3;
reg   [15:0] select_ln51_12_reg_1437;
wire   [15:0] select_ln51_13_fu_767_p3;
reg   [15:0] select_ln51_13_reg_1442;
wire   [15:0] select_ln51_14_fu_791_p3;
reg   [15:0] select_ln51_14_reg_1447;
wire   [15:0] select_ln51_15_fu_815_p3;
reg   [15:0] select_ln51_15_reg_1452;
wire   [15:0] select_ln51_16_fu_839_p3;
reg   [15:0] select_ln51_16_reg_1457;
wire   [15:0] select_ln51_17_fu_863_p3;
reg   [15:0] select_ln51_17_reg_1462;
wire   [15:0] select_ln51_18_fu_887_p3;
reg   [15:0] select_ln51_18_reg_1467;
wire   [15:0] select_ln51_19_fu_911_p3;
reg   [15:0] select_ln51_19_reg_1472;
wire   [15:0] select_ln51_20_fu_935_p3;
reg   [15:0] select_ln51_20_reg_1477;
wire   [15:0] select_ln51_21_fu_959_p3;
reg   [15:0] select_ln51_21_reg_1482;
wire   [15:0] select_ln51_22_fu_983_p3;
reg   [15:0] select_ln51_22_reg_1487;
wire   [15:0] select_ln51_23_fu_1007_p3;
reg   [15:0] select_ln51_23_reg_1492;
wire   [15:0] select_ln51_24_fu_1031_p3;
reg   [15:0] select_ln51_24_reg_1497;
wire   [15:0] select_ln51_25_fu_1055_p3;
reg   [15:0] select_ln51_25_reg_1502;
wire   [15:0] select_ln51_26_fu_1079_p3;
reg   [15:0] select_ln51_26_reg_1507;
wire   [15:0] select_ln51_27_fu_1103_p3;
reg   [15:0] select_ln51_27_reg_1512;
wire   [15:0] select_ln51_28_fu_1127_p3;
reg   [15:0] select_ln51_28_reg_1517;
wire   [15:0] select_ln51_29_fu_1151_p3;
reg   [15:0] select_ln51_29_reg_1522;
wire   [15:0] select_ln51_30_fu_1175_p3;
reg   [15:0] select_ln51_30_reg_1527;
wire   [15:0] select_ln51_31_fu_1199_p3;
reg   [15:0] select_ln51_31_reg_1532;
wire   [15:0] select_ln51_32_fu_1223_p3;
reg   [15:0] select_ln51_32_reg_1537;
wire   [15:0] select_ln51_33_fu_1247_p3;
reg   [15:0] select_ln51_33_reg_1542;
wire   [15:0] select_ln51_34_fu_1271_p3;
reg   [15:0] select_ln51_34_reg_1547;
wire   [15:0] select_ln51_35_fu_1295_p3;
reg   [15:0] select_ln51_35_reg_1552;
wire   [15:0] select_ln51_36_fu_1319_p3;
reg   [15:0] select_ln51_36_reg_1557;
wire   [15:0] select_ln51_37_fu_1343_p3;
reg   [15:0] select_ln51_37_reg_1562;
wire   [15:0] select_ln51_38_fu_1367_p3;
reg   [15:0] select_ln51_38_reg_1567;
wire   [39:0] in_data_fu_293_p1;
wire   [0:0] icmp_ln51_fu_607_p2;
wire   [15:0] out_data_fu_613_p4;
wire   [39:0] trunc_ln44_s_fu_297_p4;
wire   [0:0] icmp_ln51_8_fu_631_p2;
wire   [15:0] out_data_8_fu_637_p4;
wire   [39:0] trunc_ln44_7_fu_307_p4;
wire   [0:0] icmp_ln51_9_fu_655_p2;
wire   [15:0] out_data_9_fu_661_p4;
wire   [39:0] trunc_ln44_8_fu_317_p4;
wire   [0:0] icmp_ln51_10_fu_679_p2;
wire   [15:0] out_data_10_fu_685_p4;
wire   [39:0] trunc_ln44_9_fu_327_p4;
wire   [0:0] icmp_ln51_11_fu_703_p2;
wire   [15:0] trunc_ln_fu_709_p4;
wire   [39:0] trunc_ln44_1_fu_337_p4;
wire   [0:0] icmp_ln51_12_fu_727_p2;
wire   [15:0] trunc_ln52_s_fu_733_p4;
wire   [39:0] trunc_ln44_2_fu_347_p4;
wire   [0:0] icmp_ln51_13_fu_751_p2;
wire   [15:0] trunc_ln52_3_fu_757_p4;
wire   [39:0] trunc_ln44_3_fu_357_p4;
wire   [0:0] icmp_ln51_14_fu_775_p2;
wire   [15:0] trunc_ln52_4_fu_781_p4;
wire   [39:0] trunc_ln44_4_fu_367_p4;
wire   [0:0] icmp_ln51_15_fu_799_p2;
wire   [15:0] trunc_ln52_5_fu_805_p4;
wire   [39:0] trunc_ln44_5_fu_377_p4;
wire   [0:0] icmp_ln51_16_fu_823_p2;
wire   [15:0] trunc_ln52_6_fu_829_p4;
wire   [39:0] trunc_ln44_6_fu_387_p4;
wire   [0:0] icmp_ln51_17_fu_847_p2;
wire   [15:0] trunc_ln52_7_fu_853_p4;
wire   [39:0] trunc_ln44_10_fu_397_p4;
wire   [0:0] icmp_ln51_18_fu_871_p2;
wire   [15:0] trunc_ln52_8_fu_877_p4;
wire   [39:0] trunc_ln44_11_fu_407_p4;
wire   [0:0] icmp_ln51_19_fu_895_p2;
wire   [15:0] trunc_ln52_9_fu_901_p4;
wire   [39:0] trunc_ln44_12_fu_417_p4;
wire   [0:0] icmp_ln51_20_fu_919_p2;
wire   [15:0] trunc_ln52_1_fu_925_p4;
wire   [39:0] trunc_ln44_13_fu_427_p4;
wire   [0:0] icmp_ln51_21_fu_943_p2;
wire   [15:0] trunc_ln52_2_fu_949_p4;
wire   [39:0] trunc_ln44_14_fu_437_p4;
wire   [0:0] icmp_ln51_22_fu_967_p2;
wire   [15:0] trunc_ln52_10_fu_973_p4;
wire   [39:0] trunc_ln44_15_fu_447_p4;
wire   [0:0] icmp_ln51_23_fu_991_p2;
wire   [15:0] trunc_ln52_11_fu_997_p4;
wire   [39:0] trunc_ln44_16_fu_457_p4;
wire   [0:0] icmp_ln51_24_fu_1015_p2;
wire   [15:0] trunc_ln52_12_fu_1021_p4;
wire   [39:0] trunc_ln44_17_fu_467_p4;
wire   [0:0] icmp_ln51_25_fu_1039_p2;
wire   [15:0] trunc_ln52_13_fu_1045_p4;
wire   [39:0] trunc_ln44_18_fu_477_p4;
wire   [0:0] icmp_ln51_26_fu_1063_p2;
wire   [15:0] trunc_ln52_14_fu_1069_p4;
wire   [39:0] trunc_ln44_19_fu_487_p4;
wire   [0:0] icmp_ln51_27_fu_1087_p2;
wire   [15:0] trunc_ln52_15_fu_1093_p4;
wire   [39:0] trunc_ln44_20_fu_497_p4;
wire   [0:0] icmp_ln51_28_fu_1111_p2;
wire   [15:0] trunc_ln52_16_fu_1117_p4;
wire   [39:0] trunc_ln44_21_fu_507_p4;
wire   [0:0] icmp_ln51_29_fu_1135_p2;
wire   [15:0] trunc_ln52_17_fu_1141_p4;
wire   [39:0] trunc_ln44_22_fu_517_p4;
wire   [0:0] icmp_ln51_30_fu_1159_p2;
wire   [15:0] trunc_ln52_18_fu_1165_p4;
wire   [39:0] trunc_ln44_23_fu_527_p4;
wire   [0:0] icmp_ln51_31_fu_1183_p2;
wire   [15:0] trunc_ln52_19_fu_1189_p4;
wire   [39:0] trunc_ln44_24_fu_537_p4;
wire   [0:0] icmp_ln51_32_fu_1207_p2;
wire   [15:0] trunc_ln52_20_fu_1213_p4;
wire   [39:0] trunc_ln44_25_fu_547_p4;
wire   [0:0] icmp_ln51_33_fu_1231_p2;
wire   [15:0] trunc_ln52_21_fu_1237_p4;
wire   [39:0] trunc_ln44_26_fu_557_p4;
wire   [0:0] icmp_ln51_34_fu_1255_p2;
wire   [15:0] trunc_ln52_22_fu_1261_p4;
wire   [39:0] trunc_ln44_27_fu_567_p4;
wire   [0:0] icmp_ln51_35_fu_1279_p2;
wire   [15:0] trunc_ln52_23_fu_1285_p4;
wire   [39:0] trunc_ln44_28_fu_577_p4;
wire   [0:0] icmp_ln51_36_fu_1303_p2;
wire   [15:0] trunc_ln52_24_fu_1309_p4;
wire   [39:0] trunc_ln44_29_fu_587_p4;
wire   [0:0] icmp_ln51_37_fu_1327_p2;
wire   [15:0] trunc_ln52_25_fu_1333_p4;
wire   [39:0] trunc_ln44_30_fu_597_p4;
wire   [0:0] icmp_ln51_38_fu_1351_p2;
wire   [15:0] trunc_ln52_26_fu_1357_p4;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer20_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        select_ln51_10_reg_1427 <= select_ln51_10_fu_695_p3;
        select_ln51_11_reg_1432 <= select_ln51_11_fu_719_p3;
        select_ln51_12_reg_1437 <= select_ln51_12_fu_743_p3;
        select_ln51_13_reg_1442 <= select_ln51_13_fu_767_p3;
        select_ln51_14_reg_1447 <= select_ln51_14_fu_791_p3;
        select_ln51_15_reg_1452 <= select_ln51_15_fu_815_p3;
        select_ln51_16_reg_1457 <= select_ln51_16_fu_839_p3;
        select_ln51_17_reg_1462 <= select_ln51_17_fu_863_p3;
        select_ln51_18_reg_1467 <= select_ln51_18_fu_887_p3;
        select_ln51_19_reg_1472 <= select_ln51_19_fu_911_p3;
        select_ln51_20_reg_1477 <= select_ln51_20_fu_935_p3;
        select_ln51_21_reg_1482 <= select_ln51_21_fu_959_p3;
        select_ln51_22_reg_1487 <= select_ln51_22_fu_983_p3;
        select_ln51_23_reg_1492 <= select_ln51_23_fu_1007_p3;
        select_ln51_24_reg_1497 <= select_ln51_24_fu_1031_p3;
        select_ln51_25_reg_1502 <= select_ln51_25_fu_1055_p3;
        select_ln51_26_reg_1507 <= select_ln51_26_fu_1079_p3;
        select_ln51_27_reg_1512 <= select_ln51_27_fu_1103_p3;
        select_ln51_28_reg_1517 <= select_ln51_28_fu_1127_p3;
        select_ln51_29_reg_1522 <= select_ln51_29_fu_1151_p3;
        select_ln51_30_reg_1527 <= select_ln51_30_fu_1175_p3;
        select_ln51_31_reg_1532 <= select_ln51_31_fu_1199_p3;
        select_ln51_32_reg_1537 <= select_ln51_32_fu_1223_p3;
        select_ln51_33_reg_1542 <= select_ln51_33_fu_1247_p3;
        select_ln51_34_reg_1547 <= select_ln51_34_fu_1271_p3;
        select_ln51_35_reg_1552 <= select_ln51_35_fu_1295_p3;
        select_ln51_36_reg_1557 <= select_ln51_36_fu_1319_p3;
        select_ln51_37_reg_1562 <= select_ln51_37_fu_1343_p3;
        select_ln51_38_reg_1567 <= select_ln51_38_fu_1367_p3;
        select_ln51_8_reg_1417 <= select_ln51_8_fu_647_p3;
        select_ln51_9_reg_1422 <= select_ln51_9_fu_671_p3;
        select_ln51_reg_1412 <= select_ln51_fu_623_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer20_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer20_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer20_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer18_out_blk_n = layer18_out_empty_n;
    end else begin
        layer18_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer18_out_read = 1'b1;
    end else begin
        layer18_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer20_out_blk_n = layer20_out_full_n;
    end else begin
        layer20_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer20_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer20_out_write = 1'b1;
    end else begin
        layer20_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer20_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer18_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_10_fu_679_p2 = (($signed(trunc_ln44_8_fu_317_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_703_p2 = (($signed(trunc_ln44_9_fu_327_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_727_p2 = (($signed(trunc_ln44_1_fu_337_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_751_p2 = (($signed(trunc_ln44_2_fu_347_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_775_p2 = (($signed(trunc_ln44_3_fu_357_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_799_p2 = (($signed(trunc_ln44_4_fu_367_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_16_fu_823_p2 = (($signed(trunc_ln44_5_fu_377_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_17_fu_847_p2 = (($signed(trunc_ln44_6_fu_387_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_18_fu_871_p2 = (($signed(trunc_ln44_10_fu_397_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_19_fu_895_p2 = (($signed(trunc_ln44_11_fu_407_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_20_fu_919_p2 = (($signed(trunc_ln44_12_fu_417_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_21_fu_943_p2 = (($signed(trunc_ln44_13_fu_427_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_22_fu_967_p2 = (($signed(trunc_ln44_14_fu_437_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_23_fu_991_p2 = (($signed(trunc_ln44_15_fu_447_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_24_fu_1015_p2 = (($signed(trunc_ln44_16_fu_457_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_25_fu_1039_p2 = (($signed(trunc_ln44_17_fu_467_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_26_fu_1063_p2 = (($signed(trunc_ln44_18_fu_477_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_27_fu_1087_p2 = (($signed(trunc_ln44_19_fu_487_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_28_fu_1111_p2 = (($signed(trunc_ln44_20_fu_497_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_29_fu_1135_p2 = (($signed(trunc_ln44_21_fu_507_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_30_fu_1159_p2 = (($signed(trunc_ln44_22_fu_517_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_31_fu_1183_p2 = (($signed(trunc_ln44_23_fu_527_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_32_fu_1207_p2 = (($signed(trunc_ln44_24_fu_537_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_33_fu_1231_p2 = (($signed(trunc_ln44_25_fu_547_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_34_fu_1255_p2 = (($signed(trunc_ln44_26_fu_557_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_35_fu_1279_p2 = (($signed(trunc_ln44_27_fu_567_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_36_fu_1303_p2 = (($signed(trunc_ln44_28_fu_577_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_37_fu_1327_p2 = (($signed(trunc_ln44_29_fu_587_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_38_fu_1351_p2 = (($signed(trunc_ln44_30_fu_597_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_631_p2 = (($signed(trunc_ln44_s_fu_297_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_655_p2 = (($signed(trunc_ln44_7_fu_307_p4) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_607_p2 = (($signed(in_data_fu_293_p1) > $signed(40'd0)) ? 1'b1 : 1'b0);

assign in_data_fu_293_p1 = layer18_out_dout[39:0];

assign layer20_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_38_reg_1567}, {select_ln51_37_reg_1562}}, {select_ln51_36_reg_1557}}, {select_ln51_35_reg_1552}}, {select_ln51_34_reg_1547}}, {select_ln51_33_reg_1542}}, {select_ln51_32_reg_1537}}, {select_ln51_31_reg_1532}}, {select_ln51_30_reg_1527}}, {select_ln51_29_reg_1522}}, {select_ln51_28_reg_1517}}, {select_ln51_27_reg_1512}}, {select_ln51_26_reg_1507}}, {select_ln51_25_reg_1502}}, {select_ln51_24_reg_1497}}, {select_ln51_23_reg_1492}}, {select_ln51_22_reg_1487}}, {select_ln51_21_reg_1482}}, {select_ln51_20_reg_1477}}, {select_ln51_19_reg_1472}}, {select_ln51_18_reg_1467}}, {select_ln51_17_reg_1462}}, {select_ln51_16_reg_1457}}, {select_ln51_15_reg_1452}}, {select_ln51_14_reg_1447}}, {select_ln51_13_reg_1442}}, {select_ln51_12_reg_1437}}, {select_ln51_11_reg_1432}}, {select_ln51_10_reg_1427}}, {select_ln51_9_reg_1422}}, {select_ln51_8_reg_1417}}, {select_ln51_reg_1412}};

assign out_data_10_fu_685_p4 = {{layer18_out_dout[145:130]}};

assign out_data_8_fu_637_p4 = {{layer18_out_dout[65:50]}};

assign out_data_9_fu_661_p4 = {{layer18_out_dout[105:90]}};

assign out_data_fu_613_p4 = {{layer18_out_dout[25:10]}};

assign select_ln51_10_fu_695_p3 = ((icmp_ln51_10_fu_679_p2[0:0] == 1'b1) ? out_data_10_fu_685_p4 : 16'd0);

assign select_ln51_11_fu_719_p3 = ((icmp_ln51_11_fu_703_p2[0:0] == 1'b1) ? trunc_ln_fu_709_p4 : 16'd0);

assign select_ln51_12_fu_743_p3 = ((icmp_ln51_12_fu_727_p2[0:0] == 1'b1) ? trunc_ln52_s_fu_733_p4 : 16'd0);

assign select_ln51_13_fu_767_p3 = ((icmp_ln51_13_fu_751_p2[0:0] == 1'b1) ? trunc_ln52_3_fu_757_p4 : 16'd0);

assign select_ln51_14_fu_791_p3 = ((icmp_ln51_14_fu_775_p2[0:0] == 1'b1) ? trunc_ln52_4_fu_781_p4 : 16'd0);

assign select_ln51_15_fu_815_p3 = ((icmp_ln51_15_fu_799_p2[0:0] == 1'b1) ? trunc_ln52_5_fu_805_p4 : 16'd0);

assign select_ln51_16_fu_839_p3 = ((icmp_ln51_16_fu_823_p2[0:0] == 1'b1) ? trunc_ln52_6_fu_829_p4 : 16'd0);

assign select_ln51_17_fu_863_p3 = ((icmp_ln51_17_fu_847_p2[0:0] == 1'b1) ? trunc_ln52_7_fu_853_p4 : 16'd0);

assign select_ln51_18_fu_887_p3 = ((icmp_ln51_18_fu_871_p2[0:0] == 1'b1) ? trunc_ln52_8_fu_877_p4 : 16'd0);

assign select_ln51_19_fu_911_p3 = ((icmp_ln51_19_fu_895_p2[0:0] == 1'b1) ? trunc_ln52_9_fu_901_p4 : 16'd0);

assign select_ln51_20_fu_935_p3 = ((icmp_ln51_20_fu_919_p2[0:0] == 1'b1) ? trunc_ln52_1_fu_925_p4 : 16'd0);

assign select_ln51_21_fu_959_p3 = ((icmp_ln51_21_fu_943_p2[0:0] == 1'b1) ? trunc_ln52_2_fu_949_p4 : 16'd0);

assign select_ln51_22_fu_983_p3 = ((icmp_ln51_22_fu_967_p2[0:0] == 1'b1) ? trunc_ln52_10_fu_973_p4 : 16'd0);

assign select_ln51_23_fu_1007_p3 = ((icmp_ln51_23_fu_991_p2[0:0] == 1'b1) ? trunc_ln52_11_fu_997_p4 : 16'd0);

assign select_ln51_24_fu_1031_p3 = ((icmp_ln51_24_fu_1015_p2[0:0] == 1'b1) ? trunc_ln52_12_fu_1021_p4 : 16'd0);

assign select_ln51_25_fu_1055_p3 = ((icmp_ln51_25_fu_1039_p2[0:0] == 1'b1) ? trunc_ln52_13_fu_1045_p4 : 16'd0);

assign select_ln51_26_fu_1079_p3 = ((icmp_ln51_26_fu_1063_p2[0:0] == 1'b1) ? trunc_ln52_14_fu_1069_p4 : 16'd0);

assign select_ln51_27_fu_1103_p3 = ((icmp_ln51_27_fu_1087_p2[0:0] == 1'b1) ? trunc_ln52_15_fu_1093_p4 : 16'd0);

assign select_ln51_28_fu_1127_p3 = ((icmp_ln51_28_fu_1111_p2[0:0] == 1'b1) ? trunc_ln52_16_fu_1117_p4 : 16'd0);

assign select_ln51_29_fu_1151_p3 = ((icmp_ln51_29_fu_1135_p2[0:0] == 1'b1) ? trunc_ln52_17_fu_1141_p4 : 16'd0);

assign select_ln51_30_fu_1175_p3 = ((icmp_ln51_30_fu_1159_p2[0:0] == 1'b1) ? trunc_ln52_18_fu_1165_p4 : 16'd0);

assign select_ln51_31_fu_1199_p3 = ((icmp_ln51_31_fu_1183_p2[0:0] == 1'b1) ? trunc_ln52_19_fu_1189_p4 : 16'd0);

assign select_ln51_32_fu_1223_p3 = ((icmp_ln51_32_fu_1207_p2[0:0] == 1'b1) ? trunc_ln52_20_fu_1213_p4 : 16'd0);

assign select_ln51_33_fu_1247_p3 = ((icmp_ln51_33_fu_1231_p2[0:0] == 1'b1) ? trunc_ln52_21_fu_1237_p4 : 16'd0);

assign select_ln51_34_fu_1271_p3 = ((icmp_ln51_34_fu_1255_p2[0:0] == 1'b1) ? trunc_ln52_22_fu_1261_p4 : 16'd0);

assign select_ln51_35_fu_1295_p3 = ((icmp_ln51_35_fu_1279_p2[0:0] == 1'b1) ? trunc_ln52_23_fu_1285_p4 : 16'd0);

assign select_ln51_36_fu_1319_p3 = ((icmp_ln51_36_fu_1303_p2[0:0] == 1'b1) ? trunc_ln52_24_fu_1309_p4 : 16'd0);

assign select_ln51_37_fu_1343_p3 = ((icmp_ln51_37_fu_1327_p2[0:0] == 1'b1) ? trunc_ln52_25_fu_1333_p4 : 16'd0);

assign select_ln51_38_fu_1367_p3 = ((icmp_ln51_38_fu_1351_p2[0:0] == 1'b1) ? trunc_ln52_26_fu_1357_p4 : 16'd0);

assign select_ln51_8_fu_647_p3 = ((icmp_ln51_8_fu_631_p2[0:0] == 1'b1) ? out_data_8_fu_637_p4 : 16'd0);

assign select_ln51_9_fu_671_p3 = ((icmp_ln51_9_fu_655_p2[0:0] == 1'b1) ? out_data_9_fu_661_p4 : 16'd0);

assign select_ln51_fu_623_p3 = ((icmp_ln51_fu_607_p2[0:0] == 1'b1) ? out_data_fu_613_p4 : 16'd0);

assign start_out = real_start;

assign trunc_ln44_10_fu_397_p4 = {{layer18_out_dout[479:440]}};

assign trunc_ln44_11_fu_407_p4 = {{layer18_out_dout[519:480]}};

assign trunc_ln44_12_fu_417_p4 = {{layer18_out_dout[559:520]}};

assign trunc_ln44_13_fu_427_p4 = {{layer18_out_dout[599:560]}};

assign trunc_ln44_14_fu_437_p4 = {{layer18_out_dout[639:600]}};

assign trunc_ln44_15_fu_447_p4 = {{layer18_out_dout[679:640]}};

assign trunc_ln44_16_fu_457_p4 = {{layer18_out_dout[719:680]}};

assign trunc_ln44_17_fu_467_p4 = {{layer18_out_dout[759:720]}};

assign trunc_ln44_18_fu_477_p4 = {{layer18_out_dout[799:760]}};

assign trunc_ln44_19_fu_487_p4 = {{layer18_out_dout[839:800]}};

assign trunc_ln44_1_fu_337_p4 = {{layer18_out_dout[239:200]}};

assign trunc_ln44_20_fu_497_p4 = {{layer18_out_dout[879:840]}};

assign trunc_ln44_21_fu_507_p4 = {{layer18_out_dout[919:880]}};

assign trunc_ln44_22_fu_517_p4 = {{layer18_out_dout[959:920]}};

assign trunc_ln44_23_fu_527_p4 = {{layer18_out_dout[999:960]}};

assign trunc_ln44_24_fu_537_p4 = {{layer18_out_dout[1039:1000]}};

assign trunc_ln44_25_fu_547_p4 = {{layer18_out_dout[1079:1040]}};

assign trunc_ln44_26_fu_557_p4 = {{layer18_out_dout[1119:1080]}};

assign trunc_ln44_27_fu_567_p4 = {{layer18_out_dout[1159:1120]}};

assign trunc_ln44_28_fu_577_p4 = {{layer18_out_dout[1199:1160]}};

assign trunc_ln44_29_fu_587_p4 = {{layer18_out_dout[1239:1200]}};

assign trunc_ln44_2_fu_347_p4 = {{layer18_out_dout[279:240]}};

assign trunc_ln44_30_fu_597_p4 = {{layer18_out_dout[1279:1240]}};

assign trunc_ln44_3_fu_357_p4 = {{layer18_out_dout[319:280]}};

assign trunc_ln44_4_fu_367_p4 = {{layer18_out_dout[359:320]}};

assign trunc_ln44_5_fu_377_p4 = {{layer18_out_dout[399:360]}};

assign trunc_ln44_6_fu_387_p4 = {{layer18_out_dout[439:400]}};

assign trunc_ln44_7_fu_307_p4 = {{layer18_out_dout[119:80]}};

assign trunc_ln44_8_fu_317_p4 = {{layer18_out_dout[159:120]}};

assign trunc_ln44_9_fu_327_p4 = {{layer18_out_dout[199:160]}};

assign trunc_ln44_s_fu_297_p4 = {{layer18_out_dout[79:40]}};

assign trunc_ln52_10_fu_973_p4 = {{layer18_out_dout[625:610]}};

assign trunc_ln52_11_fu_997_p4 = {{layer18_out_dout[665:650]}};

assign trunc_ln52_12_fu_1021_p4 = {{layer18_out_dout[705:690]}};

assign trunc_ln52_13_fu_1045_p4 = {{layer18_out_dout[745:730]}};

assign trunc_ln52_14_fu_1069_p4 = {{layer18_out_dout[785:770]}};

assign trunc_ln52_15_fu_1093_p4 = {{layer18_out_dout[825:810]}};

assign trunc_ln52_16_fu_1117_p4 = {{layer18_out_dout[865:850]}};

assign trunc_ln52_17_fu_1141_p4 = {{layer18_out_dout[905:890]}};

assign trunc_ln52_18_fu_1165_p4 = {{layer18_out_dout[945:930]}};

assign trunc_ln52_19_fu_1189_p4 = {{layer18_out_dout[985:970]}};

assign trunc_ln52_1_fu_925_p4 = {{layer18_out_dout[545:530]}};

assign trunc_ln52_20_fu_1213_p4 = {{layer18_out_dout[1025:1010]}};

assign trunc_ln52_21_fu_1237_p4 = {{layer18_out_dout[1065:1050]}};

assign trunc_ln52_22_fu_1261_p4 = {{layer18_out_dout[1105:1090]}};

assign trunc_ln52_23_fu_1285_p4 = {{layer18_out_dout[1145:1130]}};

assign trunc_ln52_24_fu_1309_p4 = {{layer18_out_dout[1185:1170]}};

assign trunc_ln52_25_fu_1333_p4 = {{layer18_out_dout[1225:1210]}};

assign trunc_ln52_26_fu_1357_p4 = {{layer18_out_dout[1265:1250]}};

assign trunc_ln52_2_fu_949_p4 = {{layer18_out_dout[585:570]}};

assign trunc_ln52_3_fu_757_p4 = {{layer18_out_dout[265:250]}};

assign trunc_ln52_4_fu_781_p4 = {{layer18_out_dout[305:290]}};

assign trunc_ln52_5_fu_805_p4 = {{layer18_out_dout[345:330]}};

assign trunc_ln52_6_fu_829_p4 = {{layer18_out_dout[385:370]}};

assign trunc_ln52_7_fu_853_p4 = {{layer18_out_dout[425:410]}};

assign trunc_ln52_8_fu_877_p4 = {{layer18_out_dout[465:450]}};

assign trunc_ln52_9_fu_901_p4 = {{layer18_out_dout[505:490]}};

assign trunc_ln52_s_fu_733_p4 = {{layer18_out_dout[225:210]}};

assign trunc_ln_fu_709_p4 = {{layer18_out_dout[185:170]}};

endmodule //myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config20_s
