-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config20_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer18_out_dout : IN STD_LOGIC_VECTOR (1279 downto 0);
    layer18_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer18_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer18_out_empty_n : IN STD_LOGIC;
    layer18_out_read : OUT STD_LOGIC;
    layer20_out_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    layer20_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer20_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer20_out_full_n : IN STD_LOGIC;
    layer20_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config20_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_C7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000111";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_117 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010111";
    constant ap_const_lv32_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_167 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100111";
    constant ap_const_lv32_168 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101000";
    constant ap_const_lv32_18F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001111";
    constant ap_const_lv32_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010000";
    constant ap_const_lv32_1B7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110111";
    constant ap_const_lv32_1B8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";
    constant ap_const_lv32_207 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000000111";
    constant ap_const_lv32_208 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000001000";
    constant ap_const_lv32_22F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000101111";
    constant ap_const_lv32_230 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000110000";
    constant ap_const_lv32_257 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001010111";
    constant ap_const_lv32_258 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001011000";
    constant ap_const_lv32_27F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001111111";
    constant ap_const_lv32_280 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010000000";
    constant ap_const_lv32_2A7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010100111";
    constant ap_const_lv32_2A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010101000";
    constant ap_const_lv32_2CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011001111";
    constant ap_const_lv32_2D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011010000";
    constant ap_const_lv32_2F7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011110111";
    constant ap_const_lv32_2F8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011111000";
    constant ap_const_lv32_31F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100011111";
    constant ap_const_lv32_320 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100100000";
    constant ap_const_lv32_347 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001101000111";
    constant ap_const_lv32_348 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001101001000";
    constant ap_const_lv32_36F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001101101111";
    constant ap_const_lv32_370 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001101110000";
    constant ap_const_lv32_397 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001110010111";
    constant ap_const_lv32_398 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001110011000";
    constant ap_const_lv32_3BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001110111111";
    constant ap_const_lv32_3C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111000000";
    constant ap_const_lv32_3E7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111100111";
    constant ap_const_lv32_3E8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111101000";
    constant ap_const_lv32_40F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010000001111";
    constant ap_const_lv32_410 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010000010000";
    constant ap_const_lv32_437 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010000110111";
    constant ap_const_lv32_438 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010000111000";
    constant ap_const_lv32_45F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010001011111";
    constant ap_const_lv32_460 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010001100000";
    constant ap_const_lv32_487 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010010000111";
    constant ap_const_lv32_488 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010010001000";
    constant ap_const_lv32_4AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010010101111";
    constant ap_const_lv32_4B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010010110000";
    constant ap_const_lv32_4D7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010011010111";
    constant ap_const_lv32_4D8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010011011000";
    constant ap_const_lv32_4FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010011111111";
    constant ap_const_lv40_0 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_69 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101001";
    constant ap_const_lv32_82 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000010";
    constant ap_const_lv32_91 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010001";
    constant ap_const_lv32_AA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101010";
    constant ap_const_lv32_B9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111001";
    constant ap_const_lv32_D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010010";
    constant ap_const_lv32_E1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100001";
    constant ap_const_lv32_FA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111010";
    constant ap_const_lv32_109 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001001";
    constant ap_const_lv32_122 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100010";
    constant ap_const_lv32_131 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110001";
    constant ap_const_lv32_14A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001010";
    constant ap_const_lv32_159 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011001";
    constant ap_const_lv32_172 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110010";
    constant ap_const_lv32_181 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000001";
    constant ap_const_lv32_19A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011010";
    constant ap_const_lv32_1A9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101001";
    constant ap_const_lv32_1C2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000010";
    constant ap_const_lv32_1D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010001";
    constant ap_const_lv32_1EA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111101010";
    constant ap_const_lv32_1F9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111001";
    constant ap_const_lv32_212 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000010010";
    constant ap_const_lv32_221 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000100001";
    constant ap_const_lv32_23A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000111010";
    constant ap_const_lv32_249 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001001001";
    constant ap_const_lv32_262 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001100010";
    constant ap_const_lv32_271 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001110001";
    constant ap_const_lv32_28A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010001010";
    constant ap_const_lv32_299 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010011001";
    constant ap_const_lv32_2B2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010110010";
    constant ap_const_lv32_2C1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011000001";
    constant ap_const_lv32_2DA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011011010";
    constant ap_const_lv32_2E9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011101001";
    constant ap_const_lv32_302 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100000010";
    constant ap_const_lv32_311 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100010001";
    constant ap_const_lv32_32A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100101010";
    constant ap_const_lv32_339 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100111001";
    constant ap_const_lv32_352 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001101010010";
    constant ap_const_lv32_361 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001101100001";
    constant ap_const_lv32_37A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001101111010";
    constant ap_const_lv32_389 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001110001001";
    constant ap_const_lv32_3A2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001110100010";
    constant ap_const_lv32_3B1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001110110001";
    constant ap_const_lv32_3CA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111001010";
    constant ap_const_lv32_3D9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111011001";
    constant ap_const_lv32_3F2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111110010";
    constant ap_const_lv32_401 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010000000001";
    constant ap_const_lv32_41A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010000011010";
    constant ap_const_lv32_429 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010000101001";
    constant ap_const_lv32_442 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010001000010";
    constant ap_const_lv32_451 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010001010001";
    constant ap_const_lv32_46A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010001101010";
    constant ap_const_lv32_479 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010001111001";
    constant ap_const_lv32_492 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010010010010";
    constant ap_const_lv32_4A1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010010100001";
    constant ap_const_lv32_4BA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010010111010";
    constant ap_const_lv32_4C9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010011001001";
    constant ap_const_lv32_4E2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010011100010";
    constant ap_const_lv32_4F1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010011110001";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer18_out_blk_n : STD_LOGIC;
    signal layer20_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal select_ln51_fu_623_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_reg_1412 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal select_ln51_8_fu_647_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_8_reg_1417 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_9_fu_671_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_9_reg_1422 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_10_fu_695_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_10_reg_1427 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_11_fu_719_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_11_reg_1432 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_12_fu_743_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_12_reg_1437 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_13_fu_767_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_13_reg_1442 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_14_fu_791_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_14_reg_1447 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_15_fu_815_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_15_reg_1452 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_16_fu_839_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_16_reg_1457 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_17_fu_863_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_17_reg_1462 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_18_fu_887_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_18_reg_1467 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_19_fu_911_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_19_reg_1472 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_20_fu_935_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_20_reg_1477 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_21_fu_959_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_21_reg_1482 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_22_fu_983_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_22_reg_1487 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_23_fu_1007_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_23_reg_1492 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_24_fu_1031_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_24_reg_1497 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_25_fu_1055_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_25_reg_1502 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_26_fu_1079_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_26_reg_1507 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_27_fu_1103_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_27_reg_1512 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_28_fu_1127_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_28_reg_1517 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_29_fu_1151_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_29_reg_1522 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_30_fu_1175_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_30_reg_1527 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_31_fu_1199_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_31_reg_1532 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_32_fu_1223_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_32_reg_1537 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_33_fu_1247_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_33_reg_1542 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_34_fu_1271_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_34_reg_1547 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_35_fu_1295_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_35_reg_1552 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_36_fu_1319_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_36_reg_1557 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_37_fu_1343_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_37_reg_1562 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_38_fu_1367_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_38_reg_1567 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_data_fu_293_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_fu_613_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_s_fu_297_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_8_fu_631_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_8_fu_637_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_7_fu_307_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_9_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_9_fu_661_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_8_fu_317_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_10_fu_679_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_10_fu_685_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_9_fu_327_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_11_fu_703_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_709_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_1_fu_337_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_12_fu_727_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_s_fu_733_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_2_fu_347_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_13_fu_751_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_3_fu_757_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_3_fu_357_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_14_fu_775_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_4_fu_781_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_4_fu_367_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_15_fu_799_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_5_fu_805_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_5_fu_377_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_16_fu_823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_6_fu_829_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_6_fu_387_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_17_fu_847_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_7_fu_853_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_10_fu_397_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_18_fu_871_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_8_fu_877_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_11_fu_407_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_19_fu_895_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_9_fu_901_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_12_fu_417_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_20_fu_919_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_1_fu_925_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_13_fu_427_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_21_fu_943_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_2_fu_949_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_14_fu_437_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_22_fu_967_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_10_fu_973_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_15_fu_447_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_23_fu_991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_11_fu_997_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_16_fu_457_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_24_fu_1015_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_12_fu_1021_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_17_fu_467_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_25_fu_1039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_13_fu_1045_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_18_fu_477_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_26_fu_1063_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_14_fu_1069_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_19_fu_487_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_27_fu_1087_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_15_fu_1093_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_20_fu_497_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_28_fu_1111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_16_fu_1117_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_21_fu_507_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_29_fu_1135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_17_fu_1141_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_22_fu_517_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_30_fu_1159_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_18_fu_1165_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_23_fu_527_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_31_fu_1183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_19_fu_1189_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_24_fu_537_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_32_fu_1207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_20_fu_1213_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_25_fu_547_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_33_fu_1231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_21_fu_1237_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_26_fu_557_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_34_fu_1255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_22_fu_1261_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_27_fu_567_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_35_fu_1279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_23_fu_1285_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_28_fu_577_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_36_fu_1303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_24_fu_1309_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_29_fu_587_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_37_fu_1327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_25_fu_1333_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_30_fu_597_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln51_38_fu_1351_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_26_fu_1357_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer20_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                select_ln51_10_reg_1427 <= select_ln51_10_fu_695_p3;
                select_ln51_11_reg_1432 <= select_ln51_11_fu_719_p3;
                select_ln51_12_reg_1437 <= select_ln51_12_fu_743_p3;
                select_ln51_13_reg_1442 <= select_ln51_13_fu_767_p3;
                select_ln51_14_reg_1447 <= select_ln51_14_fu_791_p3;
                select_ln51_15_reg_1452 <= select_ln51_15_fu_815_p3;
                select_ln51_16_reg_1457 <= select_ln51_16_fu_839_p3;
                select_ln51_17_reg_1462 <= select_ln51_17_fu_863_p3;
                select_ln51_18_reg_1467 <= select_ln51_18_fu_887_p3;
                select_ln51_19_reg_1472 <= select_ln51_19_fu_911_p3;
                select_ln51_20_reg_1477 <= select_ln51_20_fu_935_p3;
                select_ln51_21_reg_1482 <= select_ln51_21_fu_959_p3;
                select_ln51_22_reg_1487 <= select_ln51_22_fu_983_p3;
                select_ln51_23_reg_1492 <= select_ln51_23_fu_1007_p3;
                select_ln51_24_reg_1497 <= select_ln51_24_fu_1031_p3;
                select_ln51_25_reg_1502 <= select_ln51_25_fu_1055_p3;
                select_ln51_26_reg_1507 <= select_ln51_26_fu_1079_p3;
                select_ln51_27_reg_1512 <= select_ln51_27_fu_1103_p3;
                select_ln51_28_reg_1517 <= select_ln51_28_fu_1127_p3;
                select_ln51_29_reg_1522 <= select_ln51_29_fu_1151_p3;
                select_ln51_30_reg_1527 <= select_ln51_30_fu_1175_p3;
                select_ln51_31_reg_1532 <= select_ln51_31_fu_1199_p3;
                select_ln51_32_reg_1537 <= select_ln51_32_fu_1223_p3;
                select_ln51_33_reg_1542 <= select_ln51_33_fu_1247_p3;
                select_ln51_34_reg_1547 <= select_ln51_34_fu_1271_p3;
                select_ln51_35_reg_1552 <= select_ln51_35_fu_1295_p3;
                select_ln51_36_reg_1557 <= select_ln51_36_fu_1319_p3;
                select_ln51_37_reg_1562 <= select_ln51_37_fu_1343_p3;
                select_ln51_38_reg_1567 <= select_ln51_38_fu_1367_p3;
                select_ln51_8_reg_1417 <= select_ln51_8_fu_647_p3;
                select_ln51_9_reg_1422 <= select_ln51_9_fu_671_p3;
                select_ln51_reg_1412 <= select_ln51_fu_623_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer20_out_full_n, ap_CS_fsm_state2, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((layer20_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(layer20_out_full_n)
    begin
        if ((layer20_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer18_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer18_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer20_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer20_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    icmp_ln51_10_fu_679_p2 <= "1" when (signed(trunc_ln44_8_fu_317_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_11_fu_703_p2 <= "1" when (signed(trunc_ln44_9_fu_327_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_12_fu_727_p2 <= "1" when (signed(trunc_ln44_1_fu_337_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_13_fu_751_p2 <= "1" when (signed(trunc_ln44_2_fu_347_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_14_fu_775_p2 <= "1" when (signed(trunc_ln44_3_fu_357_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_15_fu_799_p2 <= "1" when (signed(trunc_ln44_4_fu_367_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_16_fu_823_p2 <= "1" when (signed(trunc_ln44_5_fu_377_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_17_fu_847_p2 <= "1" when (signed(trunc_ln44_6_fu_387_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_18_fu_871_p2 <= "1" when (signed(trunc_ln44_10_fu_397_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_19_fu_895_p2 <= "1" when (signed(trunc_ln44_11_fu_407_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_20_fu_919_p2 <= "1" when (signed(trunc_ln44_12_fu_417_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_21_fu_943_p2 <= "1" when (signed(trunc_ln44_13_fu_427_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_22_fu_967_p2 <= "1" when (signed(trunc_ln44_14_fu_437_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_23_fu_991_p2 <= "1" when (signed(trunc_ln44_15_fu_447_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_24_fu_1015_p2 <= "1" when (signed(trunc_ln44_16_fu_457_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_25_fu_1039_p2 <= "1" when (signed(trunc_ln44_17_fu_467_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_26_fu_1063_p2 <= "1" when (signed(trunc_ln44_18_fu_477_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_27_fu_1087_p2 <= "1" when (signed(trunc_ln44_19_fu_487_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_28_fu_1111_p2 <= "1" when (signed(trunc_ln44_20_fu_497_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_29_fu_1135_p2 <= "1" when (signed(trunc_ln44_21_fu_507_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_30_fu_1159_p2 <= "1" when (signed(trunc_ln44_22_fu_517_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_31_fu_1183_p2 <= "1" when (signed(trunc_ln44_23_fu_527_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_32_fu_1207_p2 <= "1" when (signed(trunc_ln44_24_fu_537_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_33_fu_1231_p2 <= "1" when (signed(trunc_ln44_25_fu_547_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_34_fu_1255_p2 <= "1" when (signed(trunc_ln44_26_fu_557_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_35_fu_1279_p2 <= "1" when (signed(trunc_ln44_27_fu_567_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_36_fu_1303_p2 <= "1" when (signed(trunc_ln44_28_fu_577_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_37_fu_1327_p2 <= "1" when (signed(trunc_ln44_29_fu_587_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_38_fu_1351_p2 <= "1" when (signed(trunc_ln44_30_fu_597_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_8_fu_631_p2 <= "1" when (signed(trunc_ln44_s_fu_297_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_9_fu_655_p2 <= "1" when (signed(trunc_ln44_7_fu_307_p4) > signed(ap_const_lv40_0)) else "0";
    icmp_ln51_fu_607_p2 <= "1" when (signed(in_data_fu_293_p1) > signed(ap_const_lv40_0)) else "0";
    in_data_fu_293_p1 <= layer18_out_dout(40 - 1 downto 0);

    internal_ap_ready_assign_proc : process(layer20_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer20_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer18_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer18_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer18_out_blk_n <= layer18_out_empty_n;
        else 
            layer18_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer18_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer18_out_read <= ap_const_logic_1;
        else 
            layer18_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer20_out_blk_n_assign_proc : process(layer20_out_full_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer20_out_blk_n <= layer20_out_full_n;
        else 
            layer20_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer20_out_din <= (((((((((((((((((((((((((((((((select_ln51_38_reg_1567 & select_ln51_37_reg_1562) & select_ln51_36_reg_1557) & select_ln51_35_reg_1552) & select_ln51_34_reg_1547) & select_ln51_33_reg_1542) & select_ln51_32_reg_1537) & select_ln51_31_reg_1532) & select_ln51_30_reg_1527) & select_ln51_29_reg_1522) & select_ln51_28_reg_1517) & select_ln51_27_reg_1512) & select_ln51_26_reg_1507) & select_ln51_25_reg_1502) & select_ln51_24_reg_1497) & select_ln51_23_reg_1492) & select_ln51_22_reg_1487) & select_ln51_21_reg_1482) & select_ln51_20_reg_1477) & select_ln51_19_reg_1472) & select_ln51_18_reg_1467) & select_ln51_17_reg_1462) & select_ln51_16_reg_1457) & select_ln51_15_reg_1452) & select_ln51_14_reg_1447) & select_ln51_13_reg_1442) & select_ln51_12_reg_1437) & select_ln51_11_reg_1432) & select_ln51_10_reg_1427) & select_ln51_9_reg_1422) & select_ln51_8_reg_1417) & select_ln51_reg_1412);

    layer20_out_write_assign_proc : process(layer20_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer20_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer20_out_write <= ap_const_logic_1;
        else 
            layer20_out_write <= ap_const_logic_0;
        end if; 
    end process;

    out_data_10_fu_685_p4 <= layer18_out_dout(145 downto 130);
    out_data_8_fu_637_p4 <= layer18_out_dout(65 downto 50);
    out_data_9_fu_661_p4 <= layer18_out_dout(105 downto 90);
    out_data_fu_613_p4 <= layer18_out_dout(25 downto 10);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_10_fu_695_p3 <= 
        out_data_10_fu_685_p4 when (icmp_ln51_10_fu_679_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_11_fu_719_p3 <= 
        trunc_ln_fu_709_p4 when (icmp_ln51_11_fu_703_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_12_fu_743_p3 <= 
        trunc_ln52_s_fu_733_p4 when (icmp_ln51_12_fu_727_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_13_fu_767_p3 <= 
        trunc_ln52_3_fu_757_p4 when (icmp_ln51_13_fu_751_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_14_fu_791_p3 <= 
        trunc_ln52_4_fu_781_p4 when (icmp_ln51_14_fu_775_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_15_fu_815_p3 <= 
        trunc_ln52_5_fu_805_p4 when (icmp_ln51_15_fu_799_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_16_fu_839_p3 <= 
        trunc_ln52_6_fu_829_p4 when (icmp_ln51_16_fu_823_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_17_fu_863_p3 <= 
        trunc_ln52_7_fu_853_p4 when (icmp_ln51_17_fu_847_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_18_fu_887_p3 <= 
        trunc_ln52_8_fu_877_p4 when (icmp_ln51_18_fu_871_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_19_fu_911_p3 <= 
        trunc_ln52_9_fu_901_p4 when (icmp_ln51_19_fu_895_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_20_fu_935_p3 <= 
        trunc_ln52_1_fu_925_p4 when (icmp_ln51_20_fu_919_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_21_fu_959_p3 <= 
        trunc_ln52_2_fu_949_p4 when (icmp_ln51_21_fu_943_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_22_fu_983_p3 <= 
        trunc_ln52_10_fu_973_p4 when (icmp_ln51_22_fu_967_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_23_fu_1007_p3 <= 
        trunc_ln52_11_fu_997_p4 when (icmp_ln51_23_fu_991_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_24_fu_1031_p3 <= 
        trunc_ln52_12_fu_1021_p4 when (icmp_ln51_24_fu_1015_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_25_fu_1055_p3 <= 
        trunc_ln52_13_fu_1045_p4 when (icmp_ln51_25_fu_1039_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_26_fu_1079_p3 <= 
        trunc_ln52_14_fu_1069_p4 when (icmp_ln51_26_fu_1063_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_27_fu_1103_p3 <= 
        trunc_ln52_15_fu_1093_p4 when (icmp_ln51_27_fu_1087_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_28_fu_1127_p3 <= 
        trunc_ln52_16_fu_1117_p4 when (icmp_ln51_28_fu_1111_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_29_fu_1151_p3 <= 
        trunc_ln52_17_fu_1141_p4 when (icmp_ln51_29_fu_1135_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_30_fu_1175_p3 <= 
        trunc_ln52_18_fu_1165_p4 when (icmp_ln51_30_fu_1159_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_31_fu_1199_p3 <= 
        trunc_ln52_19_fu_1189_p4 when (icmp_ln51_31_fu_1183_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_32_fu_1223_p3 <= 
        trunc_ln52_20_fu_1213_p4 when (icmp_ln51_32_fu_1207_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_33_fu_1247_p3 <= 
        trunc_ln52_21_fu_1237_p4 when (icmp_ln51_33_fu_1231_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_34_fu_1271_p3 <= 
        trunc_ln52_22_fu_1261_p4 when (icmp_ln51_34_fu_1255_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_35_fu_1295_p3 <= 
        trunc_ln52_23_fu_1285_p4 when (icmp_ln51_35_fu_1279_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_36_fu_1319_p3 <= 
        trunc_ln52_24_fu_1309_p4 when (icmp_ln51_36_fu_1303_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_37_fu_1343_p3 <= 
        trunc_ln52_25_fu_1333_p4 when (icmp_ln51_37_fu_1327_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_38_fu_1367_p3 <= 
        trunc_ln52_26_fu_1357_p4 when (icmp_ln51_38_fu_1351_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_8_fu_647_p3 <= 
        out_data_8_fu_637_p4 when (icmp_ln51_8_fu_631_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_9_fu_671_p3 <= 
        out_data_9_fu_661_p4 when (icmp_ln51_9_fu_655_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_fu_623_p3 <= 
        out_data_fu_613_p4 when (icmp_ln51_fu_607_p2(0) = '1') else 
        ap_const_lv16_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln44_10_fu_397_p4 <= layer18_out_dout(479 downto 440);
    trunc_ln44_11_fu_407_p4 <= layer18_out_dout(519 downto 480);
    trunc_ln44_12_fu_417_p4 <= layer18_out_dout(559 downto 520);
    trunc_ln44_13_fu_427_p4 <= layer18_out_dout(599 downto 560);
    trunc_ln44_14_fu_437_p4 <= layer18_out_dout(639 downto 600);
    trunc_ln44_15_fu_447_p4 <= layer18_out_dout(679 downto 640);
    trunc_ln44_16_fu_457_p4 <= layer18_out_dout(719 downto 680);
    trunc_ln44_17_fu_467_p4 <= layer18_out_dout(759 downto 720);
    trunc_ln44_18_fu_477_p4 <= layer18_out_dout(799 downto 760);
    trunc_ln44_19_fu_487_p4 <= layer18_out_dout(839 downto 800);
    trunc_ln44_1_fu_337_p4 <= layer18_out_dout(239 downto 200);
    trunc_ln44_20_fu_497_p4 <= layer18_out_dout(879 downto 840);
    trunc_ln44_21_fu_507_p4 <= layer18_out_dout(919 downto 880);
    trunc_ln44_22_fu_517_p4 <= layer18_out_dout(959 downto 920);
    trunc_ln44_23_fu_527_p4 <= layer18_out_dout(999 downto 960);
    trunc_ln44_24_fu_537_p4 <= layer18_out_dout(1039 downto 1000);
    trunc_ln44_25_fu_547_p4 <= layer18_out_dout(1079 downto 1040);
    trunc_ln44_26_fu_557_p4 <= layer18_out_dout(1119 downto 1080);
    trunc_ln44_27_fu_567_p4 <= layer18_out_dout(1159 downto 1120);
    trunc_ln44_28_fu_577_p4 <= layer18_out_dout(1199 downto 1160);
    trunc_ln44_29_fu_587_p4 <= layer18_out_dout(1239 downto 1200);
    trunc_ln44_2_fu_347_p4 <= layer18_out_dout(279 downto 240);
    trunc_ln44_30_fu_597_p4 <= layer18_out_dout(1279 downto 1240);
    trunc_ln44_3_fu_357_p4 <= layer18_out_dout(319 downto 280);
    trunc_ln44_4_fu_367_p4 <= layer18_out_dout(359 downto 320);
    trunc_ln44_5_fu_377_p4 <= layer18_out_dout(399 downto 360);
    trunc_ln44_6_fu_387_p4 <= layer18_out_dout(439 downto 400);
    trunc_ln44_7_fu_307_p4 <= layer18_out_dout(119 downto 80);
    trunc_ln44_8_fu_317_p4 <= layer18_out_dout(159 downto 120);
    trunc_ln44_9_fu_327_p4 <= layer18_out_dout(199 downto 160);
    trunc_ln44_s_fu_297_p4 <= layer18_out_dout(79 downto 40);
    trunc_ln52_10_fu_973_p4 <= layer18_out_dout(625 downto 610);
    trunc_ln52_11_fu_997_p4 <= layer18_out_dout(665 downto 650);
    trunc_ln52_12_fu_1021_p4 <= layer18_out_dout(705 downto 690);
    trunc_ln52_13_fu_1045_p4 <= layer18_out_dout(745 downto 730);
    trunc_ln52_14_fu_1069_p4 <= layer18_out_dout(785 downto 770);
    trunc_ln52_15_fu_1093_p4 <= layer18_out_dout(825 downto 810);
    trunc_ln52_16_fu_1117_p4 <= layer18_out_dout(865 downto 850);
    trunc_ln52_17_fu_1141_p4 <= layer18_out_dout(905 downto 890);
    trunc_ln52_18_fu_1165_p4 <= layer18_out_dout(945 downto 930);
    trunc_ln52_19_fu_1189_p4 <= layer18_out_dout(985 downto 970);
    trunc_ln52_1_fu_925_p4 <= layer18_out_dout(545 downto 530);
    trunc_ln52_20_fu_1213_p4 <= layer18_out_dout(1025 downto 1010);
    trunc_ln52_21_fu_1237_p4 <= layer18_out_dout(1065 downto 1050);
    trunc_ln52_22_fu_1261_p4 <= layer18_out_dout(1105 downto 1090);
    trunc_ln52_23_fu_1285_p4 <= layer18_out_dout(1145 downto 1130);
    trunc_ln52_24_fu_1309_p4 <= layer18_out_dout(1185 downto 1170);
    trunc_ln52_25_fu_1333_p4 <= layer18_out_dout(1225 downto 1210);
    trunc_ln52_26_fu_1357_p4 <= layer18_out_dout(1265 downto 1250);
    trunc_ln52_2_fu_949_p4 <= layer18_out_dout(585 downto 570);
    trunc_ln52_3_fu_757_p4 <= layer18_out_dout(265 downto 250);
    trunc_ln52_4_fu_781_p4 <= layer18_out_dout(305 downto 290);
    trunc_ln52_5_fu_805_p4 <= layer18_out_dout(345 downto 330);
    trunc_ln52_6_fu_829_p4 <= layer18_out_dout(385 downto 370);
    trunc_ln52_7_fu_853_p4 <= layer18_out_dout(425 downto 410);
    trunc_ln52_8_fu_877_p4 <= layer18_out_dout(465 downto 450);
    trunc_ln52_9_fu_901_p4 <= layer18_out_dout(505 downto 490);
    trunc_ln52_s_fu_733_p4 <= layer18_out_dout(225 downto 210);
    trunc_ln_fu_709_p4 <= layer18_out_dout(185 downto 170);
end behav;
