-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_axi_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config23_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer21_out_dout : IN STD_LOGIC_VECTOR (129 downto 0);
    layer21_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer21_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer21_out_empty_n : IN STD_LOGIC;
    layer21_out_read : OUT STD_LOGIC;
    output_local_din : OUT STD_LOGIC_VECTOR (159 downto 0);
    output_local_full_n : IN STD_LOGIC;
    output_local_write : OUT STD_LOGIC );
end;


architecture behav of myproject_axi_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config23_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_5B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011011";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110100";
    constant ap_const_lv32_75 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110101";
    constant ap_const_lv32_81 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_4C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001100";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv32_66 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100110";
    constant ap_const_lv32_73 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110011";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal invert_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table_ce0 : STD_LOGIC;
    signal invert_table_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal layer21_out_blk_n : STD_LOGIC;
    signal output_local_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal data_array_8_reg_1397 : STD_LOGIC_VECTOR (12 downto 0);
    signal data_array_9_reg_1403 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln66_fu_726_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln66_reg_1409 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln66_1_fu_746_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln66_1_reg_1415 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln66_3_fu_766_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln66_3_reg_1421 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln66_4_fu_786_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln66_4_reg_1427 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln213_fu_794_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln213_reg_1433 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln213_2_reg_1438 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln213_3_reg_1443 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln213_4_reg_1448 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln213_5_reg_1453 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln213_6_reg_1458 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln213_7_reg_1463 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln213_8_reg_1468 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln213_9_reg_1473 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln213_s_reg_1478 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln66_8_fu_976_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln66_8_reg_1483 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_1_reg_1507 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_2_reg_1512 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_3_reg_1517 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_reg_1522 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_5_reg_1527 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_6_reg_1532 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_reg_1537 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_8_reg_1542 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal exp_res_reg_1547 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal exp_table_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal exp_res_1_reg_1553 : STD_LOGIC_VECTOR (15 downto 0);
    signal exp_res_2_reg_1569 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal exp_res_3_reg_1575 : STD_LOGIC_VECTOR (15 downto 0);
    signal exp_res_4_reg_1591 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal exp_res_5_reg_1597 : STD_LOGIC_VECTOR (15 downto 0);
    signal exp_res_6_reg_1613 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal exp_res_7_reg_1619 : STD_LOGIC_VECTOR (15 downto 0);
    signal exp_res_8_reg_1635 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal exp_res_9_reg_1641 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal inv_exp_sum_reg_1652 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal trunc_ln1_reg_1657 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal trunc_ln241_1_reg_1662 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_2_reg_1667 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_3_reg_1672 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_4_reg_1677 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_5_reg_1682 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_6_reg_1687 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_7_reg_1692 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_8_reg_1697 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln241_9_reg_1702 : STD_LOGIC_VECTOR (15 downto 0);
    signal exp_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce0 : STD_LOGIC;
    signal exp_table_we0 : STD_LOGIC;
    signal exp_table_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce1 : STD_LOGIC;
    signal grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_start : STD_LOGIC;
    signal grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_done : STD_LOGIC;
    signal grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_idle : STD_LOGIC;
    signal grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_ready : STD_LOGIC;
    signal grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_ce0 : STD_LOGIC;
    signal grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_we0 : STD_LOGIC;
    signal grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call3 : BOOLEAN;
    signal zext_ln223_fu_1034_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_1_fu_1049_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_2_fu_1134_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_3_fu_1138_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_4_fu_1142_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_5_fu_1146_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_6_fu_1150_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_7_fu_1154_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_8_fu_1158_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_9_fu_1162_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln232_fu_1224_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal mul_ln241_fu_243_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln241_fu_1229_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_2_fu_244_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_4_fu_245_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_6_fu_246_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_3_fu_247_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_7_fu_248_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_5_fu_249_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_1_fu_250_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_8_fu_251_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln241_9_fu_252_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal data_array_fu_620_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal data_array_1_fu_624_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln66_fu_714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_array_2_fu_634_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal data_array_3_fu_644_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln66_1_fu_734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_1_fu_740_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_array_4_fu_654_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal data_array_5_fu_664_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln66_3_fu_754_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_3_fu_760_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_array_6_fu_674_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal data_array_7_fu_684_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln66_4_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_4_fu_780_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_2_fu_888_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_2_fu_892_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_5_fu_904_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_5_fu_908_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_2_fu_898_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln66_5_fu_914_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln66_6_fu_920_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_6_fu_926_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_7_fu_940_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_7_fu_944_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_6_fu_932_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln66_7_fu_950_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln66_8_fu_956_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_8_fu_962_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_fu_968_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln66_1_fu_972_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal d_xi_xmax_fu_984_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_fu_1024_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal d_xi_xmax_10_fu_988_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_s_fu_1039_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal d_xi_xmax_11_fu_992_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal d_xi_xmax_12_fu_996_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal d_xi_xmax_13_fu_1000_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal d_xi_xmax_14_fu_1004_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal d_xi_xmax_15_fu_1008_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal d_xi_xmax_16_fu_1012_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal d_xi_xmax_17_fu_1016_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal d_xi_xmax_18_fu_1020_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_1_fu_1170_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_3_fu_1174_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_fu_1166_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_6_fu_1189_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_7_fu_1193_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_5_fu_1185_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_8_fu_1198_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_4_fu_1179_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_2_fu_1204_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_1210_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln232_fu_1220_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln241_fu_243_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_1_fu_250_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_2_fu_244_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_3_fu_247_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_4_fu_245_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_5_fu_249_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_6_fu_246_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_7_fu_248_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_8_fu_251_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln241_9_fu_252_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_axi_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        table_out_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        table_out_ce0 : OUT STD_LOGIC;
        table_out_we0 : OUT STD_LOGIC;
        table_out_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component myproject_axi_mul_18s_16s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_axi_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config23_s_invert_bxn IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component myproject_axi_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config23_s_exp_tabbyn IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    invert_table_U : component myproject_axi_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config23_s_invert_bxn
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table_address0,
        ce0 => invert_table_ce0,
        q0 => invert_table_q0);

    exp_table_U : component myproject_axi_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config23_s_exp_tabbyn
    generic map (
        DataWidth => 16,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table_address0,
        ce0 => exp_table_ce0,
        we0 => exp_table_we0,
        d0 => grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_d0,
        q0 => exp_table_q0,
        address1 => exp_table_address1,
        ce1 => exp_table_ce1,
        q1 => exp_table_q1);

    grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614 : component myproject_axi_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_start,
        ap_done => grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_done,
        ap_idle => grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_idle,
        ap_ready => grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_ready,
        table_out_address0 => grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_address0,
        table_out_ce0 => grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_ce0,
        table_out_we0 => grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_we0,
        table_out_d0 => grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_d0);

    mul_18s_16s_26_1_1_U740 : component myproject_axi_mul_18s_16s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_fu_243_p0,
        din1 => exp_res_reg_1547,
        dout => mul_ln241_fu_243_p2);

    mul_18s_16s_26_1_1_U741 : component myproject_axi_mul_18s_16s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_2_fu_244_p0,
        din1 => exp_res_2_reg_1569,
        dout => mul_ln241_2_fu_244_p2);

    mul_18s_16s_26_1_1_U742 : component myproject_axi_mul_18s_16s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_4_fu_245_p0,
        din1 => exp_res_4_reg_1591,
        dout => mul_ln241_4_fu_245_p2);

    mul_18s_16s_26_1_1_U743 : component myproject_axi_mul_18s_16s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_6_fu_246_p0,
        din1 => exp_res_6_reg_1613,
        dout => mul_ln241_6_fu_246_p2);

    mul_18s_16s_26_1_1_U744 : component myproject_axi_mul_18s_16s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_3_fu_247_p0,
        din1 => exp_res_3_reg_1575,
        dout => mul_ln241_3_fu_247_p2);

    mul_18s_16s_26_1_1_U745 : component myproject_axi_mul_18s_16s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_7_fu_248_p0,
        din1 => exp_res_7_reg_1619,
        dout => mul_ln241_7_fu_248_p2);

    mul_18s_16s_26_1_1_U746 : component myproject_axi_mul_18s_16s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_5_fu_249_p0,
        din1 => exp_res_5_reg_1597,
        dout => mul_ln241_5_fu_249_p2);

    mul_18s_16s_26_1_1_U747 : component myproject_axi_mul_18s_16s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_1_fu_250_p0,
        din1 => exp_res_1_reg_1553,
        dout => mul_ln241_1_fu_250_p2);

    mul_18s_16s_26_1_1_U748 : component myproject_axi_mul_18s_16s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_8_fu_251_p0,
        din1 => exp_res_8_reg_1635,
        dout => mul_ln241_8_fu_251_p2);

    mul_18s_16s_26_1_1_U749 : component myproject_axi_mul_18s_16s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln241_9_fu_252_p0,
        din1 => exp_res_9_reg_1641,
        dout => mul_ln241_9_fu_252_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_ready = ap_const_logic_1)) then 
                    grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                data_array_8_reg_1397 <= layer21_out_dout(116 downto 104);
                data_array_9_reg_1403 <= layer21_out_dout(129 downto 117);
                select_ln66_1_reg_1415 <= select_ln66_1_fu_746_p3;
                select_ln66_3_reg_1421 <= select_ln66_3_fu_766_p3;
                select_ln66_4_reg_1427 <= select_ln66_4_fu_786_p3;
                select_ln66_reg_1409 <= select_ln66_fu_726_p3;
                trunc_ln213_2_reg_1438 <= layer21_out_dout(24 downto 13);
                trunc_ln213_3_reg_1443 <= layer21_out_dout(37 downto 26);
                trunc_ln213_4_reg_1448 <= layer21_out_dout(50 downto 39);
                trunc_ln213_5_reg_1453 <= layer21_out_dout(63 downto 52);
                trunc_ln213_6_reg_1458 <= layer21_out_dout(76 downto 65);
                trunc_ln213_7_reg_1463 <= layer21_out_dout(89 downto 78);
                trunc_ln213_8_reg_1468 <= layer21_out_dout(102 downto 91);
                trunc_ln213_9_reg_1473 <= layer21_out_dout(115 downto 104);
                trunc_ln213_reg_1433 <= trunc_ln213_fu_794_p1;
                trunc_ln213_s_reg_1478 <= layer21_out_dout(128 downto 117);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                exp_res_1_reg_1553 <= exp_table_q0;
                exp_res_reg_1547 <= exp_table_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                exp_res_2_reg_1569 <= exp_table_q1;
                exp_res_3_reg_1575 <= exp_table_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                exp_res_4_reg_1591 <= exp_table_q1;
                exp_res_5_reg_1597 <= exp_table_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                exp_res_6_reg_1613 <= exp_table_q1;
                exp_res_7_reg_1619 <= exp_table_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                exp_res_8_reg_1635 <= exp_table_q1;
                exp_res_9_reg_1641 <= exp_table_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                inv_exp_sum_reg_1652 <= invert_table_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                select_ln66_8_reg_1483 <= select_ln66_8_fu_976_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                tmp_1_reg_1507 <= d_xi_xmax_11_fu_992_p2(11 downto 2);
                tmp_2_reg_1512 <= d_xi_xmax_12_fu_996_p2(11 downto 2);
                tmp_3_reg_1517 <= d_xi_xmax_13_fu_1000_p2(11 downto 2);
                tmp_4_reg_1522 <= d_xi_xmax_14_fu_1004_p2(11 downto 2);
                tmp_5_reg_1527 <= d_xi_xmax_15_fu_1008_p2(11 downto 2);
                tmp_6_reg_1532 <= d_xi_xmax_16_fu_1012_p2(11 downto 2);
                tmp_7_reg_1537 <= d_xi_xmax_17_fu_1016_p2(11 downto 2);
                tmp_8_reg_1542 <= d_xi_xmax_18_fu_1020_p2(11 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                trunc_ln1_reg_1657 <= mul_ln241_fu_243_p2(25 downto 10);
                trunc_ln241_1_reg_1662 <= mul_ln241_1_fu_250_p2(25 downto 10);
                trunc_ln241_2_reg_1667 <= mul_ln241_2_fu_244_p2(25 downto 10);
                trunc_ln241_3_reg_1672 <= mul_ln241_3_fu_247_p2(25 downto 10);
                trunc_ln241_4_reg_1677 <= mul_ln241_4_fu_245_p2(25 downto 10);
                trunc_ln241_5_reg_1682 <= mul_ln241_5_fu_249_p2(25 downto 10);
                trunc_ln241_6_reg_1687 <= mul_ln241_6_fu_246_p2(25 downto 10);
                trunc_ln241_7_reg_1692 <= mul_ln241_7_fu_248_p2(25 downto 10);
                trunc_ln241_8_reg_1697 <= mul_ln241_8_fu_251_p2(25 downto 10);
                trunc_ln241_9_reg_1702 <= mul_ln241_9_fu_252_p2(25 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, output_local_full_n, ap_CS_fsm_state12, ap_CS_fsm_state2, grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_done, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((output_local_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    add_ln51_1_fu_1170_p2 <= std_logic_vector(signed(exp_res_6_reg_1613) + signed(exp_res_4_reg_1591));
    add_ln51_2_fu_1204_p2 <= std_logic_vector(unsigned(add_ln51_8_fu_1198_p2) + unsigned(add_ln51_4_fu_1179_p2));
    add_ln51_3_fu_1174_p2 <= std_logic_vector(unsigned(add_ln51_1_fu_1170_p2) + unsigned(exp_res_7_reg_1619));
    add_ln51_4_fu_1179_p2 <= std_logic_vector(unsigned(add_ln51_3_fu_1174_p2) + unsigned(add_ln51_fu_1166_p2));
    add_ln51_5_fu_1185_p2 <= std_logic_vector(signed(exp_res_5_reg_1597) + signed(exp_res_3_reg_1575));
    add_ln51_6_fu_1189_p2 <= std_logic_vector(signed(exp_res_reg_1547) + signed(exp_res_1_reg_1553));
    add_ln51_7_fu_1193_p2 <= std_logic_vector(unsigned(add_ln51_6_fu_1189_p2) + unsigned(exp_res_2_reg_1569));
    add_ln51_8_fu_1198_p2 <= std_logic_vector(unsigned(add_ln51_7_fu_1193_p2) + unsigned(add_ln51_5_fu_1185_p2));
    add_ln51_fu_1166_p2 <= std_logic_vector(signed(exp_res_9_reg_1641) + signed(exp_res_8_reg_1635));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(output_local_full_n)
    begin
        if ((output_local_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_done)
    begin
        if ((grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, layer21_out_empty_n)
    begin
                ap_block_state1 <= ((layer21_out_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call3_assign_proc : process(ap_start, layer21_out_empty_n)
    begin
                ap_block_state1_ignore_call3 <= ((layer21_out_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, output_local_full_n, ap_CS_fsm_state12)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((output_local_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(output_local_full_n, ap_CS_fsm_state12)
    begin
        if (((output_local_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    d_xi_xmax_10_fu_988_p2 <= std_logic_vector(unsigned(select_ln66_8_reg_1483) - unsigned(trunc_ln213_2_reg_1438));
    d_xi_xmax_11_fu_992_p2 <= std_logic_vector(unsigned(select_ln66_8_reg_1483) - unsigned(trunc_ln213_3_reg_1443));
    d_xi_xmax_12_fu_996_p2 <= std_logic_vector(unsigned(select_ln66_8_reg_1483) - unsigned(trunc_ln213_4_reg_1448));
    d_xi_xmax_13_fu_1000_p2 <= std_logic_vector(unsigned(select_ln66_8_reg_1483) - unsigned(trunc_ln213_5_reg_1453));
    d_xi_xmax_14_fu_1004_p2 <= std_logic_vector(unsigned(select_ln66_8_reg_1483) - unsigned(trunc_ln213_6_reg_1458));
    d_xi_xmax_15_fu_1008_p2 <= std_logic_vector(unsigned(select_ln66_8_reg_1483) - unsigned(trunc_ln213_7_reg_1463));
    d_xi_xmax_16_fu_1012_p2 <= std_logic_vector(unsigned(select_ln66_8_reg_1483) - unsigned(trunc_ln213_8_reg_1468));
    d_xi_xmax_17_fu_1016_p2 <= std_logic_vector(unsigned(select_ln66_8_reg_1483) - unsigned(trunc_ln213_9_reg_1473));
    d_xi_xmax_18_fu_1020_p2 <= std_logic_vector(unsigned(select_ln66_8_reg_1483) - unsigned(trunc_ln213_s_reg_1478));
    d_xi_xmax_fu_984_p2 <= std_logic_vector(unsigned(select_ln66_8_reg_1483) - unsigned(trunc_ln213_reg_1433));
    data_array_1_fu_624_p4 <= layer21_out_dout(25 downto 13);
    data_array_2_fu_634_p4 <= layer21_out_dout(38 downto 26);
    data_array_3_fu_644_p4 <= layer21_out_dout(51 downto 39);
    data_array_4_fu_654_p4 <= layer21_out_dout(64 downto 52);
    data_array_5_fu_664_p4 <= layer21_out_dout(77 downto 65);
    data_array_6_fu_674_p4 <= layer21_out_dout(90 downto 78);
    data_array_7_fu_684_p4 <= layer21_out_dout(103 downto 91);
    data_array_fu_620_p1 <= layer21_out_dout(13 - 1 downto 0);

    exp_table_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_address0, zext_ln223_1_fu_1049_p1, zext_ln223_3_fu_1138_p1, zext_ln223_5_fu_1146_p1, zext_ln223_7_fu_1154_p1, zext_ln223_9_fu_1162_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            exp_table_address0 <= zext_ln223_9_fu_1162_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            exp_table_address0 <= zext_ln223_7_fu_1154_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            exp_table_address0 <= zext_ln223_5_fu_1146_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            exp_table_address0 <= zext_ln223_3_fu_1138_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            exp_table_address0 <= zext_ln223_1_fu_1049_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            exp_table_address0 <= grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_address0;
        else 
            exp_table_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    exp_table_address1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, zext_ln223_fu_1034_p1, zext_ln223_2_fu_1134_p1, zext_ln223_4_fu_1142_p1, zext_ln223_6_fu_1150_p1, zext_ln223_8_fu_1158_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            exp_table_address1 <= zext_ln223_8_fu_1158_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            exp_table_address1 <= zext_ln223_6_fu_1150_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            exp_table_address1 <= zext_ln223_4_fu_1142_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            exp_table_address1 <= zext_ln223_2_fu_1134_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            exp_table_address1 <= zext_ln223_fu_1034_p1(10 - 1 downto 0);
        else 
            exp_table_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    exp_table_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_ce0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            exp_table_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            exp_table_ce0 <= grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_ce0;
        else 
            exp_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            exp_table_ce1 <= ap_const_logic_1;
        else 
            exp_table_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_we0_assign_proc : process(ap_CS_fsm_state2, grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            exp_table_we0 <= grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_table_out_we0;
        else 
            exp_table_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_start <= grp_init_exp_table_ap_ufixed_12_10_5_3_0_softmax_config23_s_fu_614_ap_start_reg;
    icmp_ln66_1_fu_734_p2 <= "1" when (signed(data_array_2_fu_634_p4) < signed(data_array_3_fu_644_p4)) else "0";
    icmp_ln66_2_fu_888_p2 <= "1" when (signed(select_ln66_reg_1409) < signed(select_ln66_1_reg_1415)) else "0";
    icmp_ln66_3_fu_754_p2 <= "1" when (signed(data_array_4_fu_654_p4) < signed(data_array_5_fu_664_p4)) else "0";
    icmp_ln66_4_fu_774_p2 <= "1" when (signed(data_array_6_fu_674_p4) < signed(data_array_7_fu_684_p4)) else "0";
    icmp_ln66_5_fu_904_p2 <= "1" when (signed(select_ln66_3_reg_1421) < signed(select_ln66_4_reg_1427)) else "0";
    icmp_ln66_6_fu_920_p2 <= "1" when (signed(select_ln66_2_fu_898_p3) < signed(select_ln66_5_fu_914_p3)) else "0";
    icmp_ln66_7_fu_940_p2 <= "1" when (signed(data_array_8_reg_1397) < signed(data_array_9_reg_1403)) else "0";
    icmp_ln66_8_fu_956_p2 <= "1" when (signed(select_ln66_6_fu_932_p3) < signed(select_ln66_7_fu_950_p3)) else "0";
    icmp_ln66_fu_714_p2 <= "1" when (signed(data_array_fu_620_p1) < signed(data_array_1_fu_624_p4)) else "0";
    invert_table_address0 <= zext_ln232_fu_1224_p1(10 - 1 downto 0);

    invert_table_ce0_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            invert_table_ce0 <= ap_const_logic_1;
        else 
            invert_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    layer21_out_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, layer21_out_empty_n)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            layer21_out_blk_n <= layer21_out_empty_n;
        else 
            layer21_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer21_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer21_out_read <= ap_const_logic_1;
        else 
            layer21_out_read <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln241_1_fu_250_p0 <= sext_ln241_fu_1229_p1(18 - 1 downto 0);
    mul_ln241_2_fu_244_p0 <= sext_ln241_fu_1229_p1(18 - 1 downto 0);
    mul_ln241_3_fu_247_p0 <= sext_ln241_fu_1229_p1(18 - 1 downto 0);
    mul_ln241_4_fu_245_p0 <= sext_ln241_fu_1229_p1(18 - 1 downto 0);
    mul_ln241_5_fu_249_p0 <= sext_ln241_fu_1229_p1(18 - 1 downto 0);
    mul_ln241_6_fu_246_p0 <= sext_ln241_fu_1229_p1(18 - 1 downto 0);
    mul_ln241_7_fu_248_p0 <= sext_ln241_fu_1229_p1(18 - 1 downto 0);
    mul_ln241_8_fu_251_p0 <= sext_ln241_fu_1229_p1(18 - 1 downto 0);
    mul_ln241_9_fu_252_p0 <= sext_ln241_fu_1229_p1(18 - 1 downto 0);
    mul_ln241_fu_243_p0 <= sext_ln241_fu_1229_p1(18 - 1 downto 0);

    output_local_blk_n_assign_proc : process(output_local_full_n, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            output_local_blk_n <= output_local_full_n;
        else 
            output_local_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    output_local_din <= (((((((((trunc_ln241_9_reg_1702 & trunc_ln241_8_reg_1697) & trunc_ln241_7_reg_1692) & trunc_ln241_6_reg_1687) & trunc_ln241_5_reg_1682) & trunc_ln241_4_reg_1677) & trunc_ln241_3_reg_1672) & trunc_ln241_2_reg_1667) & trunc_ln241_1_reg_1662) & trunc_ln1_reg_1657);

    output_local_write_assign_proc : process(output_local_full_n, ap_CS_fsm_state12)
    begin
        if (((output_local_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            output_local_write <= ap_const_logic_1;
        else 
            output_local_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln66_1_fu_746_p3 <= 
        data_array_2_fu_634_p4 when (xor_ln66_1_fu_740_p2(0) = '1') else 
        data_array_3_fu_644_p4;
    select_ln66_2_fu_898_p3 <= 
        select_ln66_reg_1409 when (xor_ln66_2_fu_892_p2(0) = '1') else 
        select_ln66_1_reg_1415;
    select_ln66_3_fu_766_p3 <= 
        data_array_4_fu_654_p4 when (xor_ln66_3_fu_760_p2(0) = '1') else 
        data_array_5_fu_664_p4;
    select_ln66_4_fu_786_p3 <= 
        data_array_6_fu_674_p4 when (xor_ln66_4_fu_780_p2(0) = '1') else 
        data_array_7_fu_684_p4;
    select_ln66_5_fu_914_p3 <= 
        select_ln66_3_reg_1421 when (xor_ln66_5_fu_908_p2(0) = '1') else 
        select_ln66_4_reg_1427;
    select_ln66_6_fu_932_p3 <= 
        select_ln66_2_fu_898_p3 when (xor_ln66_6_fu_926_p2(0) = '1') else 
        select_ln66_5_fu_914_p3;
    select_ln66_7_fu_950_p3 <= 
        data_array_8_reg_1397 when (xor_ln66_7_fu_944_p2(0) = '1') else 
        data_array_9_reg_1403;
    select_ln66_8_fu_976_p3 <= 
        trunc_ln66_fu_968_p1 when (xor_ln66_8_fu_962_p2(0) = '1') else 
        trunc_ln66_1_fu_972_p1;
    select_ln66_fu_726_p3 <= 
        data_array_fu_620_p1 when (xor_ln66_fu_720_p2(0) = '1') else 
        data_array_1_fu_624_p4;
        sext_ln232_fu_1220_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_9_fu_1210_p4),10));

        sext_ln241_fu_1229_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inv_exp_sum_reg_1652),26));

    tmp_9_fu_1210_p4 <= add_ln51_2_fu_1204_p2(15 downto 8);
    tmp_fu_1024_p4 <= d_xi_xmax_fu_984_p2(11 downto 2);
    tmp_s_fu_1039_p4 <= d_xi_xmax_10_fu_988_p2(11 downto 2);
    trunc_ln213_fu_794_p1 <= layer21_out_dout(12 - 1 downto 0);
    trunc_ln66_1_fu_972_p1 <= select_ln66_7_fu_950_p3(12 - 1 downto 0);
    trunc_ln66_fu_968_p1 <= select_ln66_6_fu_932_p3(12 - 1 downto 0);
    xor_ln66_1_fu_740_p2 <= (icmp_ln66_1_fu_734_p2 xor ap_const_lv1_1);
    xor_ln66_2_fu_892_p2 <= (icmp_ln66_2_fu_888_p2 xor ap_const_lv1_1);
    xor_ln66_3_fu_760_p2 <= (icmp_ln66_3_fu_754_p2 xor ap_const_lv1_1);
    xor_ln66_4_fu_780_p2 <= (icmp_ln66_4_fu_774_p2 xor ap_const_lv1_1);
    xor_ln66_5_fu_908_p2 <= (icmp_ln66_5_fu_904_p2 xor ap_const_lv1_1);
    xor_ln66_6_fu_926_p2 <= (icmp_ln66_6_fu_920_p2 xor ap_const_lv1_1);
    xor_ln66_7_fu_944_p2 <= (icmp_ln66_7_fu_940_p2 xor ap_const_lv1_1);
    xor_ln66_8_fu_962_p2 <= (icmp_ln66_8_fu_956_p2 xor ap_const_lv1_1);
    xor_ln66_fu_720_p2 <= (icmp_ln66_fu_714_p2 xor ap_const_lv1_1);
    zext_ln223_1_fu_1049_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_1039_p4),64));
    zext_ln223_2_fu_1134_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_1507),64));
    zext_ln223_3_fu_1138_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_reg_1512),64));
    zext_ln223_4_fu_1142_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_reg_1517),64));
    zext_ln223_5_fu_1146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_reg_1522),64));
    zext_ln223_6_fu_1150_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_reg_1527),64));
    zext_ln223_7_fu_1154_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_reg_1532),64));
    zext_ln223_8_fu_1158_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_reg_1537),64));
    zext_ln223_9_fu_1162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_reg_1542),64));
    zext_ln223_fu_1034_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_1024_p4),64));
    zext_ln232_fu_1224_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln232_fu_1220_p1),64));
end behav;
