// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_axi_relu_array_ap_fixed_8u_array_ap_ufixed_16_6_4_0_0_8u_relu_config15_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer14_out_dout,
        layer14_out_num_data_valid,
        layer14_out_fifo_cap,
        layer14_out_empty_n,
        layer14_out_read,
        layer15_out_din,
        layer15_out_num_data_valid,
        layer15_out_fifo_cap,
        layer15_out_full_n,
        layer15_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [455:0] layer14_out_dout;
input  [6:0] layer14_out_num_data_valid;
input  [6:0] layer14_out_fifo_cap;
input   layer14_out_empty_n;
output   layer14_out_read;
output  [127:0] layer15_out_din;
input  [6:0] layer15_out_num_data_valid;
input  [6:0] layer15_out_fifo_cap;
input   layer15_out_full_n;
output   layer15_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer14_out_read;
reg layer15_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_201_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer14_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer15_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln51_fu_292_p2;
reg   [0:0] icmp_ln51_reg_2022;
reg   [0:0] tmp_reg_2027;
reg   [0:0] tmp_57_reg_2034;
wire   [15:0] add_ln52_fu_366_p2;
reg   [15:0] add_ln52_reg_2040;
wire   [0:0] icmp_ln52_4_fu_382_p2;
reg   [0:0] icmp_ln52_4_reg_2047;
wire   [0:0] icmp_ln52_5_fu_388_p2;
reg   [0:0] icmp_ln52_5_reg_2053;
reg   [0:0] tmp_58_reg_2059;
wire   [0:0] icmp_ln51_1_fu_402_p2;
reg   [0:0] icmp_ln51_1_reg_2065;
reg   [0:0] tmp_59_reg_2070;
reg   [0:0] tmp_62_reg_2077;
wire   [15:0] add_ln52_1_fu_482_p2;
reg   [15:0] add_ln52_1_reg_2083;
wire   [0:0] icmp_ln52_11_fu_498_p2;
reg   [0:0] icmp_ln52_11_reg_2090;
wire   [0:0] icmp_ln52_12_fu_504_p2;
reg   [0:0] icmp_ln52_12_reg_2096;
reg   [0:0] tmp_63_reg_2102;
wire   [0:0] icmp_ln51_2_fu_518_p2;
reg   [0:0] icmp_ln51_2_reg_2108;
reg   [0:0] tmp_64_reg_2113;
reg   [0:0] tmp_67_reg_2120;
wire   [15:0] add_ln52_2_fu_598_p2;
reg   [15:0] add_ln52_2_reg_2126;
wire   [0:0] icmp_ln52_18_fu_614_p2;
reg   [0:0] icmp_ln52_18_reg_2133;
wire   [0:0] icmp_ln52_19_fu_620_p2;
reg   [0:0] icmp_ln52_19_reg_2139;
reg   [0:0] tmp_68_reg_2145;
wire   [0:0] icmp_ln51_3_fu_634_p2;
reg   [0:0] icmp_ln51_3_reg_2151;
reg   [0:0] tmp_69_reg_2156;
reg   [0:0] tmp_72_reg_2163;
wire   [15:0] add_ln52_3_fu_714_p2;
reg   [15:0] add_ln52_3_reg_2169;
wire   [0:0] icmp_ln52_fu_730_p2;
reg   [0:0] icmp_ln52_reg_2176;
wire   [0:0] icmp_ln52_24_fu_736_p2;
reg   [0:0] icmp_ln52_24_reg_2182;
reg   [0:0] tmp_73_reg_2188;
wire   [0:0] icmp_ln51_4_fu_750_p2;
reg   [0:0] icmp_ln51_4_reg_2194;
reg   [0:0] tmp_74_reg_2199;
reg   [0:0] tmp_77_reg_2206;
wire   [15:0] add_ln52_4_fu_830_p2;
reg   [15:0] add_ln52_4_reg_2212;
wire   [0:0] icmp_ln52_26_fu_846_p2;
reg   [0:0] icmp_ln52_26_reg_2219;
wire   [0:0] icmp_ln52_27_fu_852_p2;
reg   [0:0] icmp_ln52_27_reg_2225;
reg   [0:0] tmp_78_reg_2231;
wire   [0:0] icmp_ln51_5_fu_866_p2;
reg   [0:0] icmp_ln51_5_reg_2237;
reg   [0:0] tmp_79_reg_2242;
reg   [0:0] tmp_82_reg_2249;
wire   [15:0] add_ln52_5_fu_946_p2;
reg   [15:0] add_ln52_5_reg_2255;
wire   [0:0] icmp_ln52_29_fu_962_p2;
reg   [0:0] icmp_ln52_29_reg_2262;
wire   [0:0] icmp_ln52_30_fu_968_p2;
reg   [0:0] icmp_ln52_30_reg_2268;
reg   [0:0] tmp_83_reg_2274;
wire   [0:0] icmp_ln51_6_fu_982_p2;
reg   [0:0] icmp_ln51_6_reg_2280;
reg   [0:0] tmp_84_reg_2285;
reg   [0:0] tmp_87_reg_2292;
wire   [15:0] add_ln52_6_fu_1062_p2;
reg   [15:0] add_ln52_6_reg_2298;
wire   [0:0] icmp_ln52_32_fu_1078_p2;
reg   [0:0] icmp_ln52_32_reg_2305;
wire   [0:0] icmp_ln52_33_fu_1084_p2;
reg   [0:0] icmp_ln52_33_reg_2311;
reg   [0:0] tmp_88_reg_2317;
wire   [0:0] icmp_ln51_7_fu_1098_p2;
reg   [0:0] icmp_ln51_7_reg_2323;
reg   [0:0] tmp_89_reg_2328;
reg   [0:0] tmp_92_reg_2335;
wire   [15:0] add_ln52_7_fu_1178_p2;
reg   [15:0] add_ln52_7_reg_2341;
wire   [0:0] icmp_ln52_35_fu_1194_p2;
reg   [0:0] icmp_ln52_35_reg_2348;
wire   [0:0] icmp_ln52_36_fu_1200_p2;
reg   [0:0] icmp_ln52_36_reg_2354;
reg   [0:0] tmp_93_reg_2360;
reg   [5:0] i_fu_176;
wire   [5:0] i_10_fu_207_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_9;
reg    ap_block_pp0_stage0_01001;
wire   [56:0] trunc_ln44_fu_218_p1;
wire   [17:0] trunc_ln52_fu_332_p1;
wire   [0:0] tmp_55_fu_316_p3;
wire   [0:0] icmp_ln52_2_fu_336_p2;
wire   [0:0] or_ln52_fu_350_p2;
wire   [0:0] tmp_56_fu_324_p3;
wire   [0:0] and_ln52_fu_356_p2;
wire   [15:0] trunc_ln5_fu_306_p4;
wire   [15:0] zext_ln52_fu_362_p1;
wire   [21:0] tmp_9_fu_372_p4;
wire   [56:0] trunc_ln44_1_fu_222_p4;
wire   [17:0] tmp_1_fu_442_p4;
wire   [0:0] tmp_60_fu_426_p3;
wire   [0:0] icmp_ln52_9_fu_452_p2;
wire   [0:0] or_ln52_3_fu_466_p2;
wire   [0:0] tmp_61_fu_434_p3;
wire   [0:0] and_ln52_2_fu_472_p2;
wire   [15:0] trunc_ln52_1_fu_416_p4;
wire   [15:0] zext_ln52_1_fu_478_p1;
wire   [21:0] tmp_2_fu_488_p4;
wire   [56:0] trunc_ln44_2_fu_232_p4;
wire   [17:0] tmp_3_fu_558_p4;
wire   [0:0] tmp_65_fu_542_p3;
wire   [0:0] icmp_ln52_16_fu_568_p2;
wire   [0:0] or_ln52_6_fu_582_p2;
wire   [0:0] tmp_66_fu_550_p3;
wire   [0:0] and_ln52_4_fu_588_p2;
wire   [15:0] trunc_ln52_2_fu_532_p4;
wire   [15:0] zext_ln52_2_fu_594_p1;
wire   [21:0] tmp_4_fu_604_p4;
wire   [56:0] trunc_ln44_3_fu_242_p4;
wire   [17:0] tmp_5_fu_674_p4;
wire   [0:0] tmp_70_fu_658_p3;
wire   [0:0] icmp_ln52_23_fu_684_p2;
wire   [0:0] or_ln52_9_fu_698_p2;
wire   [0:0] tmp_71_fu_666_p3;
wire   [0:0] and_ln52_6_fu_704_p2;
wire   [15:0] trunc_ln52_3_fu_648_p4;
wire   [15:0] zext_ln52_3_fu_710_p1;
wire   [21:0] tmp_6_fu_720_p4;
wire   [56:0] trunc_ln44_4_fu_252_p4;
wire   [17:0] tmp_7_fu_790_p4;
wire   [0:0] tmp_75_fu_774_p3;
wire   [0:0] icmp_ln52_25_fu_800_p2;
wire   [0:0] or_ln52_12_fu_814_p2;
wire   [0:0] tmp_76_fu_782_p3;
wire   [0:0] and_ln52_8_fu_820_p2;
wire   [15:0] trunc_ln52_4_fu_764_p4;
wire   [15:0] zext_ln52_4_fu_826_p1;
wire   [21:0] tmp_8_fu_836_p4;
wire   [56:0] trunc_ln44_5_fu_262_p4;
wire   [17:0] tmp_10_fu_906_p4;
wire   [0:0] tmp_80_fu_890_p3;
wire   [0:0] icmp_ln52_28_fu_916_p2;
wire   [0:0] or_ln52_15_fu_930_p2;
wire   [0:0] tmp_81_fu_898_p3;
wire   [0:0] and_ln52_10_fu_936_p2;
wire   [15:0] trunc_ln52_5_fu_880_p4;
wire   [15:0] zext_ln52_5_fu_942_p1;
wire   [21:0] tmp_11_fu_952_p4;
wire   [56:0] trunc_ln44_6_fu_272_p4;
wire   [17:0] tmp_12_fu_1022_p4;
wire   [0:0] tmp_85_fu_1006_p3;
wire   [0:0] icmp_ln52_31_fu_1032_p2;
wire   [0:0] or_ln52_18_fu_1046_p2;
wire   [0:0] tmp_86_fu_1014_p3;
wire   [0:0] and_ln52_12_fu_1052_p2;
wire   [15:0] trunc_ln52_6_fu_996_p4;
wire   [15:0] zext_ln52_6_fu_1058_p1;
wire   [21:0] tmp_13_fu_1068_p4;
wire   [56:0] trunc_ln44_7_fu_282_p4;
wire   [17:0] tmp_14_fu_1138_p4;
wire   [0:0] tmp_90_fu_1122_p3;
wire   [0:0] icmp_ln52_34_fu_1148_p2;
wire   [0:0] or_ln52_21_fu_1162_p2;
wire   [0:0] tmp_91_fu_1130_p3;
wire   [0:0] and_ln52_14_fu_1168_p2;
wire   [15:0] trunc_ln52_7_fu_1112_p4;
wire   [15:0] zext_ln52_7_fu_1174_p1;
wire   [21:0] tmp_s_fu_1184_p4;
wire   [0:0] select_ln52_fu_1222_p3;
wire   [0:0] select_ln52_3_fu_1227_p3;
wire   [0:0] or_ln52_1_fu_1233_p2;
wire   [0:0] xor_ln52_24_fu_1217_p2;
wire   [0:0] and_ln52_16_fu_1244_p2;
wire   [0:0] and_ln52_1_fu_1249_p2;
wire   [14:0] trunc_ln52_15_fu_1214_p1;
wire   [14:0] select_ln52_1_fu_1260_p3;
wire   [0:0] xor_ln52_1_fu_1254_p2;
wire   [0:0] and_ln52_17_fu_1272_p2;
wire   [0:0] xor_ln52_fu_1238_p2;
wire   [15:0] zext_ln52_8_fu_1268_p1;
wire   [15:0] select_ln52_7_fu_1283_p3;
wire   [0:0] or_ln52_2_fu_1277_p2;
wire   [15:0] select_ln52_2_fu_1289_p3;
wire   [15:0] out_data_fu_1297_p3;
wire   [0:0] select_ln52_4_fu_1319_p3;
wire   [0:0] select_ln52_15_fu_1324_p3;
wire   [0:0] or_ln52_4_fu_1330_p2;
wire   [0:0] xor_ln52_25_fu_1314_p2;
wire   [0:0] and_ln52_18_fu_1341_p2;
wire   [0:0] and_ln52_3_fu_1346_p2;
wire   [14:0] trunc_ln52_16_fu_1311_p1;
wire   [14:0] select_ln52_5_fu_1357_p3;
wire   [0:0] xor_ln52_3_fu_1351_p2;
wire   [0:0] and_ln52_19_fu_1369_p2;
wire   [0:0] xor_ln52_2_fu_1335_p2;
wire   [15:0] zext_ln52_9_fu_1365_p1;
wire   [15:0] select_ln52_32_fu_1380_p3;
wire   [0:0] or_ln52_5_fu_1374_p2;
wire   [15:0] select_ln52_6_fu_1386_p3;
wire   [15:0] out_data_9_fu_1394_p3;
wire   [0:0] select_ln52_8_fu_1416_p3;
wire   [0:0] select_ln52_34_fu_1421_p3;
wire   [0:0] or_ln52_7_fu_1427_p2;
wire   [0:0] xor_ln52_26_fu_1411_p2;
wire   [0:0] and_ln52_20_fu_1438_p2;
wire   [0:0] and_ln52_5_fu_1443_p2;
wire   [14:0] trunc_ln52_17_fu_1408_p1;
wire   [14:0] select_ln52_9_fu_1454_p3;
wire   [0:0] xor_ln52_5_fu_1448_p2;
wire   [0:0] and_ln52_21_fu_1466_p2;
wire   [0:0] xor_ln52_4_fu_1432_p2;
wire   [15:0] zext_ln52_10_fu_1462_p1;
wire   [15:0] select_ln52_35_fu_1477_p3;
wire   [0:0] or_ln52_8_fu_1471_p2;
wire   [15:0] select_ln52_10_fu_1483_p3;
wire   [15:0] out_data_11_fu_1491_p3;
wire   [0:0] select_ln52_12_fu_1513_p3;
wire   [0:0] select_ln52_37_fu_1518_p3;
wire   [0:0] or_ln52_10_fu_1524_p2;
wire   [0:0] xor_ln52_27_fu_1508_p2;
wire   [0:0] and_ln52_22_fu_1535_p2;
wire   [0:0] and_ln52_7_fu_1540_p2;
wire   [14:0] trunc_ln52_18_fu_1505_p1;
wire   [14:0] select_ln52_13_fu_1551_p3;
wire   [0:0] xor_ln52_7_fu_1545_p2;
wire   [0:0] and_ln52_23_fu_1563_p2;
wire   [0:0] xor_ln52_6_fu_1529_p2;
wire   [15:0] zext_ln52_11_fu_1559_p1;
wire   [15:0] select_ln52_38_fu_1574_p3;
wire   [0:0] or_ln52_11_fu_1568_p2;
wire   [15:0] select_ln52_14_fu_1580_p3;
wire   [15:0] out_data_13_fu_1588_p3;
wire   [0:0] select_ln52_16_fu_1610_p3;
wire   [0:0] select_ln52_40_fu_1615_p3;
wire   [0:0] or_ln52_13_fu_1621_p2;
wire   [0:0] xor_ln52_28_fu_1605_p2;
wire   [0:0] and_ln52_24_fu_1632_p2;
wire   [0:0] and_ln52_9_fu_1637_p2;
wire   [14:0] trunc_ln52_19_fu_1602_p1;
wire   [14:0] select_ln52_17_fu_1648_p3;
wire   [0:0] xor_ln52_9_fu_1642_p2;
wire   [0:0] and_ln52_25_fu_1660_p2;
wire   [0:0] xor_ln52_8_fu_1626_p2;
wire   [15:0] zext_ln52_12_fu_1656_p1;
wire   [15:0] select_ln52_41_fu_1671_p3;
wire   [0:0] or_ln52_14_fu_1665_p2;
wire   [15:0] select_ln52_18_fu_1677_p3;
wire   [15:0] select_ln52_19_fu_1685_p3;
wire   [0:0] select_ln52_20_fu_1707_p3;
wire   [0:0] select_ln52_42_fu_1712_p3;
wire   [0:0] or_ln52_16_fu_1718_p2;
wire   [0:0] xor_ln52_29_fu_1702_p2;
wire   [0:0] and_ln52_26_fu_1729_p2;
wire   [0:0] and_ln52_11_fu_1734_p2;
wire   [14:0] trunc_ln52_20_fu_1699_p1;
wire   [14:0] select_ln52_21_fu_1745_p3;
wire   [0:0] xor_ln52_11_fu_1739_p2;
wire   [0:0] and_ln52_27_fu_1757_p2;
wire   [0:0] xor_ln52_10_fu_1723_p2;
wire   [15:0] zext_ln52_13_fu_1753_p1;
wire   [15:0] select_ln52_43_fu_1768_p3;
wire   [0:0] or_ln52_17_fu_1762_p2;
wire   [15:0] select_ln52_22_fu_1774_p3;
wire   [15:0] select_ln52_23_fu_1782_p3;
wire   [0:0] select_ln52_24_fu_1804_p3;
wire   [0:0] select_ln52_44_fu_1809_p3;
wire   [0:0] or_ln52_19_fu_1815_p2;
wire   [0:0] xor_ln52_30_fu_1799_p2;
wire   [0:0] and_ln52_28_fu_1826_p2;
wire   [0:0] and_ln52_13_fu_1831_p2;
wire   [14:0] trunc_ln52_21_fu_1796_p1;
wire   [14:0] select_ln52_25_fu_1842_p3;
wire   [0:0] xor_ln52_13_fu_1836_p2;
wire   [0:0] and_ln52_29_fu_1854_p2;
wire   [0:0] xor_ln52_12_fu_1820_p2;
wire   [15:0] zext_ln52_14_fu_1850_p1;
wire   [15:0] select_ln52_45_fu_1865_p3;
wire   [0:0] or_ln52_20_fu_1859_p2;
wire   [15:0] select_ln52_26_fu_1871_p3;
wire   [15:0] select_ln52_27_fu_1879_p3;
wire   [0:0] select_ln52_28_fu_1901_p3;
wire   [0:0] select_ln52_46_fu_1906_p3;
wire   [0:0] or_ln52_22_fu_1912_p2;
wire   [0:0] xor_ln52_31_fu_1896_p2;
wire   [0:0] and_ln52_30_fu_1923_p2;
wire   [0:0] and_ln52_15_fu_1928_p2;
wire   [14:0] trunc_ln52_22_fu_1893_p1;
wire   [14:0] select_ln52_29_fu_1939_p3;
wire   [0:0] xor_ln52_15_fu_1933_p2;
wire   [0:0] and_ln52_31_fu_1951_p2;
wire   [0:0] xor_ln52_14_fu_1917_p2;
wire   [15:0] zext_ln52_15_fu_1947_p1;
wire   [15:0] select_ln52_47_fu_1962_p3;
wire   [0:0] or_ln52_23_fu_1956_p2;
wire   [15:0] select_ln52_30_fu_1968_p3;
wire   [15:0] select_ln52_31_fu_1976_p3;
wire   [15:0] select_ln51_3_fu_1983_p3;
wire   [15:0] select_ln51_2_fu_1886_p3;
wire   [15:0] select_ln51_1_fu_1789_p3;
wire   [15:0] select_ln51_fu_1692_p3;
wire   [15:0] out_data_14_fu_1595_p3;
wire   [15:0] out_data_12_fu_1498_p3;
wire   [15:0] out_data_10_fu_1401_p3;
wire   [15:0] out_data_8_fu_1304_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_225;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_176 = 6'd0;
end

myproject_axi_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_225)) begin
        if ((icmp_ln41_fu_201_p2 == 1'd0)) begin
            i_fu_176 <= i_10_fu_207_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_176 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln52_1_reg_2083 <= add_ln52_1_fu_482_p2;
        add_ln52_2_reg_2126 <= add_ln52_2_fu_598_p2;
        add_ln52_3_reg_2169 <= add_ln52_3_fu_714_p2;
        add_ln52_4_reg_2212 <= add_ln52_4_fu_830_p2;
        add_ln52_5_reg_2255 <= add_ln52_5_fu_946_p2;
        add_ln52_6_reg_2298 <= add_ln52_6_fu_1062_p2;
        add_ln52_7_reg_2341 <= add_ln52_7_fu_1178_p2;
        add_ln52_reg_2040 <= add_ln52_fu_366_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln51_1_reg_2065 <= icmp_ln51_1_fu_402_p2;
        icmp_ln51_2_reg_2108 <= icmp_ln51_2_fu_518_p2;
        icmp_ln51_3_reg_2151 <= icmp_ln51_3_fu_634_p2;
        icmp_ln51_4_reg_2194 <= icmp_ln51_4_fu_750_p2;
        icmp_ln51_5_reg_2237 <= icmp_ln51_5_fu_866_p2;
        icmp_ln51_6_reg_2280 <= icmp_ln51_6_fu_982_p2;
        icmp_ln51_7_reg_2323 <= icmp_ln51_7_fu_1098_p2;
        icmp_ln51_reg_2022 <= icmp_ln51_fu_292_p2;
        icmp_ln52_11_reg_2090 <= icmp_ln52_11_fu_498_p2;
        icmp_ln52_12_reg_2096 <= icmp_ln52_12_fu_504_p2;
        icmp_ln52_18_reg_2133 <= icmp_ln52_18_fu_614_p2;
        icmp_ln52_19_reg_2139 <= icmp_ln52_19_fu_620_p2;
        icmp_ln52_24_reg_2182 <= icmp_ln52_24_fu_736_p2;
        icmp_ln52_26_reg_2219 <= icmp_ln52_26_fu_846_p2;
        icmp_ln52_27_reg_2225 <= icmp_ln52_27_fu_852_p2;
        icmp_ln52_29_reg_2262 <= icmp_ln52_29_fu_962_p2;
        icmp_ln52_30_reg_2268 <= icmp_ln52_30_fu_968_p2;
        icmp_ln52_32_reg_2305 <= icmp_ln52_32_fu_1078_p2;
        icmp_ln52_33_reg_2311 <= icmp_ln52_33_fu_1084_p2;
        icmp_ln52_35_reg_2348 <= icmp_ln52_35_fu_1194_p2;
        icmp_ln52_36_reg_2354 <= icmp_ln52_36_fu_1200_p2;
        icmp_ln52_4_reg_2047 <= icmp_ln52_4_fu_382_p2;
        icmp_ln52_5_reg_2053 <= icmp_ln52_5_fu_388_p2;
        icmp_ln52_reg_2176 <= icmp_ln52_fu_730_p2;
        tmp_57_reg_2034 <= layer14_out_dout[32'd34];
        tmp_58_reg_2059 <= add_ln52_fu_366_p2[32'd15];
        tmp_59_reg_2070 <= layer14_out_dout[32'd113];
        tmp_62_reg_2077 <= layer14_out_dout[32'd91];
        tmp_63_reg_2102 <= add_ln52_1_fu_482_p2[32'd15];
        tmp_64_reg_2113 <= layer14_out_dout[32'd170];
        tmp_67_reg_2120 <= layer14_out_dout[32'd148];
        tmp_68_reg_2145 <= add_ln52_2_fu_598_p2[32'd15];
        tmp_69_reg_2156 <= layer14_out_dout[32'd227];
        tmp_72_reg_2163 <= layer14_out_dout[32'd205];
        tmp_73_reg_2188 <= add_ln52_3_fu_714_p2[32'd15];
        tmp_74_reg_2199 <= layer14_out_dout[32'd284];
        tmp_77_reg_2206 <= layer14_out_dout[32'd262];
        tmp_78_reg_2231 <= add_ln52_4_fu_830_p2[32'd15];
        tmp_79_reg_2242 <= layer14_out_dout[32'd341];
        tmp_82_reg_2249 <= layer14_out_dout[32'd319];
        tmp_83_reg_2274 <= add_ln52_5_fu_946_p2[32'd15];
        tmp_84_reg_2285 <= layer14_out_dout[32'd398];
        tmp_87_reg_2292 <= layer14_out_dout[32'd376];
        tmp_88_reg_2317 <= add_ln52_6_fu_1062_p2[32'd15];
        tmp_89_reg_2328 <= layer14_out_dout[32'd455];
        tmp_92_reg_2335 <= layer14_out_dout[32'd433];
        tmp_93_reg_2360 <= add_ln52_7_fu_1178_p2[32'd15];
        tmp_reg_2027 <= layer14_out_dout[32'd56];
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_201_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_9 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_9 = i_fu_176;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer14_out_blk_n = layer14_out_empty_n;
    end else begin
        layer14_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer14_out_read = 1'b1;
    end else begin
        layer14_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer15_out_blk_n = layer15_out_full_n;
    end else begin
        layer15_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer15_out_write = 1'b1;
    end else begin
        layer15_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_1_fu_482_p2 = (trunc_ln52_1_fu_416_p4 + zext_ln52_1_fu_478_p1);

assign add_ln52_2_fu_598_p2 = (trunc_ln52_2_fu_532_p4 + zext_ln52_2_fu_594_p1);

assign add_ln52_3_fu_714_p2 = (trunc_ln52_3_fu_648_p4 + zext_ln52_3_fu_710_p1);

assign add_ln52_4_fu_830_p2 = (trunc_ln52_4_fu_764_p4 + zext_ln52_4_fu_826_p1);

assign add_ln52_5_fu_946_p2 = (trunc_ln52_5_fu_880_p4 + zext_ln52_5_fu_942_p1);

assign add_ln52_6_fu_1062_p2 = (trunc_ln52_6_fu_996_p4 + zext_ln52_6_fu_1058_p1);

assign add_ln52_7_fu_1178_p2 = (trunc_ln52_7_fu_1112_p4 + zext_ln52_7_fu_1174_p1);

assign add_ln52_fu_366_p2 = (trunc_ln5_fu_306_p4 + zext_ln52_fu_362_p1);

assign and_ln52_10_fu_936_p2 = (tmp_81_fu_898_p3 & or_ln52_15_fu_930_p2);

assign and_ln52_11_fu_1734_p2 = (tmp_82_reg_2249 & and_ln52_26_fu_1729_p2);

assign and_ln52_12_fu_1052_p2 = (tmp_86_fu_1014_p3 & or_ln52_18_fu_1046_p2);

assign and_ln52_13_fu_1831_p2 = (tmp_87_reg_2292 & and_ln52_28_fu_1826_p2);

assign and_ln52_14_fu_1168_p2 = (tmp_91_fu_1130_p3 & or_ln52_21_fu_1162_p2);

assign and_ln52_15_fu_1928_p2 = (tmp_92_reg_2335 & and_ln52_30_fu_1923_p2);

assign and_ln52_16_fu_1244_p2 = (xor_ln52_24_fu_1217_p2 & icmp_ln52_4_reg_2047);

assign and_ln52_17_fu_1272_p2 = (xor_ln52_1_fu_1254_p2 & tmp_reg_2027);

assign and_ln52_18_fu_1341_p2 = (xor_ln52_25_fu_1314_p2 & icmp_ln52_11_reg_2090);

assign and_ln52_19_fu_1369_p2 = (xor_ln52_3_fu_1351_p2 & tmp_59_reg_2070);

assign and_ln52_1_fu_1249_p2 = (tmp_57_reg_2034 & and_ln52_16_fu_1244_p2);

assign and_ln52_20_fu_1438_p2 = (xor_ln52_26_fu_1411_p2 & icmp_ln52_18_reg_2133);

assign and_ln52_21_fu_1466_p2 = (xor_ln52_5_fu_1448_p2 & tmp_64_reg_2113);

assign and_ln52_22_fu_1535_p2 = (xor_ln52_27_fu_1508_p2 & icmp_ln52_reg_2176);

assign and_ln52_23_fu_1563_p2 = (xor_ln52_7_fu_1545_p2 & tmp_69_reg_2156);

assign and_ln52_24_fu_1632_p2 = (xor_ln52_28_fu_1605_p2 & icmp_ln52_26_reg_2219);

assign and_ln52_25_fu_1660_p2 = (xor_ln52_9_fu_1642_p2 & tmp_74_reg_2199);

assign and_ln52_26_fu_1729_p2 = (xor_ln52_29_fu_1702_p2 & icmp_ln52_29_reg_2262);

assign and_ln52_27_fu_1757_p2 = (xor_ln52_11_fu_1739_p2 & tmp_79_reg_2242);

assign and_ln52_28_fu_1826_p2 = (xor_ln52_30_fu_1799_p2 & icmp_ln52_32_reg_2305);

assign and_ln52_29_fu_1854_p2 = (xor_ln52_13_fu_1836_p2 & tmp_84_reg_2285);

assign and_ln52_2_fu_472_p2 = (tmp_61_fu_434_p3 & or_ln52_3_fu_466_p2);

assign and_ln52_30_fu_1923_p2 = (xor_ln52_31_fu_1896_p2 & icmp_ln52_35_reg_2348);

assign and_ln52_31_fu_1951_p2 = (xor_ln52_15_fu_1933_p2 & tmp_89_reg_2328);

assign and_ln52_3_fu_1346_p2 = (tmp_62_reg_2077 & and_ln52_18_fu_1341_p2);

assign and_ln52_4_fu_588_p2 = (tmp_66_fu_550_p3 & or_ln52_6_fu_582_p2);

assign and_ln52_5_fu_1443_p2 = (tmp_67_reg_2120 & and_ln52_20_fu_1438_p2);

assign and_ln52_6_fu_704_p2 = (tmp_71_fu_666_p3 & or_ln52_9_fu_698_p2);

assign and_ln52_7_fu_1540_p2 = (tmp_72_reg_2163 & and_ln52_22_fu_1535_p2);

assign and_ln52_8_fu_820_p2 = (tmp_76_fu_782_p3 & or_ln52_12_fu_814_p2);

assign and_ln52_9_fu_1637_p2 = (tmp_77_reg_2206 & and_ln52_24_fu_1632_p2);

assign and_ln52_fu_356_p2 = (tmp_56_fu_324_p3 & or_ln52_fu_350_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer14_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer15_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_225 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_10_fu_207_p2 = (ap_sig_allocacmp_i_9 + 6'd1);

assign icmp_ln41_fu_201_p2 = ((ap_sig_allocacmp_i_9 == 6'd40) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_402_p2 = (($signed(trunc_ln44_1_fu_222_p4) > $signed(57'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_518_p2 = (($signed(trunc_ln44_2_fu_232_p4) > $signed(57'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_634_p2 = (($signed(trunc_ln44_3_fu_242_p4) > $signed(57'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_750_p2 = (($signed(trunc_ln44_4_fu_252_p4) > $signed(57'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_866_p2 = (($signed(trunc_ln44_5_fu_262_p4) > $signed(57'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_982_p2 = (($signed(trunc_ln44_6_fu_272_p4) > $signed(57'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_1098_p2 = (($signed(trunc_ln44_7_fu_282_p4) > $signed(57'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_292_p2 = (($signed(trunc_ln44_fu_218_p1) > $signed(57'd0)) ? 1'b1 : 1'b0);

assign icmp_ln52_11_fu_498_p2 = ((tmp_2_fu_488_p4 == 22'd4194303) ? 1'b1 : 1'b0);

assign icmp_ln52_12_fu_504_p2 = ((tmp_2_fu_488_p4 == 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_16_fu_568_p2 = ((tmp_3_fu_558_p4 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_18_fu_614_p2 = ((tmp_4_fu_604_p4 == 22'd4194303) ? 1'b1 : 1'b0);

assign icmp_ln52_19_fu_620_p2 = ((tmp_4_fu_604_p4 == 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_23_fu_684_p2 = ((tmp_5_fu_674_p4 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_24_fu_736_p2 = ((tmp_6_fu_720_p4 == 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_25_fu_800_p2 = ((tmp_7_fu_790_p4 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_26_fu_846_p2 = ((tmp_8_fu_836_p4 == 22'd4194303) ? 1'b1 : 1'b0);

assign icmp_ln52_27_fu_852_p2 = ((tmp_8_fu_836_p4 == 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_28_fu_916_p2 = ((tmp_10_fu_906_p4 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_29_fu_962_p2 = ((tmp_11_fu_952_p4 == 22'd4194303) ? 1'b1 : 1'b0);

assign icmp_ln52_2_fu_336_p2 = ((trunc_ln52_fu_332_p1 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_30_fu_968_p2 = ((tmp_11_fu_952_p4 == 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_31_fu_1032_p2 = ((tmp_12_fu_1022_p4 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_32_fu_1078_p2 = ((tmp_13_fu_1068_p4 == 22'd4194303) ? 1'b1 : 1'b0);

assign icmp_ln52_33_fu_1084_p2 = ((tmp_13_fu_1068_p4 == 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_34_fu_1148_p2 = ((tmp_14_fu_1138_p4 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_35_fu_1194_p2 = ((tmp_s_fu_1184_p4 == 22'd4194303) ? 1'b1 : 1'b0);

assign icmp_ln52_36_fu_1200_p2 = ((tmp_s_fu_1184_p4 == 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_4_fu_382_p2 = ((tmp_9_fu_372_p4 == 22'd4194303) ? 1'b1 : 1'b0);

assign icmp_ln52_5_fu_388_p2 = ((tmp_9_fu_372_p4 == 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_9_fu_452_p2 = ((tmp_1_fu_442_p4 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_730_p2 = ((tmp_6_fu_720_p4 == 22'd4194303) ? 1'b1 : 1'b0);

assign layer15_out_din = {{{{{{{{select_ln51_3_fu_1983_p3}, {select_ln51_2_fu_1886_p3}}, {select_ln51_1_fu_1789_p3}}, {select_ln51_fu_1692_p3}}, {out_data_14_fu_1595_p3}}, {out_data_12_fu_1498_p3}}, {out_data_10_fu_1401_p3}}, {out_data_8_fu_1304_p3}};

assign or_ln52_10_fu_1524_p2 = (tmp_69_reg_2156 | select_ln52_37_fu_1518_p3);

assign or_ln52_11_fu_1568_p2 = (xor_ln52_6_fu_1529_p2 | and_ln52_23_fu_1563_p2);

assign or_ln52_12_fu_814_p2 = (tmp_75_fu_774_p3 | icmp_ln52_25_fu_800_p2);

assign or_ln52_13_fu_1621_p2 = (tmp_74_reg_2199 | select_ln52_40_fu_1615_p3);

assign or_ln52_14_fu_1665_p2 = (xor_ln52_8_fu_1626_p2 | and_ln52_25_fu_1660_p2);

assign or_ln52_15_fu_930_p2 = (tmp_80_fu_890_p3 | icmp_ln52_28_fu_916_p2);

assign or_ln52_16_fu_1718_p2 = (tmp_79_reg_2242 | select_ln52_42_fu_1712_p3);

assign or_ln52_17_fu_1762_p2 = (xor_ln52_10_fu_1723_p2 | and_ln52_27_fu_1757_p2);

assign or_ln52_18_fu_1046_p2 = (tmp_85_fu_1006_p3 | icmp_ln52_31_fu_1032_p2);

assign or_ln52_19_fu_1815_p2 = (tmp_84_reg_2285 | select_ln52_44_fu_1809_p3);

assign or_ln52_1_fu_1233_p2 = (tmp_reg_2027 | select_ln52_3_fu_1227_p3);

assign or_ln52_20_fu_1859_p2 = (xor_ln52_12_fu_1820_p2 | and_ln52_29_fu_1854_p2);

assign or_ln52_21_fu_1162_p2 = (tmp_90_fu_1122_p3 | icmp_ln52_34_fu_1148_p2);

assign or_ln52_22_fu_1912_p2 = (tmp_89_reg_2328 | select_ln52_46_fu_1906_p3);

assign or_ln52_23_fu_1956_p2 = (xor_ln52_14_fu_1917_p2 | and_ln52_31_fu_1951_p2);

assign or_ln52_2_fu_1277_p2 = (xor_ln52_fu_1238_p2 | and_ln52_17_fu_1272_p2);

assign or_ln52_3_fu_466_p2 = (tmp_60_fu_426_p3 | icmp_ln52_9_fu_452_p2);

assign or_ln52_4_fu_1330_p2 = (tmp_59_reg_2070 | select_ln52_15_fu_1324_p3);

assign or_ln52_5_fu_1374_p2 = (xor_ln52_2_fu_1335_p2 | and_ln52_19_fu_1369_p2);

assign or_ln52_6_fu_582_p2 = (tmp_65_fu_542_p3 | icmp_ln52_16_fu_568_p2);

assign or_ln52_7_fu_1427_p2 = (tmp_64_reg_2113 | select_ln52_34_fu_1421_p3);

assign or_ln52_8_fu_1471_p2 = (xor_ln52_4_fu_1432_p2 | and_ln52_21_fu_1466_p2);

assign or_ln52_9_fu_698_p2 = (tmp_70_fu_658_p3 | icmp_ln52_23_fu_684_p2);

assign or_ln52_fu_350_p2 = (tmp_55_fu_316_p3 | icmp_ln52_2_fu_336_p2);

assign out_data_10_fu_1401_p3 = ((icmp_ln51_1_reg_2065[0:0] == 1'b1) ? out_data_9_fu_1394_p3 : 16'd0);

assign out_data_11_fu_1491_p3 = ((or_ln52_8_fu_1471_p2[0:0] == 1'b1) ? select_ln52_10_fu_1483_p3 : add_ln52_2_reg_2126);

assign out_data_12_fu_1498_p3 = ((icmp_ln51_2_reg_2108[0:0] == 1'b1) ? out_data_11_fu_1491_p3 : 16'd0);

assign out_data_13_fu_1588_p3 = ((or_ln52_11_fu_1568_p2[0:0] == 1'b1) ? select_ln52_14_fu_1580_p3 : add_ln52_3_reg_2169);

assign out_data_14_fu_1595_p3 = ((icmp_ln51_3_reg_2151[0:0] == 1'b1) ? out_data_13_fu_1588_p3 : 16'd0);

assign out_data_8_fu_1304_p3 = ((icmp_ln51_reg_2022[0:0] == 1'b1) ? out_data_fu_1297_p3 : 16'd0);

assign out_data_9_fu_1394_p3 = ((or_ln52_5_fu_1374_p2[0:0] == 1'b1) ? select_ln52_6_fu_1386_p3 : add_ln52_1_reg_2083);

assign out_data_fu_1297_p3 = ((or_ln52_2_fu_1277_p2[0:0] == 1'b1) ? select_ln52_2_fu_1289_p3 : add_ln52_reg_2040);

assign select_ln51_1_fu_1789_p3 = ((icmp_ln51_5_reg_2237[0:0] == 1'b1) ? select_ln52_23_fu_1782_p3 : 16'd0);

assign select_ln51_2_fu_1886_p3 = ((icmp_ln51_6_reg_2280[0:0] == 1'b1) ? select_ln52_27_fu_1879_p3 : 16'd0);

assign select_ln51_3_fu_1983_p3 = ((icmp_ln51_7_reg_2323[0:0] == 1'b1) ? select_ln52_31_fu_1976_p3 : 16'd0);

assign select_ln51_fu_1692_p3 = ((icmp_ln51_4_reg_2194[0:0] == 1'b1) ? select_ln52_19_fu_1685_p3 : 16'd0);

assign select_ln52_10_fu_1483_p3 = ((or_ln52_7_fu_1427_p2[0:0] == 1'b1) ? select_ln52_35_fu_1477_p3 : 16'd65535);

assign select_ln52_12_fu_1513_p3 = ((tmp_73_reg_2188[0:0] == 1'b1) ? icmp_ln52_24_reg_2182 : icmp_ln52_reg_2176);

assign select_ln52_13_fu_1551_p3 = ((and_ln52_7_fu_1540_p2[0:0] == 1'b1) ? trunc_ln52_18_fu_1505_p1 : 15'd0);

assign select_ln52_14_fu_1580_p3 = ((or_ln52_10_fu_1524_p2[0:0] == 1'b1) ? select_ln52_38_fu_1574_p3 : 16'd65535);

assign select_ln52_15_fu_1324_p3 = ((tmp_62_reg_2077[0:0] == 1'b1) ? select_ln52_4_fu_1319_p3 : icmp_ln52_12_reg_2096);

assign select_ln52_16_fu_1610_p3 = ((tmp_78_reg_2231[0:0] == 1'b1) ? icmp_ln52_27_reg_2225 : icmp_ln52_26_reg_2219);

assign select_ln52_17_fu_1648_p3 = ((and_ln52_9_fu_1637_p2[0:0] == 1'b1) ? trunc_ln52_19_fu_1602_p1 : 15'd0);

assign select_ln52_18_fu_1677_p3 = ((or_ln52_13_fu_1621_p2[0:0] == 1'b1) ? select_ln52_41_fu_1671_p3 : 16'd65535);

assign select_ln52_19_fu_1685_p3 = ((or_ln52_14_fu_1665_p2[0:0] == 1'b1) ? select_ln52_18_fu_1677_p3 : add_ln52_4_reg_2212);

assign select_ln52_1_fu_1260_p3 = ((and_ln52_1_fu_1249_p2[0:0] == 1'b1) ? trunc_ln52_15_fu_1214_p1 : 15'd0);

assign select_ln52_20_fu_1707_p3 = ((tmp_83_reg_2274[0:0] == 1'b1) ? icmp_ln52_30_reg_2268 : icmp_ln52_29_reg_2262);

assign select_ln52_21_fu_1745_p3 = ((and_ln52_11_fu_1734_p2[0:0] == 1'b1) ? trunc_ln52_20_fu_1699_p1 : 15'd0);

assign select_ln52_22_fu_1774_p3 = ((or_ln52_16_fu_1718_p2[0:0] == 1'b1) ? select_ln52_43_fu_1768_p3 : 16'd65535);

assign select_ln52_23_fu_1782_p3 = ((or_ln52_17_fu_1762_p2[0:0] == 1'b1) ? select_ln52_22_fu_1774_p3 : add_ln52_5_reg_2255);

assign select_ln52_24_fu_1804_p3 = ((tmp_88_reg_2317[0:0] == 1'b1) ? icmp_ln52_33_reg_2311 : icmp_ln52_32_reg_2305);

assign select_ln52_25_fu_1842_p3 = ((and_ln52_13_fu_1831_p2[0:0] == 1'b1) ? trunc_ln52_21_fu_1796_p1 : 15'd0);

assign select_ln52_26_fu_1871_p3 = ((or_ln52_19_fu_1815_p2[0:0] == 1'b1) ? select_ln52_45_fu_1865_p3 : 16'd65535);

assign select_ln52_27_fu_1879_p3 = ((or_ln52_20_fu_1859_p2[0:0] == 1'b1) ? select_ln52_26_fu_1871_p3 : add_ln52_6_reg_2298);

assign select_ln52_28_fu_1901_p3 = ((tmp_93_reg_2360[0:0] == 1'b1) ? icmp_ln52_36_reg_2354 : icmp_ln52_35_reg_2348);

assign select_ln52_29_fu_1939_p3 = ((and_ln52_15_fu_1928_p2[0:0] == 1'b1) ? trunc_ln52_22_fu_1893_p1 : 15'd0);

assign select_ln52_2_fu_1289_p3 = ((or_ln52_1_fu_1233_p2[0:0] == 1'b1) ? select_ln52_7_fu_1283_p3 : 16'd65535);

assign select_ln52_30_fu_1968_p3 = ((or_ln52_22_fu_1912_p2[0:0] == 1'b1) ? select_ln52_47_fu_1962_p3 : 16'd65535);

assign select_ln52_31_fu_1976_p3 = ((or_ln52_23_fu_1956_p2[0:0] == 1'b1) ? select_ln52_30_fu_1968_p3 : add_ln52_7_reg_2341);

assign select_ln52_32_fu_1380_p3 = ((tmp_59_reg_2070[0:0] == 1'b1) ? zext_ln52_9_fu_1365_p1 : add_ln52_1_reg_2083);

assign select_ln52_34_fu_1421_p3 = ((tmp_67_reg_2120[0:0] == 1'b1) ? select_ln52_8_fu_1416_p3 : icmp_ln52_19_reg_2139);

assign select_ln52_35_fu_1477_p3 = ((tmp_64_reg_2113[0:0] == 1'b1) ? zext_ln52_10_fu_1462_p1 : add_ln52_2_reg_2126);

assign select_ln52_37_fu_1518_p3 = ((tmp_72_reg_2163[0:0] == 1'b1) ? select_ln52_12_fu_1513_p3 : icmp_ln52_24_reg_2182);

assign select_ln52_38_fu_1574_p3 = ((tmp_69_reg_2156[0:0] == 1'b1) ? zext_ln52_11_fu_1559_p1 : add_ln52_3_reg_2169);

assign select_ln52_3_fu_1227_p3 = ((tmp_57_reg_2034[0:0] == 1'b1) ? select_ln52_fu_1222_p3 : icmp_ln52_5_reg_2053);

assign select_ln52_40_fu_1615_p3 = ((tmp_77_reg_2206[0:0] == 1'b1) ? select_ln52_16_fu_1610_p3 : icmp_ln52_27_reg_2225);

assign select_ln52_41_fu_1671_p3 = ((tmp_74_reg_2199[0:0] == 1'b1) ? zext_ln52_12_fu_1656_p1 : add_ln52_4_reg_2212);

assign select_ln52_42_fu_1712_p3 = ((tmp_82_reg_2249[0:0] == 1'b1) ? select_ln52_20_fu_1707_p3 : icmp_ln52_30_reg_2268);

assign select_ln52_43_fu_1768_p3 = ((tmp_79_reg_2242[0:0] == 1'b1) ? zext_ln52_13_fu_1753_p1 : add_ln52_5_reg_2255);

assign select_ln52_44_fu_1809_p3 = ((tmp_87_reg_2292[0:0] == 1'b1) ? select_ln52_24_fu_1804_p3 : icmp_ln52_33_reg_2311);

assign select_ln52_45_fu_1865_p3 = ((tmp_84_reg_2285[0:0] == 1'b1) ? zext_ln52_14_fu_1850_p1 : add_ln52_6_reg_2298);

assign select_ln52_46_fu_1906_p3 = ((tmp_92_reg_2335[0:0] == 1'b1) ? select_ln52_28_fu_1901_p3 : icmp_ln52_36_reg_2354);

assign select_ln52_47_fu_1962_p3 = ((tmp_89_reg_2328[0:0] == 1'b1) ? zext_ln52_15_fu_1947_p1 : add_ln52_7_reg_2341);

assign select_ln52_4_fu_1319_p3 = ((tmp_63_reg_2102[0:0] == 1'b1) ? icmp_ln52_12_reg_2096 : icmp_ln52_11_reg_2090);

assign select_ln52_5_fu_1357_p3 = ((and_ln52_3_fu_1346_p2[0:0] == 1'b1) ? trunc_ln52_16_fu_1311_p1 : 15'd0);

assign select_ln52_6_fu_1386_p3 = ((or_ln52_4_fu_1330_p2[0:0] == 1'b1) ? select_ln52_32_fu_1380_p3 : 16'd65535);

assign select_ln52_7_fu_1283_p3 = ((tmp_reg_2027[0:0] == 1'b1) ? zext_ln52_8_fu_1268_p1 : add_ln52_reg_2040);

assign select_ln52_8_fu_1416_p3 = ((tmp_68_reg_2145[0:0] == 1'b1) ? icmp_ln52_19_reg_2139 : icmp_ln52_18_reg_2133);

assign select_ln52_9_fu_1454_p3 = ((and_ln52_5_fu_1443_p2[0:0] == 1'b1) ? trunc_ln52_17_fu_1408_p1 : 15'd0);

assign select_ln52_fu_1222_p3 = ((tmp_58_reg_2059[0:0] == 1'b1) ? icmp_ln52_5_reg_2053 : icmp_ln52_4_reg_2047);

assign start_out = real_start;

assign tmp_10_fu_906_p4 = {{layer14_out_dout[302:285]}};

assign tmp_11_fu_952_p4 = {{layer14_out_dout[341:320]}};

assign tmp_12_fu_1022_p4 = {{layer14_out_dout[359:342]}};

assign tmp_13_fu_1068_p4 = {{layer14_out_dout[398:377]}};

assign tmp_14_fu_1138_p4 = {{layer14_out_dout[416:399]}};

assign tmp_1_fu_442_p4 = {{layer14_out_dout[74:57]}};

assign tmp_2_fu_488_p4 = {{layer14_out_dout[113:92]}};

assign tmp_3_fu_558_p4 = {{layer14_out_dout[131:114]}};

assign tmp_4_fu_604_p4 = {{layer14_out_dout[170:149]}};

assign tmp_55_fu_316_p3 = layer14_out_dout[32'd19];

assign tmp_56_fu_324_p3 = layer14_out_dout[32'd18];

assign tmp_5_fu_674_p4 = {{layer14_out_dout[188:171]}};

assign tmp_60_fu_426_p3 = layer14_out_dout[32'd76];

assign tmp_61_fu_434_p3 = layer14_out_dout[32'd75];

assign tmp_65_fu_542_p3 = layer14_out_dout[32'd133];

assign tmp_66_fu_550_p3 = layer14_out_dout[32'd132];

assign tmp_6_fu_720_p4 = {{layer14_out_dout[227:206]}};

assign tmp_70_fu_658_p3 = layer14_out_dout[32'd190];

assign tmp_71_fu_666_p3 = layer14_out_dout[32'd189];

assign tmp_75_fu_774_p3 = layer14_out_dout[32'd247];

assign tmp_76_fu_782_p3 = layer14_out_dout[32'd246];

assign tmp_7_fu_790_p4 = {{layer14_out_dout[245:228]}};

assign tmp_80_fu_890_p3 = layer14_out_dout[32'd304];

assign tmp_81_fu_898_p3 = layer14_out_dout[32'd303];

assign tmp_85_fu_1006_p3 = layer14_out_dout[32'd361];

assign tmp_86_fu_1014_p3 = layer14_out_dout[32'd360];

assign tmp_8_fu_836_p4 = {{layer14_out_dout[284:263]}};

assign tmp_90_fu_1122_p3 = layer14_out_dout[32'd418];

assign tmp_91_fu_1130_p3 = layer14_out_dout[32'd417];

assign tmp_9_fu_372_p4 = {{layer14_out_dout[56:35]}};

assign tmp_s_fu_1184_p4 = {{layer14_out_dout[455:434]}};

assign trunc_ln44_1_fu_222_p4 = {{layer14_out_dout[113:57]}};

assign trunc_ln44_2_fu_232_p4 = {{layer14_out_dout[170:114]}};

assign trunc_ln44_3_fu_242_p4 = {{layer14_out_dout[227:171]}};

assign trunc_ln44_4_fu_252_p4 = {{layer14_out_dout[284:228]}};

assign trunc_ln44_5_fu_262_p4 = {{layer14_out_dout[341:285]}};

assign trunc_ln44_6_fu_272_p4 = {{layer14_out_dout[398:342]}};

assign trunc_ln44_7_fu_282_p4 = {{layer14_out_dout[455:399]}};

assign trunc_ln44_fu_218_p1 = layer14_out_dout[56:0];

assign trunc_ln52_15_fu_1214_p1 = add_ln52_reg_2040[14:0];

assign trunc_ln52_16_fu_1311_p1 = add_ln52_1_reg_2083[14:0];

assign trunc_ln52_17_fu_1408_p1 = add_ln52_2_reg_2126[14:0];

assign trunc_ln52_18_fu_1505_p1 = add_ln52_3_reg_2169[14:0];

assign trunc_ln52_19_fu_1602_p1 = add_ln52_4_reg_2212[14:0];

assign trunc_ln52_1_fu_416_p4 = {{layer14_out_dout[91:76]}};

assign trunc_ln52_20_fu_1699_p1 = add_ln52_5_reg_2255[14:0];

assign trunc_ln52_21_fu_1796_p1 = add_ln52_6_reg_2298[14:0];

assign trunc_ln52_22_fu_1893_p1 = add_ln52_7_reg_2341[14:0];

assign trunc_ln52_2_fu_532_p4 = {{layer14_out_dout[148:133]}};

assign trunc_ln52_3_fu_648_p4 = {{layer14_out_dout[205:190]}};

assign trunc_ln52_4_fu_764_p4 = {{layer14_out_dout[262:247]}};

assign trunc_ln52_5_fu_880_p4 = {{layer14_out_dout[319:304]}};

assign trunc_ln52_6_fu_996_p4 = {{layer14_out_dout[376:361]}};

assign trunc_ln52_7_fu_1112_p4 = {{layer14_out_dout[433:418]}};

assign trunc_ln52_fu_332_p1 = layer14_out_dout[17:0];

assign trunc_ln5_fu_306_p4 = {{layer14_out_dout[34:19]}};

assign xor_ln52_10_fu_1723_p2 = (or_ln52_16_fu_1718_p2 ^ 1'd1);

assign xor_ln52_11_fu_1739_p2 = (1'd1 ^ and_ln52_11_fu_1734_p2);

assign xor_ln52_12_fu_1820_p2 = (or_ln52_19_fu_1815_p2 ^ 1'd1);

assign xor_ln52_13_fu_1836_p2 = (1'd1 ^ and_ln52_13_fu_1831_p2);

assign xor_ln52_14_fu_1917_p2 = (or_ln52_22_fu_1912_p2 ^ 1'd1);

assign xor_ln52_15_fu_1933_p2 = (1'd1 ^ and_ln52_15_fu_1928_p2);

assign xor_ln52_1_fu_1254_p2 = (1'd1 ^ and_ln52_1_fu_1249_p2);

assign xor_ln52_24_fu_1217_p2 = (tmp_58_reg_2059 ^ 1'd1);

assign xor_ln52_25_fu_1314_p2 = (tmp_63_reg_2102 ^ 1'd1);

assign xor_ln52_26_fu_1411_p2 = (tmp_68_reg_2145 ^ 1'd1);

assign xor_ln52_27_fu_1508_p2 = (tmp_73_reg_2188 ^ 1'd1);

assign xor_ln52_28_fu_1605_p2 = (tmp_78_reg_2231 ^ 1'd1);

assign xor_ln52_29_fu_1702_p2 = (tmp_83_reg_2274 ^ 1'd1);

assign xor_ln52_2_fu_1335_p2 = (or_ln52_4_fu_1330_p2 ^ 1'd1);

assign xor_ln52_30_fu_1799_p2 = (tmp_88_reg_2317 ^ 1'd1);

assign xor_ln52_31_fu_1896_p2 = (tmp_93_reg_2360 ^ 1'd1);

assign xor_ln52_3_fu_1351_p2 = (1'd1 ^ and_ln52_3_fu_1346_p2);

assign xor_ln52_4_fu_1432_p2 = (or_ln52_7_fu_1427_p2 ^ 1'd1);

assign xor_ln52_5_fu_1448_p2 = (1'd1 ^ and_ln52_5_fu_1443_p2);

assign xor_ln52_6_fu_1529_p2 = (or_ln52_10_fu_1524_p2 ^ 1'd1);

assign xor_ln52_7_fu_1545_p2 = (1'd1 ^ and_ln52_7_fu_1540_p2);

assign xor_ln52_8_fu_1626_p2 = (or_ln52_13_fu_1621_p2 ^ 1'd1);

assign xor_ln52_9_fu_1642_p2 = (1'd1 ^ and_ln52_9_fu_1637_p2);

assign xor_ln52_fu_1238_p2 = (or_ln52_1_fu_1233_p2 ^ 1'd1);

assign zext_ln52_10_fu_1462_p1 = select_ln52_9_fu_1454_p3;

assign zext_ln52_11_fu_1559_p1 = select_ln52_13_fu_1551_p3;

assign zext_ln52_12_fu_1656_p1 = select_ln52_17_fu_1648_p3;

assign zext_ln52_13_fu_1753_p1 = select_ln52_21_fu_1745_p3;

assign zext_ln52_14_fu_1850_p1 = select_ln52_25_fu_1842_p3;

assign zext_ln52_15_fu_1947_p1 = select_ln52_29_fu_1939_p3;

assign zext_ln52_1_fu_478_p1 = and_ln52_2_fu_472_p2;

assign zext_ln52_2_fu_594_p1 = and_ln52_4_fu_588_p2;

assign zext_ln52_3_fu_710_p1 = and_ln52_6_fu_704_p2;

assign zext_ln52_4_fu_826_p1 = and_ln52_8_fu_820_p2;

assign zext_ln52_5_fu_942_p1 = and_ln52_10_fu_936_p2;

assign zext_ln52_6_fu_1058_p1 = and_ln52_12_fu_1052_p2;

assign zext_ln52_7_fu_1174_p1 = and_ln52_14_fu_1168_p2;

assign zext_ln52_8_fu_1268_p1 = select_ln52_1_fu_1260_p3;

assign zext_ln52_9_fu_1365_p1 = select_ln52_5_fu_1357_p3;

assign zext_ln52_fu_362_p1 = and_ln52_fu_356_p2;

endmodule //myproject_axi_relu_array_ap_fixed_8u_array_ap_ufixed_16_6_4_0_0_8u_relu_config15_s
