// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_16u_array_ap_ufixed_8_4_4_0_0_16u_relu_config15_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer14_out_dout,
        layer14_out_num_data_valid,
        layer14_out_fifo_cap,
        layer14_out_empty_n,
        layer14_out_read,
        layer15_out_din,
        layer15_out_num_data_valid,
        layer15_out_fifo_cap,
        layer15_out_full_n,
        layer15_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [671:0] layer14_out_dout;
input  [7:0] layer14_out_num_data_valid;
input  [7:0] layer14_out_fifo_cap;
input   layer14_out_empty_n;
output   layer14_out_read;
output  [127:0] layer15_out_din;
input  [7:0] layer15_out_num_data_valid;
input  [7:0] layer15_out_fifo_cap;
input   layer15_out_full_n;
output   layer15_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer14_out_read;
reg layer15_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_311_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer14_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer15_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln51_fu_482_p2;
reg   [0:0] icmp_ln51_reg_4012;
wire   [0:0] tmp_fu_488_p3;
reg   [0:0] tmp_reg_4017;
wire   [7:0] add_ln52_fu_556_p2;
reg   [7:0] add_ln52_reg_4023;
wire   [0:0] or_ln52_24_fu_614_p2;
reg   [0:0] or_ln52_24_reg_4030;
wire   [0:0] and_ln52_16_fu_626_p2;
reg   [0:0] and_ln52_16_reg_4036;
wire   [0:0] icmp_ln51_8_fu_632_p2;
reg   [0:0] icmp_ln51_8_reg_4042;
wire   [0:0] tmp_242_fu_638_p3;
reg   [0:0] tmp_242_reg_4047;
wire   [7:0] add_ln52_8_fu_712_p2;
reg   [7:0] add_ln52_8_reg_4053;
wire   [0:0] or_ln52_27_fu_770_p2;
reg   [0:0] or_ln52_27_reg_4060;
wire   [0:0] and_ln52_18_fu_782_p2;
reg   [0:0] and_ln52_18_reg_4066;
wire   [0:0] icmp_ln51_9_fu_788_p2;
reg   [0:0] icmp_ln51_9_reg_4072;
wire   [0:0] tmp_247_fu_794_p3;
reg   [0:0] tmp_247_reg_4077;
wire   [7:0] add_ln52_9_fu_868_p2;
reg   [7:0] add_ln52_9_reg_4083;
wire   [0:0] or_ln52_30_fu_926_p2;
reg   [0:0] or_ln52_30_reg_4090;
wire   [0:0] and_ln52_20_fu_938_p2;
reg   [0:0] and_ln52_20_reg_4096;
wire   [0:0] icmp_ln51_10_fu_944_p2;
reg   [0:0] icmp_ln51_10_reg_4102;
wire   [0:0] tmp_252_fu_950_p3;
reg   [0:0] tmp_252_reg_4107;
wire   [7:0] add_ln52_10_fu_1024_p2;
reg   [7:0] add_ln52_10_reg_4113;
wire   [0:0] or_ln52_33_fu_1082_p2;
reg   [0:0] or_ln52_33_reg_4120;
wire   [0:0] and_ln52_22_fu_1094_p2;
reg   [0:0] and_ln52_22_reg_4126;
wire   [0:0] icmp_ln51_11_fu_1100_p2;
reg   [0:0] icmp_ln51_11_reg_4132;
wire   [0:0] tmp_257_fu_1106_p3;
reg   [0:0] tmp_257_reg_4137;
wire   [7:0] add_ln52_11_fu_1180_p2;
reg   [7:0] add_ln52_11_reg_4143;
wire   [0:0] or_ln52_36_fu_1238_p2;
reg   [0:0] or_ln52_36_reg_4150;
wire   [0:0] and_ln52_24_fu_1250_p2;
reg   [0:0] and_ln52_24_reg_4156;
wire   [0:0] icmp_ln51_12_fu_1256_p2;
reg   [0:0] icmp_ln51_12_reg_4162;
wire   [0:0] tmp_262_fu_1262_p3;
reg   [0:0] tmp_262_reg_4167;
wire   [7:0] add_ln52_12_fu_1336_p2;
reg   [7:0] add_ln52_12_reg_4173;
wire   [0:0] or_ln52_39_fu_1394_p2;
reg   [0:0] or_ln52_39_reg_4180;
wire   [0:0] and_ln52_26_fu_1406_p2;
reg   [0:0] and_ln52_26_reg_4186;
wire   [0:0] icmp_ln51_13_fu_1412_p2;
reg   [0:0] icmp_ln51_13_reg_4192;
wire   [0:0] tmp_267_fu_1418_p3;
reg   [0:0] tmp_267_reg_4197;
wire   [7:0] add_ln52_13_fu_1492_p2;
reg   [7:0] add_ln52_13_reg_4203;
wire   [0:0] or_ln52_42_fu_1550_p2;
reg   [0:0] or_ln52_42_reg_4210;
wire   [0:0] and_ln52_28_fu_1562_p2;
reg   [0:0] and_ln52_28_reg_4216;
wire   [0:0] icmp_ln51_14_fu_1568_p2;
reg   [0:0] icmp_ln51_14_reg_4222;
wire   [0:0] tmp_272_fu_1574_p3;
reg   [0:0] tmp_272_reg_4227;
wire   [7:0] add_ln52_14_fu_1648_p2;
reg   [7:0] add_ln52_14_reg_4233;
wire   [0:0] or_ln52_45_fu_1706_p2;
reg   [0:0] or_ln52_45_reg_4240;
wire   [0:0] and_ln52_30_fu_1718_p2;
reg   [0:0] and_ln52_30_reg_4246;
wire   [0:0] icmp_ln51_15_fu_1724_p2;
reg   [0:0] icmp_ln51_15_reg_4252;
wire   [0:0] tmp_277_fu_1730_p3;
reg   [0:0] tmp_277_reg_4257;
wire   [7:0] add_ln52_15_fu_1804_p2;
reg   [7:0] add_ln52_15_reg_4263;
wire   [0:0] or_ln52_48_fu_1862_p2;
reg   [0:0] or_ln52_48_reg_4270;
wire   [0:0] and_ln52_32_fu_1874_p2;
reg   [0:0] and_ln52_32_reg_4276;
wire   [0:0] icmp_ln51_16_fu_1880_p2;
reg   [0:0] icmp_ln51_16_reg_4282;
wire   [0:0] tmp_282_fu_1886_p3;
reg   [0:0] tmp_282_reg_4287;
wire   [7:0] add_ln52_16_fu_1960_p2;
reg   [7:0] add_ln52_16_reg_4293;
wire   [0:0] or_ln52_51_fu_2018_p2;
reg   [0:0] or_ln52_51_reg_4300;
wire   [0:0] and_ln52_34_fu_2030_p2;
reg   [0:0] and_ln52_34_reg_4306;
wire   [0:0] icmp_ln51_17_fu_2036_p2;
reg   [0:0] icmp_ln51_17_reg_4312;
wire   [0:0] tmp_287_fu_2042_p3;
reg   [0:0] tmp_287_reg_4317;
wire   [7:0] add_ln52_17_fu_2116_p2;
reg   [7:0] add_ln52_17_reg_4323;
wire   [0:0] or_ln52_54_fu_2174_p2;
reg   [0:0] or_ln52_54_reg_4330;
wire   [0:0] and_ln52_36_fu_2186_p2;
reg   [0:0] and_ln52_36_reg_4336;
wire   [0:0] icmp_ln51_18_fu_2192_p2;
reg   [0:0] icmp_ln51_18_reg_4342;
wire   [0:0] tmp_292_fu_2198_p3;
reg   [0:0] tmp_292_reg_4347;
wire   [7:0] add_ln52_18_fu_2272_p2;
reg   [7:0] add_ln52_18_reg_4353;
wire   [0:0] or_ln52_57_fu_2330_p2;
reg   [0:0] or_ln52_57_reg_4360;
wire   [0:0] and_ln52_38_fu_2342_p2;
reg   [0:0] and_ln52_38_reg_4366;
wire   [0:0] icmp_ln51_19_fu_2348_p2;
reg   [0:0] icmp_ln51_19_reg_4372;
wire   [0:0] tmp_297_fu_2354_p3;
reg   [0:0] tmp_297_reg_4377;
wire   [7:0] add_ln52_19_fu_2428_p2;
reg   [7:0] add_ln52_19_reg_4383;
wire   [0:0] or_ln52_60_fu_2486_p2;
reg   [0:0] or_ln52_60_reg_4390;
wire   [0:0] and_ln52_40_fu_2498_p2;
reg   [0:0] and_ln52_40_reg_4396;
wire   [0:0] icmp_ln51_20_fu_2504_p2;
reg   [0:0] icmp_ln51_20_reg_4402;
wire   [0:0] tmp_302_fu_2510_p3;
reg   [0:0] tmp_302_reg_4407;
wire   [7:0] add_ln52_20_fu_2584_p2;
reg   [7:0] add_ln52_20_reg_4413;
wire   [0:0] or_ln52_63_fu_2642_p2;
reg   [0:0] or_ln52_63_reg_4420;
wire   [0:0] and_ln52_42_fu_2654_p2;
reg   [0:0] and_ln52_42_reg_4426;
wire   [0:0] icmp_ln51_21_fu_2660_p2;
reg   [0:0] icmp_ln51_21_reg_4432;
wire   [0:0] tmp_307_fu_2666_p3;
reg   [0:0] tmp_307_reg_4437;
wire   [7:0] add_ln52_21_fu_2740_p2;
reg   [7:0] add_ln52_21_reg_4443;
wire   [0:0] or_ln52_66_fu_2798_p2;
reg   [0:0] or_ln52_66_reg_4450;
wire   [0:0] and_ln52_44_fu_2810_p2;
reg   [0:0] and_ln52_44_reg_4456;
wire   [0:0] icmp_ln51_22_fu_2816_p2;
reg   [0:0] icmp_ln51_22_reg_4462;
wire   [0:0] tmp_312_fu_2822_p3;
reg   [0:0] tmp_312_reg_4467;
wire   [7:0] add_ln52_22_fu_2896_p2;
reg   [7:0] add_ln52_22_reg_4473;
wire   [0:0] or_ln52_69_fu_2954_p2;
reg   [0:0] or_ln52_69_reg_4480;
wire   [0:0] and_ln52_46_fu_2966_p2;
reg   [0:0] and_ln52_46_reg_4486;
reg   [6:0] i_fu_286;
wire   [6:0] i_6_fu_317_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_5;
reg    ap_block_pp0_stage0_01001;
wire   [41:0] trunc_ln44_fu_328_p1;
wire   [11:0] trunc_ln52_fu_522_p1;
wire   [0:0] tmp_238_fu_506_p3;
wire   [0:0] icmp_ln52_57_fu_526_p2;
wire   [0:0] or_ln52_fu_540_p2;
wire   [0:0] tmp_239_fu_514_p3;
wire   [0:0] and_ln52_fu_546_p2;
wire   [7:0] trunc_ln5_fu_496_p4;
wire   [7:0] zext_ln52_fu_552_p1;
wire   [20:0] tmp_16_fu_562_p4;
wire   [0:0] tmp_241_fu_584_p3;
wire   [0:0] icmp_ln52_60_fu_578_p2;
wire   [0:0] icmp_ln52_59_fu_572_p2;
wire   [0:0] tmp_240_fu_532_p3;
wire   [0:0] select_ln52_fu_598_p3;
wire   [0:0] select_ln52_50_fu_606_p3;
wire   [0:0] xor_ln52_111_fu_592_p2;
wire   [0:0] and_ln52_47_fu_620_p2;
wire   [41:0] trunc_ln44_8_fu_332_p4;
wire   [11:0] tmp_17_fu_672_p4;
wire   [0:0] tmp_243_fu_656_p3;
wire   [0:0] icmp_ln52_64_fu_682_p2;
wire   [0:0] or_ln52_26_fu_696_p2;
wire   [0:0] tmp_244_fu_664_p3;
wire   [0:0] and_ln52_17_fu_702_p2;
wire   [7:0] trunc_ln52_8_fu_646_p4;
wire   [7:0] zext_ln52_8_fu_708_p1;
wire   [20:0] tmp_18_fu_718_p4;
wire   [0:0] tmp_246_fu_740_p3;
wire   [0:0] icmp_ln52_67_fu_734_p2;
wire   [0:0] icmp_ln52_66_fu_728_p2;
wire   [0:0] tmp_245_fu_688_p3;
wire   [0:0] select_ln52_35_fu_754_p3;
wire   [0:0] select_ln52_62_fu_762_p3;
wire   [0:0] xor_ln52_112_fu_748_p2;
wire   [0:0] and_ln52_49_fu_776_p2;
wire   [41:0] trunc_ln44_9_fu_342_p4;
wire   [11:0] tmp_19_fu_828_p4;
wire   [0:0] tmp_248_fu_812_p3;
wire   [0:0] icmp_ln52_71_fu_838_p2;
wire   [0:0] or_ln52_29_fu_852_p2;
wire   [0:0] tmp_249_fu_820_p3;
wire   [0:0] and_ln52_19_fu_858_p2;
wire   [7:0] trunc_ln52_9_fu_802_p4;
wire   [7:0] zext_ln52_9_fu_864_p1;
wire   [20:0] tmp_20_fu_874_p4;
wire   [0:0] tmp_251_fu_896_p3;
wire   [0:0] icmp_ln52_74_fu_890_p2;
wire   [0:0] icmp_ln52_73_fu_884_p2;
wire   [0:0] tmp_250_fu_844_p3;
wire   [0:0] select_ln52_39_fu_910_p3;
wire   [0:0] select_ln52_97_fu_918_p3;
wire   [0:0] xor_ln52_113_fu_904_p2;
wire   [0:0] and_ln52_51_fu_932_p2;
wire   [41:0] trunc_ln44_10_fu_352_p4;
wire   [11:0] tmp_21_fu_984_p4;
wire   [0:0] tmp_253_fu_968_p3;
wire   [0:0] icmp_ln52_78_fu_994_p2;
wire   [0:0] or_ln52_32_fu_1008_p2;
wire   [0:0] tmp_254_fu_976_p3;
wire   [0:0] and_ln52_21_fu_1014_p2;
wire   [7:0] trunc_ln52_10_fu_958_p4;
wire   [7:0] zext_ln52_10_fu_1020_p1;
wire   [20:0] tmp_22_fu_1030_p4;
wire   [0:0] tmp_256_fu_1052_p3;
wire   [0:0] icmp_ln52_81_fu_1046_p2;
wire   [0:0] icmp_ln52_80_fu_1040_p2;
wire   [0:0] tmp_255_fu_1000_p3;
wire   [0:0] select_ln52_43_fu_1066_p3;
wire   [0:0] select_ln52_100_fu_1074_p3;
wire   [0:0] xor_ln52_114_fu_1060_p2;
wire   [0:0] and_ln52_53_fu_1088_p2;
wire   [41:0] trunc_ln44_11_fu_362_p4;
wire   [11:0] tmp_23_fu_1140_p4;
wire   [0:0] tmp_258_fu_1124_p3;
wire   [0:0] icmp_ln52_85_fu_1150_p2;
wire   [0:0] or_ln52_35_fu_1164_p2;
wire   [0:0] tmp_259_fu_1132_p3;
wire   [0:0] and_ln52_23_fu_1170_p2;
wire   [7:0] trunc_ln52_11_fu_1114_p4;
wire   [7:0] zext_ln52_11_fu_1176_p1;
wire   [20:0] tmp_24_fu_1186_p4;
wire   [0:0] tmp_261_fu_1208_p3;
wire   [0:0] icmp_ln52_88_fu_1202_p2;
wire   [0:0] icmp_ln52_87_fu_1196_p2;
wire   [0:0] tmp_260_fu_1156_p3;
wire   [0:0] select_ln52_47_fu_1222_p3;
wire   [0:0] select_ln52_103_fu_1230_p3;
wire   [0:0] xor_ln52_115_fu_1216_p2;
wire   [0:0] and_ln52_55_fu_1244_p2;
wire   [41:0] trunc_ln44_12_fu_372_p4;
wire   [11:0] tmp_25_fu_1296_p4;
wire   [0:0] tmp_263_fu_1280_p3;
wire   [0:0] icmp_ln52_92_fu_1306_p2;
wire   [0:0] or_ln52_38_fu_1320_p2;
wire   [0:0] tmp_264_fu_1288_p3;
wire   [0:0] and_ln52_25_fu_1326_p2;
wire   [7:0] trunc_ln52_12_fu_1270_p4;
wire   [7:0] zext_ln52_12_fu_1332_p1;
wire   [20:0] tmp_26_fu_1342_p4;
wire   [0:0] tmp_266_fu_1364_p3;
wire   [0:0] icmp_ln52_95_fu_1358_p2;
wire   [0:0] icmp_ln52_94_fu_1352_p2;
wire   [0:0] tmp_265_fu_1312_p3;
wire   [0:0] select_ln52_51_fu_1378_p3;
wire   [0:0] select_ln52_106_fu_1386_p3;
wire   [0:0] xor_ln52_116_fu_1372_p2;
wire   [0:0] and_ln52_57_fu_1400_p2;
wire   [41:0] trunc_ln44_13_fu_382_p4;
wire   [11:0] tmp_27_fu_1452_p4;
wire   [0:0] tmp_268_fu_1436_p3;
wire   [0:0] icmp_ln52_99_fu_1462_p2;
wire   [0:0] or_ln52_41_fu_1476_p2;
wire   [0:0] tmp_269_fu_1444_p3;
wire   [0:0] and_ln52_27_fu_1482_p2;
wire   [7:0] trunc_ln52_13_fu_1426_p4;
wire   [7:0] zext_ln52_13_fu_1488_p1;
wire   [20:0] tmp_28_fu_1498_p4;
wire   [0:0] tmp_271_fu_1520_p3;
wire   [0:0] icmp_ln52_102_fu_1514_p2;
wire   [0:0] icmp_ln52_101_fu_1508_p2;
wire   [0:0] tmp_270_fu_1468_p3;
wire   [0:0] select_ln52_55_fu_1534_p3;
wire   [0:0] select_ln52_109_fu_1542_p3;
wire   [0:0] xor_ln52_117_fu_1528_p2;
wire   [0:0] and_ln52_59_fu_1556_p2;
wire   [41:0] trunc_ln44_14_fu_392_p4;
wire   [11:0] tmp_29_fu_1608_p4;
wire   [0:0] tmp_273_fu_1592_p3;
wire   [0:0] icmp_ln52_106_fu_1618_p2;
wire   [0:0] or_ln52_44_fu_1632_p2;
wire   [0:0] tmp_274_fu_1600_p3;
wire   [0:0] and_ln52_29_fu_1638_p2;
wire   [7:0] trunc_ln52_14_fu_1582_p4;
wire   [7:0] zext_ln52_14_fu_1644_p1;
wire   [20:0] tmp_30_fu_1654_p4;
wire   [0:0] tmp_276_fu_1676_p3;
wire   [0:0] icmp_ln52_109_fu_1670_p2;
wire   [0:0] icmp_ln52_108_fu_1664_p2;
wire   [0:0] tmp_275_fu_1624_p3;
wire   [0:0] select_ln52_59_fu_1690_p3;
wire   [0:0] select_ln52_112_fu_1698_p3;
wire   [0:0] xor_ln52_118_fu_1684_p2;
wire   [0:0] and_ln52_61_fu_1712_p2;
wire   [41:0] trunc_ln44_15_fu_402_p4;
wire   [11:0] tmp_31_fu_1764_p4;
wire   [0:0] tmp_278_fu_1748_p3;
wire   [0:0] icmp_ln52_113_fu_1774_p2;
wire   [0:0] or_ln52_47_fu_1788_p2;
wire   [0:0] tmp_279_fu_1756_p3;
wire   [0:0] and_ln52_31_fu_1794_p2;
wire   [7:0] trunc_ln52_15_fu_1738_p4;
wire   [7:0] zext_ln52_15_fu_1800_p1;
wire   [20:0] tmp_32_fu_1810_p4;
wire   [0:0] tmp_281_fu_1832_p3;
wire   [0:0] icmp_ln52_116_fu_1826_p2;
wire   [0:0] icmp_ln52_115_fu_1820_p2;
wire   [0:0] tmp_280_fu_1780_p3;
wire   [0:0] select_ln52_63_fu_1846_p3;
wire   [0:0] select_ln52_115_fu_1854_p3;
wire   [0:0] xor_ln52_119_fu_1840_p2;
wire   [0:0] and_ln52_63_fu_1868_p2;
wire   [41:0] trunc_ln44_16_fu_412_p4;
wire   [11:0] tmp_33_fu_1920_p4;
wire   [0:0] tmp_283_fu_1904_p3;
wire   [0:0] icmp_ln52_fu_1930_p2;
wire   [0:0] or_ln52_50_fu_1944_p2;
wire   [0:0] tmp_284_fu_1912_p3;
wire   [0:0] and_ln52_33_fu_1950_p2;
wire   [7:0] trunc_ln52_16_fu_1894_p4;
wire   [7:0] zext_ln52_16_fu_1956_p1;
wire   [20:0] tmp_34_fu_1966_p4;
wire   [0:0] tmp_286_fu_1988_p3;
wire   [0:0] icmp_ln52_120_fu_1982_p2;
wire   [0:0] icmp_ln52_119_fu_1976_p2;
wire   [0:0] tmp_285_fu_1936_p3;
wire   [0:0] select_ln52_67_fu_2002_p3;
wire   [0:0] select_ln52_117_fu_2010_p3;
wire   [0:0] xor_ln52_120_fu_1996_p2;
wire   [0:0] and_ln52_65_fu_2024_p2;
wire   [41:0] trunc_ln44_17_fu_422_p4;
wire   [11:0] tmp_35_fu_2076_p4;
wire   [0:0] tmp_288_fu_2060_p3;
wire   [0:0] icmp_ln52_121_fu_2086_p2;
wire   [0:0] or_ln52_53_fu_2100_p2;
wire   [0:0] tmp_289_fu_2068_p3;
wire   [0:0] and_ln52_35_fu_2106_p2;
wire   [7:0] trunc_ln52_17_fu_2050_p4;
wire   [7:0] zext_ln52_17_fu_2112_p1;
wire   [20:0] tmp_36_fu_2122_p4;
wire   [0:0] tmp_291_fu_2144_p3;
wire   [0:0] icmp_ln52_123_fu_2138_p2;
wire   [0:0] icmp_ln52_122_fu_2132_p2;
wire   [0:0] tmp_290_fu_2092_p3;
wire   [0:0] select_ln52_71_fu_2158_p3;
wire   [0:0] select_ln52_119_fu_2166_p3;
wire   [0:0] xor_ln52_121_fu_2152_p2;
wire   [0:0] and_ln52_67_fu_2180_p2;
wire   [41:0] trunc_ln44_18_fu_432_p4;
wire   [11:0] tmp_37_fu_2232_p4;
wire   [0:0] tmp_293_fu_2216_p3;
wire   [0:0] icmp_ln52_124_fu_2242_p2;
wire   [0:0] or_ln52_56_fu_2256_p2;
wire   [0:0] tmp_294_fu_2224_p3;
wire   [0:0] and_ln52_37_fu_2262_p2;
wire   [7:0] trunc_ln52_18_fu_2206_p4;
wire   [7:0] zext_ln52_18_fu_2268_p1;
wire   [20:0] tmp_38_fu_2278_p4;
wire   [0:0] tmp_296_fu_2300_p3;
wire   [0:0] icmp_ln52_126_fu_2294_p2;
wire   [0:0] icmp_ln52_125_fu_2288_p2;
wire   [0:0] tmp_295_fu_2248_p3;
wire   [0:0] select_ln52_75_fu_2314_p3;
wire   [0:0] select_ln52_121_fu_2322_p3;
wire   [0:0] xor_ln52_122_fu_2308_p2;
wire   [0:0] and_ln52_69_fu_2336_p2;
wire   [41:0] trunc_ln44_19_fu_442_p4;
wire   [11:0] tmp_39_fu_2388_p4;
wire   [0:0] tmp_298_fu_2372_p3;
wire   [0:0] icmp_ln52_127_fu_2398_p2;
wire   [0:0] or_ln52_59_fu_2412_p2;
wire   [0:0] tmp_299_fu_2380_p3;
wire   [0:0] and_ln52_39_fu_2418_p2;
wire   [7:0] trunc_ln52_19_fu_2362_p4;
wire   [7:0] zext_ln52_19_fu_2424_p1;
wire   [20:0] tmp_40_fu_2434_p4;
wire   [0:0] tmp_301_fu_2456_p3;
wire   [0:0] icmp_ln52_129_fu_2450_p2;
wire   [0:0] icmp_ln52_128_fu_2444_p2;
wire   [0:0] tmp_300_fu_2404_p3;
wire   [0:0] select_ln52_79_fu_2470_p3;
wire   [0:0] select_ln52_123_fu_2478_p3;
wire   [0:0] xor_ln52_123_fu_2464_p2;
wire   [0:0] and_ln52_71_fu_2492_p2;
wire   [41:0] trunc_ln44_20_fu_452_p4;
wire   [11:0] tmp_41_fu_2544_p4;
wire   [0:0] tmp_303_fu_2528_p3;
wire   [0:0] icmp_ln52_130_fu_2554_p2;
wire   [0:0] or_ln52_62_fu_2568_p2;
wire   [0:0] tmp_304_fu_2536_p3;
wire   [0:0] and_ln52_41_fu_2574_p2;
wire   [7:0] trunc_ln52_20_fu_2518_p4;
wire   [7:0] zext_ln52_20_fu_2580_p1;
wire   [20:0] tmp_42_fu_2590_p4;
wire   [0:0] tmp_306_fu_2612_p3;
wire   [0:0] icmp_ln52_132_fu_2606_p2;
wire   [0:0] icmp_ln52_131_fu_2600_p2;
wire   [0:0] tmp_305_fu_2560_p3;
wire   [0:0] select_ln52_83_fu_2626_p3;
wire   [0:0] select_ln52_125_fu_2634_p3;
wire   [0:0] xor_ln52_124_fu_2620_p2;
wire   [0:0] and_ln52_73_fu_2648_p2;
wire   [41:0] trunc_ln44_21_fu_462_p4;
wire   [11:0] tmp_43_fu_2700_p4;
wire   [0:0] tmp_308_fu_2684_p3;
wire   [0:0] icmp_ln52_133_fu_2710_p2;
wire   [0:0] or_ln52_65_fu_2724_p2;
wire   [0:0] tmp_309_fu_2692_p3;
wire   [0:0] and_ln52_43_fu_2730_p2;
wire   [7:0] trunc_ln52_21_fu_2674_p4;
wire   [7:0] zext_ln52_21_fu_2736_p1;
wire   [20:0] tmp_44_fu_2746_p4;
wire   [0:0] tmp_311_fu_2768_p3;
wire   [0:0] icmp_ln52_135_fu_2762_p2;
wire   [0:0] icmp_ln52_134_fu_2756_p2;
wire   [0:0] tmp_310_fu_2716_p3;
wire   [0:0] select_ln52_87_fu_2782_p3;
wire   [0:0] select_ln52_127_fu_2790_p3;
wire   [0:0] xor_ln52_125_fu_2776_p2;
wire   [0:0] and_ln52_75_fu_2804_p2;
wire   [41:0] trunc_ln44_22_fu_472_p4;
wire   [11:0] tmp_45_fu_2856_p4;
wire   [0:0] tmp_313_fu_2840_p3;
wire   [0:0] icmp_ln52_136_fu_2866_p2;
wire   [0:0] or_ln52_68_fu_2880_p2;
wire   [0:0] tmp_314_fu_2848_p3;
wire   [0:0] and_ln52_45_fu_2886_p2;
wire   [7:0] trunc_ln52_22_fu_2830_p4;
wire   [7:0] zext_ln52_22_fu_2892_p1;
wire   [20:0] tmp_46_fu_2902_p4;
wire   [0:0] tmp_316_fu_2924_p3;
wire   [0:0] icmp_ln52_138_fu_2918_p2;
wire   [0:0] icmp_ln52_137_fu_2912_p2;
wire   [0:0] tmp_315_fu_2872_p3;
wire   [0:0] select_ln52_91_fu_2938_p3;
wire   [0:0] select_ln52_129_fu_2946_p3;
wire   [0:0] xor_ln52_126_fu_2932_p2;
wire   [0:0] and_ln52_77_fu_2960_p2;
wire   [6:0] trunc_ln52_63_fu_2972_p1;
wire   [6:0] select_ln52_32_fu_2985_p3;
wire   [0:0] xor_ln52_16_fu_2980_p2;
wire   [0:0] and_ln52_48_fu_2996_p2;
wire   [0:0] xor_ln52_fu_2975_p2;
wire   [7:0] zext_ln52_23_fu_2992_p1;
wire   [7:0] select_ln52_54_fu_3007_p3;
wire   [0:0] or_ln52_25_fu_3001_p2;
wire   [7:0] select_ln52_33_fu_3013_p3;
wire   [7:0] out_data_fu_3020_p3;
wire   [6:0] trunc_ln52_64_fu_3034_p1;
wire   [6:0] select_ln52_36_fu_3047_p3;
wire   [0:0] xor_ln52_18_fu_3042_p2;
wire   [0:0] and_ln52_50_fu_3058_p2;
wire   [0:0] xor_ln52_17_fu_3037_p2;
wire   [7:0] zext_ln52_24_fu_3054_p1;
wire   [7:0] select_ln52_95_fu_3069_p3;
wire   [0:0] or_ln52_28_fu_3063_p2;
wire   [7:0] select_ln52_37_fu_3075_p3;
wire   [7:0] out_data_24_fu_3082_p3;
wire   [6:0] trunc_ln52_65_fu_3096_p1;
wire   [6:0] select_ln52_40_fu_3109_p3;
wire   [0:0] xor_ln52_20_fu_3104_p2;
wire   [0:0] and_ln52_52_fu_3120_p2;
wire   [0:0] xor_ln52_19_fu_3099_p2;
wire   [7:0] zext_ln52_25_fu_3116_p1;
wire   [7:0] select_ln52_98_fu_3131_p3;
wire   [0:0] or_ln52_31_fu_3125_p2;
wire   [7:0] select_ln52_41_fu_3137_p3;
wire   [7:0] out_data_26_fu_3144_p3;
wire   [6:0] trunc_ln52_66_fu_3158_p1;
wire   [6:0] select_ln52_44_fu_3171_p3;
wire   [0:0] xor_ln52_22_fu_3166_p2;
wire   [0:0] and_ln52_54_fu_3182_p2;
wire   [0:0] xor_ln52_21_fu_3161_p2;
wire   [7:0] zext_ln52_26_fu_3178_p1;
wire   [7:0] select_ln52_101_fu_3193_p3;
wire   [0:0] or_ln52_34_fu_3187_p2;
wire   [7:0] select_ln52_45_fu_3199_p3;
wire   [7:0] out_data_28_fu_3206_p3;
wire   [6:0] trunc_ln52_67_fu_3220_p1;
wire   [6:0] select_ln52_48_fu_3233_p3;
wire   [0:0] xor_ln52_24_fu_3228_p2;
wire   [0:0] and_ln52_56_fu_3244_p2;
wire   [0:0] xor_ln52_23_fu_3223_p2;
wire   [7:0] zext_ln52_27_fu_3240_p1;
wire   [7:0] select_ln52_104_fu_3255_p3;
wire   [0:0] or_ln52_37_fu_3249_p2;
wire   [7:0] select_ln52_49_fu_3261_p3;
wire   [7:0] out_data_30_fu_3268_p3;
wire   [6:0] trunc_ln52_68_fu_3282_p1;
wire   [6:0] select_ln52_52_fu_3295_p3;
wire   [0:0] xor_ln52_26_fu_3290_p2;
wire   [0:0] and_ln52_58_fu_3306_p2;
wire   [0:0] xor_ln52_25_fu_3285_p2;
wire   [7:0] zext_ln52_28_fu_3302_p1;
wire   [7:0] select_ln52_107_fu_3317_p3;
wire   [0:0] or_ln52_40_fu_3311_p2;
wire   [7:0] select_ln52_53_fu_3323_p3;
wire   [7:0] out_data_32_fu_3330_p3;
wire   [6:0] trunc_ln52_69_fu_3344_p1;
wire   [6:0] select_ln52_56_fu_3357_p3;
wire   [0:0] xor_ln52_28_fu_3352_p2;
wire   [0:0] and_ln52_60_fu_3368_p2;
wire   [0:0] xor_ln52_27_fu_3347_p2;
wire   [7:0] zext_ln52_29_fu_3364_p1;
wire   [7:0] select_ln52_110_fu_3379_p3;
wire   [0:0] or_ln52_43_fu_3373_p2;
wire   [7:0] select_ln52_57_fu_3385_p3;
wire   [7:0] out_data_34_fu_3392_p3;
wire   [6:0] trunc_ln52_70_fu_3406_p1;
wire   [6:0] select_ln52_60_fu_3419_p3;
wire   [0:0] xor_ln52_30_fu_3414_p2;
wire   [0:0] and_ln52_62_fu_3430_p2;
wire   [0:0] xor_ln52_29_fu_3409_p2;
wire   [7:0] zext_ln52_30_fu_3426_p1;
wire   [7:0] select_ln52_113_fu_3441_p3;
wire   [0:0] or_ln52_46_fu_3435_p2;
wire   [7:0] select_ln52_61_fu_3447_p3;
wire   [7:0] out_data_36_fu_3454_p3;
wire   [6:0] trunc_ln52_71_fu_3468_p1;
wire   [6:0] select_ln52_64_fu_3481_p3;
wire   [0:0] xor_ln52_32_fu_3476_p2;
wire   [0:0] and_ln52_64_fu_3492_p2;
wire   [0:0] xor_ln52_31_fu_3471_p2;
wire   [7:0] zext_ln52_31_fu_3488_p1;
wire   [7:0] select_ln52_116_fu_3503_p3;
wire   [0:0] or_ln52_49_fu_3497_p2;
wire   [7:0] select_ln52_65_fu_3509_p3;
wire   [7:0] select_ln52_66_fu_3516_p3;
wire   [6:0] trunc_ln52_72_fu_3530_p1;
wire   [6:0] select_ln52_68_fu_3543_p3;
wire   [0:0] xor_ln52_34_fu_3538_p2;
wire   [0:0] and_ln52_66_fu_3554_p2;
wire   [0:0] xor_ln52_33_fu_3533_p2;
wire   [7:0] zext_ln52_32_fu_3550_p1;
wire   [7:0] select_ln52_118_fu_3565_p3;
wire   [0:0] or_ln52_52_fu_3559_p2;
wire   [7:0] select_ln52_69_fu_3571_p3;
wire   [7:0] select_ln52_70_fu_3578_p3;
wire   [6:0] trunc_ln52_73_fu_3592_p1;
wire   [6:0] select_ln52_72_fu_3605_p3;
wire   [0:0] xor_ln52_36_fu_3600_p2;
wire   [0:0] and_ln52_68_fu_3616_p2;
wire   [0:0] xor_ln52_35_fu_3595_p2;
wire   [7:0] zext_ln52_33_fu_3612_p1;
wire   [7:0] select_ln52_120_fu_3627_p3;
wire   [0:0] or_ln52_55_fu_3621_p2;
wire   [7:0] select_ln52_73_fu_3633_p3;
wire   [7:0] select_ln52_74_fu_3640_p3;
wire   [6:0] trunc_ln52_74_fu_3654_p1;
wire   [6:0] select_ln52_76_fu_3667_p3;
wire   [0:0] xor_ln52_38_fu_3662_p2;
wire   [0:0] and_ln52_70_fu_3678_p2;
wire   [0:0] xor_ln52_37_fu_3657_p2;
wire   [7:0] zext_ln52_34_fu_3674_p1;
wire   [7:0] select_ln52_122_fu_3689_p3;
wire   [0:0] or_ln52_58_fu_3683_p2;
wire   [7:0] select_ln52_77_fu_3695_p3;
wire   [7:0] select_ln52_78_fu_3702_p3;
wire   [6:0] trunc_ln52_75_fu_3716_p1;
wire   [6:0] select_ln52_80_fu_3729_p3;
wire   [0:0] xor_ln52_40_fu_3724_p2;
wire   [0:0] and_ln52_72_fu_3740_p2;
wire   [0:0] xor_ln52_39_fu_3719_p2;
wire   [7:0] zext_ln52_35_fu_3736_p1;
wire   [7:0] select_ln52_124_fu_3751_p3;
wire   [0:0] or_ln52_61_fu_3745_p2;
wire   [7:0] select_ln52_81_fu_3757_p3;
wire   [7:0] select_ln52_82_fu_3764_p3;
wire   [6:0] trunc_ln52_76_fu_3778_p1;
wire   [6:0] select_ln52_84_fu_3791_p3;
wire   [0:0] xor_ln52_42_fu_3786_p2;
wire   [0:0] and_ln52_74_fu_3802_p2;
wire   [0:0] xor_ln52_41_fu_3781_p2;
wire   [7:0] zext_ln52_36_fu_3798_p1;
wire   [7:0] select_ln52_126_fu_3813_p3;
wire   [0:0] or_ln52_64_fu_3807_p2;
wire   [7:0] select_ln52_85_fu_3819_p3;
wire   [7:0] select_ln52_86_fu_3826_p3;
wire   [6:0] trunc_ln52_77_fu_3840_p1;
wire   [6:0] select_ln52_88_fu_3853_p3;
wire   [0:0] xor_ln52_44_fu_3848_p2;
wire   [0:0] and_ln52_76_fu_3864_p2;
wire   [0:0] xor_ln52_43_fu_3843_p2;
wire   [7:0] zext_ln52_37_fu_3860_p1;
wire   [7:0] select_ln52_128_fu_3875_p3;
wire   [0:0] or_ln52_67_fu_3869_p2;
wire   [7:0] select_ln52_89_fu_3881_p3;
wire   [7:0] select_ln52_90_fu_3888_p3;
wire   [6:0] trunc_ln52_78_fu_3902_p1;
wire   [6:0] select_ln52_92_fu_3915_p3;
wire   [0:0] xor_ln52_46_fu_3910_p2;
wire   [0:0] and_ln52_78_fu_3926_p2;
wire   [0:0] xor_ln52_45_fu_3905_p2;
wire   [7:0] zext_ln52_38_fu_3922_p1;
wire   [7:0] select_ln52_130_fu_3937_p3;
wire   [0:0] or_ln52_70_fu_3931_p2;
wire   [7:0] select_ln52_93_fu_3943_p3;
wire   [7:0] select_ln52_94_fu_3950_p3;
wire   [7:0] select_ln51_7_fu_3957_p3;
wire   [7:0] select_ln51_6_fu_3895_p3;
wire   [7:0] select_ln51_5_fu_3833_p3;
wire   [7:0] select_ln51_4_fu_3771_p3;
wire   [7:0] select_ln51_3_fu_3709_p3;
wire   [7:0] select_ln51_2_fu_3647_p3;
wire   [7:0] select_ln51_1_fu_3585_p3;
wire   [7:0] select_ln51_fu_3523_p3;
wire   [7:0] out_data_37_fu_3461_p3;
wire   [7:0] out_data_35_fu_3399_p3;
wire   [7:0] out_data_33_fu_3337_p3;
wire   [7:0] out_data_31_fu_3275_p3;
wire   [7:0] out_data_29_fu_3213_p3;
wire   [7:0] out_data_27_fu_3151_p3;
wire   [7:0] out_data_25_fu_3089_p3;
wire   [7:0] out_data_23_fu_3027_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_273;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_286 = 7'd0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_273)) begin
        if ((icmp_ln41_fu_311_p2 == 1'd0)) begin
            i_fu_286 <= i_6_fu_317_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_286 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln52_10_reg_4113 <= add_ln52_10_fu_1024_p2;
        add_ln52_11_reg_4143 <= add_ln52_11_fu_1180_p2;
        add_ln52_12_reg_4173 <= add_ln52_12_fu_1336_p2;
        add_ln52_13_reg_4203 <= add_ln52_13_fu_1492_p2;
        add_ln52_14_reg_4233 <= add_ln52_14_fu_1648_p2;
        add_ln52_15_reg_4263 <= add_ln52_15_fu_1804_p2;
        add_ln52_16_reg_4293 <= add_ln52_16_fu_1960_p2;
        add_ln52_17_reg_4323 <= add_ln52_17_fu_2116_p2;
        add_ln52_18_reg_4353 <= add_ln52_18_fu_2272_p2;
        add_ln52_19_reg_4383 <= add_ln52_19_fu_2428_p2;
        add_ln52_20_reg_4413 <= add_ln52_20_fu_2584_p2;
        add_ln52_21_reg_4443 <= add_ln52_21_fu_2740_p2;
        add_ln52_22_reg_4473 <= add_ln52_22_fu_2896_p2;
        add_ln52_8_reg_4053 <= add_ln52_8_fu_712_p2;
        add_ln52_9_reg_4083 <= add_ln52_9_fu_868_p2;
        add_ln52_reg_4023 <= add_ln52_fu_556_p2;
        and_ln52_16_reg_4036 <= and_ln52_16_fu_626_p2;
        and_ln52_18_reg_4066 <= and_ln52_18_fu_782_p2;
        and_ln52_20_reg_4096 <= and_ln52_20_fu_938_p2;
        and_ln52_22_reg_4126 <= and_ln52_22_fu_1094_p2;
        and_ln52_24_reg_4156 <= and_ln52_24_fu_1250_p2;
        and_ln52_26_reg_4186 <= and_ln52_26_fu_1406_p2;
        and_ln52_28_reg_4216 <= and_ln52_28_fu_1562_p2;
        and_ln52_30_reg_4246 <= and_ln52_30_fu_1718_p2;
        and_ln52_32_reg_4276 <= and_ln52_32_fu_1874_p2;
        and_ln52_34_reg_4306 <= and_ln52_34_fu_2030_p2;
        and_ln52_36_reg_4336 <= and_ln52_36_fu_2186_p2;
        and_ln52_38_reg_4366 <= and_ln52_38_fu_2342_p2;
        and_ln52_40_reg_4396 <= and_ln52_40_fu_2498_p2;
        and_ln52_42_reg_4426 <= and_ln52_42_fu_2654_p2;
        and_ln52_44_reg_4456 <= and_ln52_44_fu_2810_p2;
        and_ln52_46_reg_4486 <= and_ln52_46_fu_2966_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln51_10_reg_4102 <= icmp_ln51_10_fu_944_p2;
        icmp_ln51_11_reg_4132 <= icmp_ln51_11_fu_1100_p2;
        icmp_ln51_12_reg_4162 <= icmp_ln51_12_fu_1256_p2;
        icmp_ln51_13_reg_4192 <= icmp_ln51_13_fu_1412_p2;
        icmp_ln51_14_reg_4222 <= icmp_ln51_14_fu_1568_p2;
        icmp_ln51_15_reg_4252 <= icmp_ln51_15_fu_1724_p2;
        icmp_ln51_16_reg_4282 <= icmp_ln51_16_fu_1880_p2;
        icmp_ln51_17_reg_4312 <= icmp_ln51_17_fu_2036_p2;
        icmp_ln51_18_reg_4342 <= icmp_ln51_18_fu_2192_p2;
        icmp_ln51_19_reg_4372 <= icmp_ln51_19_fu_2348_p2;
        icmp_ln51_20_reg_4402 <= icmp_ln51_20_fu_2504_p2;
        icmp_ln51_21_reg_4432 <= icmp_ln51_21_fu_2660_p2;
        icmp_ln51_22_reg_4462 <= icmp_ln51_22_fu_2816_p2;
        icmp_ln51_8_reg_4042 <= icmp_ln51_8_fu_632_p2;
        icmp_ln51_9_reg_4072 <= icmp_ln51_9_fu_788_p2;
        icmp_ln51_reg_4012 <= icmp_ln51_fu_482_p2;
        or_ln52_24_reg_4030 <= or_ln52_24_fu_614_p2;
        or_ln52_27_reg_4060 <= or_ln52_27_fu_770_p2;
        or_ln52_30_reg_4090 <= or_ln52_30_fu_926_p2;
        or_ln52_33_reg_4120 <= or_ln52_33_fu_1082_p2;
        or_ln52_36_reg_4150 <= or_ln52_36_fu_1238_p2;
        or_ln52_39_reg_4180 <= or_ln52_39_fu_1394_p2;
        or_ln52_42_reg_4210 <= or_ln52_42_fu_1550_p2;
        or_ln52_45_reg_4240 <= or_ln52_45_fu_1706_p2;
        or_ln52_48_reg_4270 <= or_ln52_48_fu_1862_p2;
        or_ln52_51_reg_4300 <= or_ln52_51_fu_2018_p2;
        or_ln52_54_reg_4330 <= or_ln52_54_fu_2174_p2;
        or_ln52_57_reg_4360 <= or_ln52_57_fu_2330_p2;
        or_ln52_60_reg_4390 <= or_ln52_60_fu_2486_p2;
        or_ln52_63_reg_4420 <= or_ln52_63_fu_2642_p2;
        or_ln52_66_reg_4450 <= or_ln52_66_fu_2798_p2;
        or_ln52_69_reg_4480 <= or_ln52_69_fu_2954_p2;
        tmp_242_reg_4047 <= layer14_out_dout[32'd83];
        tmp_247_reg_4077 <= layer14_out_dout[32'd125];
        tmp_252_reg_4107 <= layer14_out_dout[32'd167];
        tmp_257_reg_4137 <= layer14_out_dout[32'd209];
        tmp_262_reg_4167 <= layer14_out_dout[32'd251];
        tmp_267_reg_4197 <= layer14_out_dout[32'd293];
        tmp_272_reg_4227 <= layer14_out_dout[32'd335];
        tmp_277_reg_4257 <= layer14_out_dout[32'd377];
        tmp_282_reg_4287 <= layer14_out_dout[32'd419];
        tmp_287_reg_4317 <= layer14_out_dout[32'd461];
        tmp_292_reg_4347 <= layer14_out_dout[32'd503];
        tmp_297_reg_4377 <= layer14_out_dout[32'd545];
        tmp_302_reg_4407 <= layer14_out_dout[32'd587];
        tmp_307_reg_4437 <= layer14_out_dout[32'd629];
        tmp_312_reg_4467 <= layer14_out_dout[32'd671];
        tmp_reg_4017 <= layer14_out_dout[32'd41];
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_311_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_5 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_5 = i_fu_286;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer14_out_blk_n = layer14_out_empty_n;
    end else begin
        layer14_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer14_out_read = 1'b1;
    end else begin
        layer14_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer15_out_blk_n = layer15_out_full_n;
    end else begin
        layer15_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer15_out_write = 1'b1;
    end else begin
        layer15_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_10_fu_1024_p2 = (trunc_ln52_10_fu_958_p4 + zext_ln52_10_fu_1020_p1);

assign add_ln52_11_fu_1180_p2 = (trunc_ln52_11_fu_1114_p4 + zext_ln52_11_fu_1176_p1);

assign add_ln52_12_fu_1336_p2 = (trunc_ln52_12_fu_1270_p4 + zext_ln52_12_fu_1332_p1);

assign add_ln52_13_fu_1492_p2 = (trunc_ln52_13_fu_1426_p4 + zext_ln52_13_fu_1488_p1);

assign add_ln52_14_fu_1648_p2 = (trunc_ln52_14_fu_1582_p4 + zext_ln52_14_fu_1644_p1);

assign add_ln52_15_fu_1804_p2 = (trunc_ln52_15_fu_1738_p4 + zext_ln52_15_fu_1800_p1);

assign add_ln52_16_fu_1960_p2 = (trunc_ln52_16_fu_1894_p4 + zext_ln52_16_fu_1956_p1);

assign add_ln52_17_fu_2116_p2 = (trunc_ln52_17_fu_2050_p4 + zext_ln52_17_fu_2112_p1);

assign add_ln52_18_fu_2272_p2 = (trunc_ln52_18_fu_2206_p4 + zext_ln52_18_fu_2268_p1);

assign add_ln52_19_fu_2428_p2 = (trunc_ln52_19_fu_2362_p4 + zext_ln52_19_fu_2424_p1);

assign add_ln52_20_fu_2584_p2 = (trunc_ln52_20_fu_2518_p4 + zext_ln52_20_fu_2580_p1);

assign add_ln52_21_fu_2740_p2 = (trunc_ln52_21_fu_2674_p4 + zext_ln52_21_fu_2736_p1);

assign add_ln52_22_fu_2896_p2 = (trunc_ln52_22_fu_2830_p4 + zext_ln52_22_fu_2892_p1);

assign add_ln52_8_fu_712_p2 = (trunc_ln52_8_fu_646_p4 + zext_ln52_8_fu_708_p1);

assign add_ln52_9_fu_868_p2 = (trunc_ln52_9_fu_802_p4 + zext_ln52_9_fu_864_p1);

assign add_ln52_fu_556_p2 = (trunc_ln5_fu_496_p4 + zext_ln52_fu_552_p1);

assign and_ln52_16_fu_626_p2 = (tmp_240_fu_532_p3 & and_ln52_47_fu_620_p2);

assign and_ln52_17_fu_702_p2 = (tmp_244_fu_664_p3 & or_ln52_26_fu_696_p2);

assign and_ln52_18_fu_782_p2 = (tmp_245_fu_688_p3 & and_ln52_49_fu_776_p2);

assign and_ln52_19_fu_858_p2 = (tmp_249_fu_820_p3 & or_ln52_29_fu_852_p2);

assign and_ln52_20_fu_938_p2 = (tmp_250_fu_844_p3 & and_ln52_51_fu_932_p2);

assign and_ln52_21_fu_1014_p2 = (tmp_254_fu_976_p3 & or_ln52_32_fu_1008_p2);

assign and_ln52_22_fu_1094_p2 = (tmp_255_fu_1000_p3 & and_ln52_53_fu_1088_p2);

assign and_ln52_23_fu_1170_p2 = (tmp_259_fu_1132_p3 & or_ln52_35_fu_1164_p2);

assign and_ln52_24_fu_1250_p2 = (tmp_260_fu_1156_p3 & and_ln52_55_fu_1244_p2);

assign and_ln52_25_fu_1326_p2 = (tmp_264_fu_1288_p3 & or_ln52_38_fu_1320_p2);

assign and_ln52_26_fu_1406_p2 = (tmp_265_fu_1312_p3 & and_ln52_57_fu_1400_p2);

assign and_ln52_27_fu_1482_p2 = (tmp_269_fu_1444_p3 & or_ln52_41_fu_1476_p2);

assign and_ln52_28_fu_1562_p2 = (tmp_270_fu_1468_p3 & and_ln52_59_fu_1556_p2);

assign and_ln52_29_fu_1638_p2 = (tmp_274_fu_1600_p3 & or_ln52_44_fu_1632_p2);

assign and_ln52_30_fu_1718_p2 = (tmp_275_fu_1624_p3 & and_ln52_61_fu_1712_p2);

assign and_ln52_31_fu_1794_p2 = (tmp_279_fu_1756_p3 & or_ln52_47_fu_1788_p2);

assign and_ln52_32_fu_1874_p2 = (tmp_280_fu_1780_p3 & and_ln52_63_fu_1868_p2);

assign and_ln52_33_fu_1950_p2 = (tmp_284_fu_1912_p3 & or_ln52_50_fu_1944_p2);

assign and_ln52_34_fu_2030_p2 = (tmp_285_fu_1936_p3 & and_ln52_65_fu_2024_p2);

assign and_ln52_35_fu_2106_p2 = (tmp_289_fu_2068_p3 & or_ln52_53_fu_2100_p2);

assign and_ln52_36_fu_2186_p2 = (tmp_290_fu_2092_p3 & and_ln52_67_fu_2180_p2);

assign and_ln52_37_fu_2262_p2 = (tmp_294_fu_2224_p3 & or_ln52_56_fu_2256_p2);

assign and_ln52_38_fu_2342_p2 = (tmp_295_fu_2248_p3 & and_ln52_69_fu_2336_p2);

assign and_ln52_39_fu_2418_p2 = (tmp_299_fu_2380_p3 & or_ln52_59_fu_2412_p2);

assign and_ln52_40_fu_2498_p2 = (tmp_300_fu_2404_p3 & and_ln52_71_fu_2492_p2);

assign and_ln52_41_fu_2574_p2 = (tmp_304_fu_2536_p3 & or_ln52_62_fu_2568_p2);

assign and_ln52_42_fu_2654_p2 = (tmp_305_fu_2560_p3 & and_ln52_73_fu_2648_p2);

assign and_ln52_43_fu_2730_p2 = (tmp_309_fu_2692_p3 & or_ln52_65_fu_2724_p2);

assign and_ln52_44_fu_2810_p2 = (tmp_310_fu_2716_p3 & and_ln52_75_fu_2804_p2);

assign and_ln52_45_fu_2886_p2 = (tmp_314_fu_2848_p3 & or_ln52_68_fu_2880_p2);

assign and_ln52_46_fu_2966_p2 = (tmp_315_fu_2872_p3 & and_ln52_77_fu_2960_p2);

assign and_ln52_47_fu_620_p2 = (xor_ln52_111_fu_592_p2 & icmp_ln52_59_fu_572_p2);

assign and_ln52_48_fu_2996_p2 = (xor_ln52_16_fu_2980_p2 & tmp_reg_4017);

assign and_ln52_49_fu_776_p2 = (xor_ln52_112_fu_748_p2 & icmp_ln52_66_fu_728_p2);

assign and_ln52_50_fu_3058_p2 = (xor_ln52_18_fu_3042_p2 & tmp_242_reg_4047);

assign and_ln52_51_fu_932_p2 = (xor_ln52_113_fu_904_p2 & icmp_ln52_73_fu_884_p2);

assign and_ln52_52_fu_3120_p2 = (xor_ln52_20_fu_3104_p2 & tmp_247_reg_4077);

assign and_ln52_53_fu_1088_p2 = (xor_ln52_114_fu_1060_p2 & icmp_ln52_80_fu_1040_p2);

assign and_ln52_54_fu_3182_p2 = (xor_ln52_22_fu_3166_p2 & tmp_252_reg_4107);

assign and_ln52_55_fu_1244_p2 = (xor_ln52_115_fu_1216_p2 & icmp_ln52_87_fu_1196_p2);

assign and_ln52_56_fu_3244_p2 = (xor_ln52_24_fu_3228_p2 & tmp_257_reg_4137);

assign and_ln52_57_fu_1400_p2 = (xor_ln52_116_fu_1372_p2 & icmp_ln52_94_fu_1352_p2);

assign and_ln52_58_fu_3306_p2 = (xor_ln52_26_fu_3290_p2 & tmp_262_reg_4167);

assign and_ln52_59_fu_1556_p2 = (xor_ln52_117_fu_1528_p2 & icmp_ln52_101_fu_1508_p2);

assign and_ln52_60_fu_3368_p2 = (xor_ln52_28_fu_3352_p2 & tmp_267_reg_4197);

assign and_ln52_61_fu_1712_p2 = (xor_ln52_118_fu_1684_p2 & icmp_ln52_108_fu_1664_p2);

assign and_ln52_62_fu_3430_p2 = (xor_ln52_30_fu_3414_p2 & tmp_272_reg_4227);

assign and_ln52_63_fu_1868_p2 = (xor_ln52_119_fu_1840_p2 & icmp_ln52_115_fu_1820_p2);

assign and_ln52_64_fu_3492_p2 = (xor_ln52_32_fu_3476_p2 & tmp_277_reg_4257);

assign and_ln52_65_fu_2024_p2 = (xor_ln52_120_fu_1996_p2 & icmp_ln52_119_fu_1976_p2);

assign and_ln52_66_fu_3554_p2 = (xor_ln52_34_fu_3538_p2 & tmp_282_reg_4287);

assign and_ln52_67_fu_2180_p2 = (xor_ln52_121_fu_2152_p2 & icmp_ln52_122_fu_2132_p2);

assign and_ln52_68_fu_3616_p2 = (xor_ln52_36_fu_3600_p2 & tmp_287_reg_4317);

assign and_ln52_69_fu_2336_p2 = (xor_ln52_122_fu_2308_p2 & icmp_ln52_125_fu_2288_p2);

assign and_ln52_70_fu_3678_p2 = (xor_ln52_38_fu_3662_p2 & tmp_292_reg_4347);

assign and_ln52_71_fu_2492_p2 = (xor_ln52_123_fu_2464_p2 & icmp_ln52_128_fu_2444_p2);

assign and_ln52_72_fu_3740_p2 = (xor_ln52_40_fu_3724_p2 & tmp_297_reg_4377);

assign and_ln52_73_fu_2648_p2 = (xor_ln52_124_fu_2620_p2 & icmp_ln52_131_fu_2600_p2);

assign and_ln52_74_fu_3802_p2 = (xor_ln52_42_fu_3786_p2 & tmp_302_reg_4407);

assign and_ln52_75_fu_2804_p2 = (xor_ln52_125_fu_2776_p2 & icmp_ln52_134_fu_2756_p2);

assign and_ln52_76_fu_3864_p2 = (xor_ln52_44_fu_3848_p2 & tmp_307_reg_4437);

assign and_ln52_77_fu_2960_p2 = (xor_ln52_126_fu_2932_p2 & icmp_ln52_137_fu_2912_p2);

assign and_ln52_78_fu_3926_p2 = (xor_ln52_46_fu_3910_p2 & tmp_312_reg_4467);

assign and_ln52_fu_546_p2 = (tmp_239_fu_514_p3 & or_ln52_fu_540_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer14_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer15_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_273 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_6_fu_317_p2 = (ap_sig_allocacmp_i_5 + 7'd1);

assign icmp_ln41_fu_311_p2 = ((ap_sig_allocacmp_i_5 == 7'd70) ? 1'b1 : 1'b0);

assign icmp_ln51_10_fu_944_p2 = (($signed(trunc_ln44_10_fu_352_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_1100_p2 = (($signed(trunc_ln44_11_fu_362_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_1256_p2 = (($signed(trunc_ln44_12_fu_372_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_1412_p2 = (($signed(trunc_ln44_13_fu_382_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_1568_p2 = (($signed(trunc_ln44_14_fu_392_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_1724_p2 = (($signed(trunc_ln44_15_fu_402_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_16_fu_1880_p2 = (($signed(trunc_ln44_16_fu_412_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_17_fu_2036_p2 = (($signed(trunc_ln44_17_fu_422_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_18_fu_2192_p2 = (($signed(trunc_ln44_18_fu_432_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_19_fu_2348_p2 = (($signed(trunc_ln44_19_fu_442_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_20_fu_2504_p2 = (($signed(trunc_ln44_20_fu_452_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_21_fu_2660_p2 = (($signed(trunc_ln44_21_fu_462_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_22_fu_2816_p2 = (($signed(trunc_ln44_22_fu_472_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_632_p2 = (($signed(trunc_ln44_8_fu_332_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_788_p2 = (($signed(trunc_ln44_9_fu_342_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_482_p2 = (($signed(trunc_ln44_fu_328_p1) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln52_101_fu_1508_p2 = ((tmp_28_fu_1498_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_102_fu_1514_p2 = ((tmp_28_fu_1498_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_106_fu_1618_p2 = ((tmp_29_fu_1608_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_108_fu_1664_p2 = ((tmp_30_fu_1654_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_109_fu_1670_p2 = ((tmp_30_fu_1654_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_113_fu_1774_p2 = ((tmp_31_fu_1764_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_115_fu_1820_p2 = ((tmp_32_fu_1810_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_116_fu_1826_p2 = ((tmp_32_fu_1810_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_119_fu_1976_p2 = ((tmp_34_fu_1966_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_120_fu_1982_p2 = ((tmp_34_fu_1966_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_121_fu_2086_p2 = ((tmp_35_fu_2076_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_122_fu_2132_p2 = ((tmp_36_fu_2122_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_123_fu_2138_p2 = ((tmp_36_fu_2122_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_124_fu_2242_p2 = ((tmp_37_fu_2232_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_125_fu_2288_p2 = ((tmp_38_fu_2278_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_126_fu_2294_p2 = ((tmp_38_fu_2278_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_127_fu_2398_p2 = ((tmp_39_fu_2388_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_128_fu_2444_p2 = ((tmp_40_fu_2434_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_129_fu_2450_p2 = ((tmp_40_fu_2434_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_130_fu_2554_p2 = ((tmp_41_fu_2544_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_131_fu_2600_p2 = ((tmp_42_fu_2590_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_132_fu_2606_p2 = ((tmp_42_fu_2590_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_133_fu_2710_p2 = ((tmp_43_fu_2700_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_134_fu_2756_p2 = ((tmp_44_fu_2746_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_135_fu_2762_p2 = ((tmp_44_fu_2746_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_136_fu_2866_p2 = ((tmp_45_fu_2856_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_137_fu_2912_p2 = ((tmp_46_fu_2902_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_138_fu_2918_p2 = ((tmp_46_fu_2902_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_57_fu_526_p2 = ((trunc_ln52_fu_522_p1 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_59_fu_572_p2 = ((tmp_16_fu_562_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_60_fu_578_p2 = ((tmp_16_fu_562_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_64_fu_682_p2 = ((tmp_17_fu_672_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_66_fu_728_p2 = ((tmp_18_fu_718_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_67_fu_734_p2 = ((tmp_18_fu_718_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_71_fu_838_p2 = ((tmp_19_fu_828_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_73_fu_884_p2 = ((tmp_20_fu_874_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_74_fu_890_p2 = ((tmp_20_fu_874_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_78_fu_994_p2 = ((tmp_21_fu_984_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_80_fu_1040_p2 = ((tmp_22_fu_1030_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_81_fu_1046_p2 = ((tmp_22_fu_1030_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_85_fu_1150_p2 = ((tmp_23_fu_1140_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_87_fu_1196_p2 = ((tmp_24_fu_1186_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_88_fu_1202_p2 = ((tmp_24_fu_1186_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_92_fu_1306_p2 = ((tmp_25_fu_1296_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_94_fu_1352_p2 = ((tmp_26_fu_1342_p4 == 21'd2097151) ? 1'b1 : 1'b0);

assign icmp_ln52_95_fu_1358_p2 = ((tmp_26_fu_1342_p4 == 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_99_fu_1462_p2 = ((tmp_27_fu_1452_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_1930_p2 = ((tmp_33_fu_1920_p4 != 12'd0) ? 1'b1 : 1'b0);

assign layer15_out_din = {{{{{{{{{{{{{{{{select_ln51_7_fu_3957_p3}, {select_ln51_6_fu_3895_p3}}, {select_ln51_5_fu_3833_p3}}, {select_ln51_4_fu_3771_p3}}, {select_ln51_3_fu_3709_p3}}, {select_ln51_2_fu_3647_p3}}, {select_ln51_1_fu_3585_p3}}, {select_ln51_fu_3523_p3}}, {out_data_37_fu_3461_p3}}, {out_data_35_fu_3399_p3}}, {out_data_33_fu_3337_p3}}, {out_data_31_fu_3275_p3}}, {out_data_29_fu_3213_p3}}, {out_data_27_fu_3151_p3}}, {out_data_25_fu_3089_p3}}, {out_data_23_fu_3027_p3}};

assign or_ln52_24_fu_614_p2 = (tmp_fu_488_p3 | select_ln52_50_fu_606_p3);

assign or_ln52_25_fu_3001_p2 = (xor_ln52_fu_2975_p2 | and_ln52_48_fu_2996_p2);

assign or_ln52_26_fu_696_p2 = (tmp_243_fu_656_p3 | icmp_ln52_64_fu_682_p2);

assign or_ln52_27_fu_770_p2 = (tmp_242_fu_638_p3 | select_ln52_62_fu_762_p3);

assign or_ln52_28_fu_3063_p2 = (xor_ln52_17_fu_3037_p2 | and_ln52_50_fu_3058_p2);

assign or_ln52_29_fu_852_p2 = (tmp_248_fu_812_p3 | icmp_ln52_71_fu_838_p2);

assign or_ln52_30_fu_926_p2 = (tmp_247_fu_794_p3 | select_ln52_97_fu_918_p3);

assign or_ln52_31_fu_3125_p2 = (xor_ln52_19_fu_3099_p2 | and_ln52_52_fu_3120_p2);

assign or_ln52_32_fu_1008_p2 = (tmp_253_fu_968_p3 | icmp_ln52_78_fu_994_p2);

assign or_ln52_33_fu_1082_p2 = (tmp_252_fu_950_p3 | select_ln52_100_fu_1074_p3);

assign or_ln52_34_fu_3187_p2 = (xor_ln52_21_fu_3161_p2 | and_ln52_54_fu_3182_p2);

assign or_ln52_35_fu_1164_p2 = (tmp_258_fu_1124_p3 | icmp_ln52_85_fu_1150_p2);

assign or_ln52_36_fu_1238_p2 = (tmp_257_fu_1106_p3 | select_ln52_103_fu_1230_p3);

assign or_ln52_37_fu_3249_p2 = (xor_ln52_23_fu_3223_p2 | and_ln52_56_fu_3244_p2);

assign or_ln52_38_fu_1320_p2 = (tmp_263_fu_1280_p3 | icmp_ln52_92_fu_1306_p2);

assign or_ln52_39_fu_1394_p2 = (tmp_262_fu_1262_p3 | select_ln52_106_fu_1386_p3);

assign or_ln52_40_fu_3311_p2 = (xor_ln52_25_fu_3285_p2 | and_ln52_58_fu_3306_p2);

assign or_ln52_41_fu_1476_p2 = (tmp_268_fu_1436_p3 | icmp_ln52_99_fu_1462_p2);

assign or_ln52_42_fu_1550_p2 = (tmp_267_fu_1418_p3 | select_ln52_109_fu_1542_p3);

assign or_ln52_43_fu_3373_p2 = (xor_ln52_27_fu_3347_p2 | and_ln52_60_fu_3368_p2);

assign or_ln52_44_fu_1632_p2 = (tmp_273_fu_1592_p3 | icmp_ln52_106_fu_1618_p2);

assign or_ln52_45_fu_1706_p2 = (tmp_272_fu_1574_p3 | select_ln52_112_fu_1698_p3);

assign or_ln52_46_fu_3435_p2 = (xor_ln52_29_fu_3409_p2 | and_ln52_62_fu_3430_p2);

assign or_ln52_47_fu_1788_p2 = (tmp_278_fu_1748_p3 | icmp_ln52_113_fu_1774_p2);

assign or_ln52_48_fu_1862_p2 = (tmp_277_fu_1730_p3 | select_ln52_115_fu_1854_p3);

assign or_ln52_49_fu_3497_p2 = (xor_ln52_31_fu_3471_p2 | and_ln52_64_fu_3492_p2);

assign or_ln52_50_fu_1944_p2 = (tmp_283_fu_1904_p3 | icmp_ln52_fu_1930_p2);

assign or_ln52_51_fu_2018_p2 = (tmp_282_fu_1886_p3 | select_ln52_117_fu_2010_p3);

assign or_ln52_52_fu_3559_p2 = (xor_ln52_33_fu_3533_p2 | and_ln52_66_fu_3554_p2);

assign or_ln52_53_fu_2100_p2 = (tmp_288_fu_2060_p3 | icmp_ln52_121_fu_2086_p2);

assign or_ln52_54_fu_2174_p2 = (tmp_287_fu_2042_p3 | select_ln52_119_fu_2166_p3);

assign or_ln52_55_fu_3621_p2 = (xor_ln52_35_fu_3595_p2 | and_ln52_68_fu_3616_p2);

assign or_ln52_56_fu_2256_p2 = (tmp_293_fu_2216_p3 | icmp_ln52_124_fu_2242_p2);

assign or_ln52_57_fu_2330_p2 = (tmp_292_fu_2198_p3 | select_ln52_121_fu_2322_p3);

assign or_ln52_58_fu_3683_p2 = (xor_ln52_37_fu_3657_p2 | and_ln52_70_fu_3678_p2);

assign or_ln52_59_fu_2412_p2 = (tmp_298_fu_2372_p3 | icmp_ln52_127_fu_2398_p2);

assign or_ln52_60_fu_2486_p2 = (tmp_297_fu_2354_p3 | select_ln52_123_fu_2478_p3);

assign or_ln52_61_fu_3745_p2 = (xor_ln52_39_fu_3719_p2 | and_ln52_72_fu_3740_p2);

assign or_ln52_62_fu_2568_p2 = (tmp_303_fu_2528_p3 | icmp_ln52_130_fu_2554_p2);

assign or_ln52_63_fu_2642_p2 = (tmp_302_fu_2510_p3 | select_ln52_125_fu_2634_p3);

assign or_ln52_64_fu_3807_p2 = (xor_ln52_41_fu_3781_p2 | and_ln52_74_fu_3802_p2);

assign or_ln52_65_fu_2724_p2 = (tmp_308_fu_2684_p3 | icmp_ln52_133_fu_2710_p2);

assign or_ln52_66_fu_2798_p2 = (tmp_307_fu_2666_p3 | select_ln52_127_fu_2790_p3);

assign or_ln52_67_fu_3869_p2 = (xor_ln52_43_fu_3843_p2 | and_ln52_76_fu_3864_p2);

assign or_ln52_68_fu_2880_p2 = (tmp_313_fu_2840_p3 | icmp_ln52_136_fu_2866_p2);

assign or_ln52_69_fu_2954_p2 = (tmp_312_fu_2822_p3 | select_ln52_129_fu_2946_p3);

assign or_ln52_70_fu_3931_p2 = (xor_ln52_45_fu_3905_p2 | and_ln52_78_fu_3926_p2);

assign or_ln52_fu_540_p2 = (tmp_238_fu_506_p3 | icmp_ln52_57_fu_526_p2);

assign out_data_23_fu_3027_p3 = ((icmp_ln51_reg_4012[0:0] == 1'b1) ? out_data_fu_3020_p3 : 8'd0);

assign out_data_24_fu_3082_p3 = ((or_ln52_28_fu_3063_p2[0:0] == 1'b1) ? select_ln52_37_fu_3075_p3 : add_ln52_8_reg_4053);

assign out_data_25_fu_3089_p3 = ((icmp_ln51_8_reg_4042[0:0] == 1'b1) ? out_data_24_fu_3082_p3 : 8'd0);

assign out_data_26_fu_3144_p3 = ((or_ln52_31_fu_3125_p2[0:0] == 1'b1) ? select_ln52_41_fu_3137_p3 : add_ln52_9_reg_4083);

assign out_data_27_fu_3151_p3 = ((icmp_ln51_9_reg_4072[0:0] == 1'b1) ? out_data_26_fu_3144_p3 : 8'd0);

assign out_data_28_fu_3206_p3 = ((or_ln52_34_fu_3187_p2[0:0] == 1'b1) ? select_ln52_45_fu_3199_p3 : add_ln52_10_reg_4113);

assign out_data_29_fu_3213_p3 = ((icmp_ln51_10_reg_4102[0:0] == 1'b1) ? out_data_28_fu_3206_p3 : 8'd0);

assign out_data_30_fu_3268_p3 = ((or_ln52_37_fu_3249_p2[0:0] == 1'b1) ? select_ln52_49_fu_3261_p3 : add_ln52_11_reg_4143);

assign out_data_31_fu_3275_p3 = ((icmp_ln51_11_reg_4132[0:0] == 1'b1) ? out_data_30_fu_3268_p3 : 8'd0);

assign out_data_32_fu_3330_p3 = ((or_ln52_40_fu_3311_p2[0:0] == 1'b1) ? select_ln52_53_fu_3323_p3 : add_ln52_12_reg_4173);

assign out_data_33_fu_3337_p3 = ((icmp_ln51_12_reg_4162[0:0] == 1'b1) ? out_data_32_fu_3330_p3 : 8'd0);

assign out_data_34_fu_3392_p3 = ((or_ln52_43_fu_3373_p2[0:0] == 1'b1) ? select_ln52_57_fu_3385_p3 : add_ln52_13_reg_4203);

assign out_data_35_fu_3399_p3 = ((icmp_ln51_13_reg_4192[0:0] == 1'b1) ? out_data_34_fu_3392_p3 : 8'd0);

assign out_data_36_fu_3454_p3 = ((or_ln52_46_fu_3435_p2[0:0] == 1'b1) ? select_ln52_61_fu_3447_p3 : add_ln52_14_reg_4233);

assign out_data_37_fu_3461_p3 = ((icmp_ln51_14_reg_4222[0:0] == 1'b1) ? out_data_36_fu_3454_p3 : 8'd0);

assign out_data_fu_3020_p3 = ((or_ln52_25_fu_3001_p2[0:0] == 1'b1) ? select_ln52_33_fu_3013_p3 : add_ln52_reg_4023);

assign select_ln51_1_fu_3585_p3 = ((icmp_ln51_16_reg_4282[0:0] == 1'b1) ? select_ln52_70_fu_3578_p3 : 8'd0);

assign select_ln51_2_fu_3647_p3 = ((icmp_ln51_17_reg_4312[0:0] == 1'b1) ? select_ln52_74_fu_3640_p3 : 8'd0);

assign select_ln51_3_fu_3709_p3 = ((icmp_ln51_18_reg_4342[0:0] == 1'b1) ? select_ln52_78_fu_3702_p3 : 8'd0);

assign select_ln51_4_fu_3771_p3 = ((icmp_ln51_19_reg_4372[0:0] == 1'b1) ? select_ln52_82_fu_3764_p3 : 8'd0);

assign select_ln51_5_fu_3833_p3 = ((icmp_ln51_20_reg_4402[0:0] == 1'b1) ? select_ln52_86_fu_3826_p3 : 8'd0);

assign select_ln51_6_fu_3895_p3 = ((icmp_ln51_21_reg_4432[0:0] == 1'b1) ? select_ln52_90_fu_3888_p3 : 8'd0);

assign select_ln51_7_fu_3957_p3 = ((icmp_ln51_22_reg_4462[0:0] == 1'b1) ? select_ln52_94_fu_3950_p3 : 8'd0);

assign select_ln51_fu_3523_p3 = ((icmp_ln51_15_reg_4252[0:0] == 1'b1) ? select_ln52_66_fu_3516_p3 : 8'd0);

assign select_ln52_100_fu_1074_p3 = ((tmp_255_fu_1000_p3[0:0] == 1'b1) ? select_ln52_43_fu_1066_p3 : icmp_ln52_81_fu_1046_p2);

assign select_ln52_101_fu_3193_p3 = ((tmp_252_reg_4107[0:0] == 1'b1) ? zext_ln52_26_fu_3178_p1 : add_ln52_10_reg_4113);

assign select_ln52_103_fu_1230_p3 = ((tmp_260_fu_1156_p3[0:0] == 1'b1) ? select_ln52_47_fu_1222_p3 : icmp_ln52_88_fu_1202_p2);

assign select_ln52_104_fu_3255_p3 = ((tmp_257_reg_4137[0:0] == 1'b1) ? zext_ln52_27_fu_3240_p1 : add_ln52_11_reg_4143);

assign select_ln52_106_fu_1386_p3 = ((tmp_265_fu_1312_p3[0:0] == 1'b1) ? select_ln52_51_fu_1378_p3 : icmp_ln52_95_fu_1358_p2);

assign select_ln52_107_fu_3317_p3 = ((tmp_262_reg_4167[0:0] == 1'b1) ? zext_ln52_28_fu_3302_p1 : add_ln52_12_reg_4173);

assign select_ln52_109_fu_1542_p3 = ((tmp_270_fu_1468_p3[0:0] == 1'b1) ? select_ln52_55_fu_1534_p3 : icmp_ln52_102_fu_1514_p2);

assign select_ln52_110_fu_3379_p3 = ((tmp_267_reg_4197[0:0] == 1'b1) ? zext_ln52_29_fu_3364_p1 : add_ln52_13_reg_4203);

assign select_ln52_112_fu_1698_p3 = ((tmp_275_fu_1624_p3[0:0] == 1'b1) ? select_ln52_59_fu_1690_p3 : icmp_ln52_109_fu_1670_p2);

assign select_ln52_113_fu_3441_p3 = ((tmp_272_reg_4227[0:0] == 1'b1) ? zext_ln52_30_fu_3426_p1 : add_ln52_14_reg_4233);

assign select_ln52_115_fu_1854_p3 = ((tmp_280_fu_1780_p3[0:0] == 1'b1) ? select_ln52_63_fu_1846_p3 : icmp_ln52_116_fu_1826_p2);

assign select_ln52_116_fu_3503_p3 = ((tmp_277_reg_4257[0:0] == 1'b1) ? zext_ln52_31_fu_3488_p1 : add_ln52_15_reg_4263);

assign select_ln52_117_fu_2010_p3 = ((tmp_285_fu_1936_p3[0:0] == 1'b1) ? select_ln52_67_fu_2002_p3 : icmp_ln52_120_fu_1982_p2);

assign select_ln52_118_fu_3565_p3 = ((tmp_282_reg_4287[0:0] == 1'b1) ? zext_ln52_32_fu_3550_p1 : add_ln52_16_reg_4293);

assign select_ln52_119_fu_2166_p3 = ((tmp_290_fu_2092_p3[0:0] == 1'b1) ? select_ln52_71_fu_2158_p3 : icmp_ln52_123_fu_2138_p2);

assign select_ln52_120_fu_3627_p3 = ((tmp_287_reg_4317[0:0] == 1'b1) ? zext_ln52_33_fu_3612_p1 : add_ln52_17_reg_4323);

assign select_ln52_121_fu_2322_p3 = ((tmp_295_fu_2248_p3[0:0] == 1'b1) ? select_ln52_75_fu_2314_p3 : icmp_ln52_126_fu_2294_p2);

assign select_ln52_122_fu_3689_p3 = ((tmp_292_reg_4347[0:0] == 1'b1) ? zext_ln52_34_fu_3674_p1 : add_ln52_18_reg_4353);

assign select_ln52_123_fu_2478_p3 = ((tmp_300_fu_2404_p3[0:0] == 1'b1) ? select_ln52_79_fu_2470_p3 : icmp_ln52_129_fu_2450_p2);

assign select_ln52_124_fu_3751_p3 = ((tmp_297_reg_4377[0:0] == 1'b1) ? zext_ln52_35_fu_3736_p1 : add_ln52_19_reg_4383);

assign select_ln52_125_fu_2634_p3 = ((tmp_305_fu_2560_p3[0:0] == 1'b1) ? select_ln52_83_fu_2626_p3 : icmp_ln52_132_fu_2606_p2);

assign select_ln52_126_fu_3813_p3 = ((tmp_302_reg_4407[0:0] == 1'b1) ? zext_ln52_36_fu_3798_p1 : add_ln52_20_reg_4413);

assign select_ln52_127_fu_2790_p3 = ((tmp_310_fu_2716_p3[0:0] == 1'b1) ? select_ln52_87_fu_2782_p3 : icmp_ln52_135_fu_2762_p2);

assign select_ln52_128_fu_3875_p3 = ((tmp_307_reg_4437[0:0] == 1'b1) ? zext_ln52_37_fu_3860_p1 : add_ln52_21_reg_4443);

assign select_ln52_129_fu_2946_p3 = ((tmp_315_fu_2872_p3[0:0] == 1'b1) ? select_ln52_91_fu_2938_p3 : icmp_ln52_138_fu_2918_p2);

assign select_ln52_130_fu_3937_p3 = ((tmp_312_reg_4467[0:0] == 1'b1) ? zext_ln52_38_fu_3922_p1 : add_ln52_22_reg_4473);

assign select_ln52_32_fu_2985_p3 = ((and_ln52_16_reg_4036[0:0] == 1'b1) ? trunc_ln52_63_fu_2972_p1 : 7'd0);

assign select_ln52_33_fu_3013_p3 = ((or_ln52_24_reg_4030[0:0] == 1'b1) ? select_ln52_54_fu_3007_p3 : 8'd255);

assign select_ln52_35_fu_754_p3 = ((tmp_246_fu_740_p3[0:0] == 1'b1) ? icmp_ln52_67_fu_734_p2 : icmp_ln52_66_fu_728_p2);

assign select_ln52_36_fu_3047_p3 = ((and_ln52_18_reg_4066[0:0] == 1'b1) ? trunc_ln52_64_fu_3034_p1 : 7'd0);

assign select_ln52_37_fu_3075_p3 = ((or_ln52_27_reg_4060[0:0] == 1'b1) ? select_ln52_95_fu_3069_p3 : 8'd255);

assign select_ln52_39_fu_910_p3 = ((tmp_251_fu_896_p3[0:0] == 1'b1) ? icmp_ln52_74_fu_890_p2 : icmp_ln52_73_fu_884_p2);

assign select_ln52_40_fu_3109_p3 = ((and_ln52_20_reg_4096[0:0] == 1'b1) ? trunc_ln52_65_fu_3096_p1 : 7'd0);

assign select_ln52_41_fu_3137_p3 = ((or_ln52_30_reg_4090[0:0] == 1'b1) ? select_ln52_98_fu_3131_p3 : 8'd255);

assign select_ln52_43_fu_1066_p3 = ((tmp_256_fu_1052_p3[0:0] == 1'b1) ? icmp_ln52_81_fu_1046_p2 : icmp_ln52_80_fu_1040_p2);

assign select_ln52_44_fu_3171_p3 = ((and_ln52_22_reg_4126[0:0] == 1'b1) ? trunc_ln52_66_fu_3158_p1 : 7'd0);

assign select_ln52_45_fu_3199_p3 = ((or_ln52_33_reg_4120[0:0] == 1'b1) ? select_ln52_101_fu_3193_p3 : 8'd255);

assign select_ln52_47_fu_1222_p3 = ((tmp_261_fu_1208_p3[0:0] == 1'b1) ? icmp_ln52_88_fu_1202_p2 : icmp_ln52_87_fu_1196_p2);

assign select_ln52_48_fu_3233_p3 = ((and_ln52_24_reg_4156[0:0] == 1'b1) ? trunc_ln52_67_fu_3220_p1 : 7'd0);

assign select_ln52_49_fu_3261_p3 = ((or_ln52_36_reg_4150[0:0] == 1'b1) ? select_ln52_104_fu_3255_p3 : 8'd255);

assign select_ln52_50_fu_606_p3 = ((tmp_240_fu_532_p3[0:0] == 1'b1) ? select_ln52_fu_598_p3 : icmp_ln52_60_fu_578_p2);

assign select_ln52_51_fu_1378_p3 = ((tmp_266_fu_1364_p3[0:0] == 1'b1) ? icmp_ln52_95_fu_1358_p2 : icmp_ln52_94_fu_1352_p2);

assign select_ln52_52_fu_3295_p3 = ((and_ln52_26_reg_4186[0:0] == 1'b1) ? trunc_ln52_68_fu_3282_p1 : 7'd0);

assign select_ln52_53_fu_3323_p3 = ((or_ln52_39_reg_4180[0:0] == 1'b1) ? select_ln52_107_fu_3317_p3 : 8'd255);

assign select_ln52_54_fu_3007_p3 = ((tmp_reg_4017[0:0] == 1'b1) ? zext_ln52_23_fu_2992_p1 : add_ln52_reg_4023);

assign select_ln52_55_fu_1534_p3 = ((tmp_271_fu_1520_p3[0:0] == 1'b1) ? icmp_ln52_102_fu_1514_p2 : icmp_ln52_101_fu_1508_p2);

assign select_ln52_56_fu_3357_p3 = ((and_ln52_28_reg_4216[0:0] == 1'b1) ? trunc_ln52_69_fu_3344_p1 : 7'd0);

assign select_ln52_57_fu_3385_p3 = ((or_ln52_42_reg_4210[0:0] == 1'b1) ? select_ln52_110_fu_3379_p3 : 8'd255);

assign select_ln52_59_fu_1690_p3 = ((tmp_276_fu_1676_p3[0:0] == 1'b1) ? icmp_ln52_109_fu_1670_p2 : icmp_ln52_108_fu_1664_p2);

assign select_ln52_60_fu_3419_p3 = ((and_ln52_30_reg_4246[0:0] == 1'b1) ? trunc_ln52_70_fu_3406_p1 : 7'd0);

assign select_ln52_61_fu_3447_p3 = ((or_ln52_45_reg_4240[0:0] == 1'b1) ? select_ln52_113_fu_3441_p3 : 8'd255);

assign select_ln52_62_fu_762_p3 = ((tmp_245_fu_688_p3[0:0] == 1'b1) ? select_ln52_35_fu_754_p3 : icmp_ln52_67_fu_734_p2);

assign select_ln52_63_fu_1846_p3 = ((tmp_281_fu_1832_p3[0:0] == 1'b1) ? icmp_ln52_116_fu_1826_p2 : icmp_ln52_115_fu_1820_p2);

assign select_ln52_64_fu_3481_p3 = ((and_ln52_32_reg_4276[0:0] == 1'b1) ? trunc_ln52_71_fu_3468_p1 : 7'd0);

assign select_ln52_65_fu_3509_p3 = ((or_ln52_48_reg_4270[0:0] == 1'b1) ? select_ln52_116_fu_3503_p3 : 8'd255);

assign select_ln52_66_fu_3516_p3 = ((or_ln52_49_fu_3497_p2[0:0] == 1'b1) ? select_ln52_65_fu_3509_p3 : add_ln52_15_reg_4263);

assign select_ln52_67_fu_2002_p3 = ((tmp_286_fu_1988_p3[0:0] == 1'b1) ? icmp_ln52_120_fu_1982_p2 : icmp_ln52_119_fu_1976_p2);

assign select_ln52_68_fu_3543_p3 = ((and_ln52_34_reg_4306[0:0] == 1'b1) ? trunc_ln52_72_fu_3530_p1 : 7'd0);

assign select_ln52_69_fu_3571_p3 = ((or_ln52_51_reg_4300[0:0] == 1'b1) ? select_ln52_118_fu_3565_p3 : 8'd255);

assign select_ln52_70_fu_3578_p3 = ((or_ln52_52_fu_3559_p2[0:0] == 1'b1) ? select_ln52_69_fu_3571_p3 : add_ln52_16_reg_4293);

assign select_ln52_71_fu_2158_p3 = ((tmp_291_fu_2144_p3[0:0] == 1'b1) ? icmp_ln52_123_fu_2138_p2 : icmp_ln52_122_fu_2132_p2);

assign select_ln52_72_fu_3605_p3 = ((and_ln52_36_reg_4336[0:0] == 1'b1) ? trunc_ln52_73_fu_3592_p1 : 7'd0);

assign select_ln52_73_fu_3633_p3 = ((or_ln52_54_reg_4330[0:0] == 1'b1) ? select_ln52_120_fu_3627_p3 : 8'd255);

assign select_ln52_74_fu_3640_p3 = ((or_ln52_55_fu_3621_p2[0:0] == 1'b1) ? select_ln52_73_fu_3633_p3 : add_ln52_17_reg_4323);

assign select_ln52_75_fu_2314_p3 = ((tmp_296_fu_2300_p3[0:0] == 1'b1) ? icmp_ln52_126_fu_2294_p2 : icmp_ln52_125_fu_2288_p2);

assign select_ln52_76_fu_3667_p3 = ((and_ln52_38_reg_4366[0:0] == 1'b1) ? trunc_ln52_74_fu_3654_p1 : 7'd0);

assign select_ln52_77_fu_3695_p3 = ((or_ln52_57_reg_4360[0:0] == 1'b1) ? select_ln52_122_fu_3689_p3 : 8'd255);

assign select_ln52_78_fu_3702_p3 = ((or_ln52_58_fu_3683_p2[0:0] == 1'b1) ? select_ln52_77_fu_3695_p3 : add_ln52_18_reg_4353);

assign select_ln52_79_fu_2470_p3 = ((tmp_301_fu_2456_p3[0:0] == 1'b1) ? icmp_ln52_129_fu_2450_p2 : icmp_ln52_128_fu_2444_p2);

assign select_ln52_80_fu_3729_p3 = ((and_ln52_40_reg_4396[0:0] == 1'b1) ? trunc_ln52_75_fu_3716_p1 : 7'd0);

assign select_ln52_81_fu_3757_p3 = ((or_ln52_60_reg_4390[0:0] == 1'b1) ? select_ln52_124_fu_3751_p3 : 8'd255);

assign select_ln52_82_fu_3764_p3 = ((or_ln52_61_fu_3745_p2[0:0] == 1'b1) ? select_ln52_81_fu_3757_p3 : add_ln52_19_reg_4383);

assign select_ln52_83_fu_2626_p3 = ((tmp_306_fu_2612_p3[0:0] == 1'b1) ? icmp_ln52_132_fu_2606_p2 : icmp_ln52_131_fu_2600_p2);

assign select_ln52_84_fu_3791_p3 = ((and_ln52_42_reg_4426[0:0] == 1'b1) ? trunc_ln52_76_fu_3778_p1 : 7'd0);

assign select_ln52_85_fu_3819_p3 = ((or_ln52_63_reg_4420[0:0] == 1'b1) ? select_ln52_126_fu_3813_p3 : 8'd255);

assign select_ln52_86_fu_3826_p3 = ((or_ln52_64_fu_3807_p2[0:0] == 1'b1) ? select_ln52_85_fu_3819_p3 : add_ln52_20_reg_4413);

assign select_ln52_87_fu_2782_p3 = ((tmp_311_fu_2768_p3[0:0] == 1'b1) ? icmp_ln52_135_fu_2762_p2 : icmp_ln52_134_fu_2756_p2);

assign select_ln52_88_fu_3853_p3 = ((and_ln52_44_reg_4456[0:0] == 1'b1) ? trunc_ln52_77_fu_3840_p1 : 7'd0);

assign select_ln52_89_fu_3881_p3 = ((or_ln52_66_reg_4450[0:0] == 1'b1) ? select_ln52_128_fu_3875_p3 : 8'd255);

assign select_ln52_90_fu_3888_p3 = ((or_ln52_67_fu_3869_p2[0:0] == 1'b1) ? select_ln52_89_fu_3881_p3 : add_ln52_21_reg_4443);

assign select_ln52_91_fu_2938_p3 = ((tmp_316_fu_2924_p3[0:0] == 1'b1) ? icmp_ln52_138_fu_2918_p2 : icmp_ln52_137_fu_2912_p2);

assign select_ln52_92_fu_3915_p3 = ((and_ln52_46_reg_4486[0:0] == 1'b1) ? trunc_ln52_78_fu_3902_p1 : 7'd0);

assign select_ln52_93_fu_3943_p3 = ((or_ln52_69_reg_4480[0:0] == 1'b1) ? select_ln52_130_fu_3937_p3 : 8'd255);

assign select_ln52_94_fu_3950_p3 = ((or_ln52_70_fu_3931_p2[0:0] == 1'b1) ? select_ln52_93_fu_3943_p3 : add_ln52_22_reg_4473);

assign select_ln52_95_fu_3069_p3 = ((tmp_242_reg_4047[0:0] == 1'b1) ? zext_ln52_24_fu_3054_p1 : add_ln52_8_reg_4053);

assign select_ln52_97_fu_918_p3 = ((tmp_250_fu_844_p3[0:0] == 1'b1) ? select_ln52_39_fu_910_p3 : icmp_ln52_74_fu_890_p2);

assign select_ln52_98_fu_3131_p3 = ((tmp_247_reg_4077[0:0] == 1'b1) ? zext_ln52_25_fu_3116_p1 : add_ln52_9_reg_4083);

assign select_ln52_fu_598_p3 = ((tmp_241_fu_584_p3[0:0] == 1'b1) ? icmp_ln52_60_fu_578_p2 : icmp_ln52_59_fu_572_p2);

assign start_out = real_start;

assign tmp_16_fu_562_p4 = {{layer14_out_dout[41:21]}};

assign tmp_17_fu_672_p4 = {{layer14_out_dout[53:42]}};

assign tmp_18_fu_718_p4 = {{layer14_out_dout[83:63]}};

assign tmp_19_fu_828_p4 = {{layer14_out_dout[95:84]}};

assign tmp_20_fu_874_p4 = {{layer14_out_dout[125:105]}};

assign tmp_21_fu_984_p4 = {{layer14_out_dout[137:126]}};

assign tmp_22_fu_1030_p4 = {{layer14_out_dout[167:147]}};

assign tmp_238_fu_506_p3 = layer14_out_dout[32'd13];

assign tmp_239_fu_514_p3 = layer14_out_dout[32'd12];

assign tmp_23_fu_1140_p4 = {{layer14_out_dout[179:168]}};

assign tmp_240_fu_532_p3 = layer14_out_dout[32'd20];

assign tmp_241_fu_584_p3 = add_ln52_fu_556_p2[32'd7];

assign tmp_242_fu_638_p3 = layer14_out_dout[32'd83];

assign tmp_243_fu_656_p3 = layer14_out_dout[32'd55];

assign tmp_244_fu_664_p3 = layer14_out_dout[32'd54];

assign tmp_245_fu_688_p3 = layer14_out_dout[32'd62];

assign tmp_246_fu_740_p3 = add_ln52_8_fu_712_p2[32'd7];

assign tmp_247_fu_794_p3 = layer14_out_dout[32'd125];

assign tmp_248_fu_812_p3 = layer14_out_dout[32'd97];

assign tmp_249_fu_820_p3 = layer14_out_dout[32'd96];

assign tmp_24_fu_1186_p4 = {{layer14_out_dout[209:189]}};

assign tmp_250_fu_844_p3 = layer14_out_dout[32'd104];

assign tmp_251_fu_896_p3 = add_ln52_9_fu_868_p2[32'd7];

assign tmp_252_fu_950_p3 = layer14_out_dout[32'd167];

assign tmp_253_fu_968_p3 = layer14_out_dout[32'd139];

assign tmp_254_fu_976_p3 = layer14_out_dout[32'd138];

assign tmp_255_fu_1000_p3 = layer14_out_dout[32'd146];

assign tmp_256_fu_1052_p3 = add_ln52_10_fu_1024_p2[32'd7];

assign tmp_257_fu_1106_p3 = layer14_out_dout[32'd209];

assign tmp_258_fu_1124_p3 = layer14_out_dout[32'd181];

assign tmp_259_fu_1132_p3 = layer14_out_dout[32'd180];

assign tmp_25_fu_1296_p4 = {{layer14_out_dout[221:210]}};

assign tmp_260_fu_1156_p3 = layer14_out_dout[32'd188];

assign tmp_261_fu_1208_p3 = add_ln52_11_fu_1180_p2[32'd7];

assign tmp_262_fu_1262_p3 = layer14_out_dout[32'd251];

assign tmp_263_fu_1280_p3 = layer14_out_dout[32'd223];

assign tmp_264_fu_1288_p3 = layer14_out_dout[32'd222];

assign tmp_265_fu_1312_p3 = layer14_out_dout[32'd230];

assign tmp_266_fu_1364_p3 = add_ln52_12_fu_1336_p2[32'd7];

assign tmp_267_fu_1418_p3 = layer14_out_dout[32'd293];

assign tmp_268_fu_1436_p3 = layer14_out_dout[32'd265];

assign tmp_269_fu_1444_p3 = layer14_out_dout[32'd264];

assign tmp_26_fu_1342_p4 = {{layer14_out_dout[251:231]}};

assign tmp_270_fu_1468_p3 = layer14_out_dout[32'd272];

assign tmp_271_fu_1520_p3 = add_ln52_13_fu_1492_p2[32'd7];

assign tmp_272_fu_1574_p3 = layer14_out_dout[32'd335];

assign tmp_273_fu_1592_p3 = layer14_out_dout[32'd307];

assign tmp_274_fu_1600_p3 = layer14_out_dout[32'd306];

assign tmp_275_fu_1624_p3 = layer14_out_dout[32'd314];

assign tmp_276_fu_1676_p3 = add_ln52_14_fu_1648_p2[32'd7];

assign tmp_277_fu_1730_p3 = layer14_out_dout[32'd377];

assign tmp_278_fu_1748_p3 = layer14_out_dout[32'd349];

assign tmp_279_fu_1756_p3 = layer14_out_dout[32'd348];

assign tmp_27_fu_1452_p4 = {{layer14_out_dout[263:252]}};

assign tmp_280_fu_1780_p3 = layer14_out_dout[32'd356];

assign tmp_281_fu_1832_p3 = add_ln52_15_fu_1804_p2[32'd7];

assign tmp_282_fu_1886_p3 = layer14_out_dout[32'd419];

assign tmp_283_fu_1904_p3 = layer14_out_dout[32'd391];

assign tmp_284_fu_1912_p3 = layer14_out_dout[32'd390];

assign tmp_285_fu_1936_p3 = layer14_out_dout[32'd398];

assign tmp_286_fu_1988_p3 = add_ln52_16_fu_1960_p2[32'd7];

assign tmp_287_fu_2042_p3 = layer14_out_dout[32'd461];

assign tmp_288_fu_2060_p3 = layer14_out_dout[32'd433];

assign tmp_289_fu_2068_p3 = layer14_out_dout[32'd432];

assign tmp_28_fu_1498_p4 = {{layer14_out_dout[293:273]}};

assign tmp_290_fu_2092_p3 = layer14_out_dout[32'd440];

assign tmp_291_fu_2144_p3 = add_ln52_17_fu_2116_p2[32'd7];

assign tmp_292_fu_2198_p3 = layer14_out_dout[32'd503];

assign tmp_293_fu_2216_p3 = layer14_out_dout[32'd475];

assign tmp_294_fu_2224_p3 = layer14_out_dout[32'd474];

assign tmp_295_fu_2248_p3 = layer14_out_dout[32'd482];

assign tmp_296_fu_2300_p3 = add_ln52_18_fu_2272_p2[32'd7];

assign tmp_297_fu_2354_p3 = layer14_out_dout[32'd545];

assign tmp_298_fu_2372_p3 = layer14_out_dout[32'd517];

assign tmp_299_fu_2380_p3 = layer14_out_dout[32'd516];

assign tmp_29_fu_1608_p4 = {{layer14_out_dout[305:294]}};

assign tmp_300_fu_2404_p3 = layer14_out_dout[32'd524];

assign tmp_301_fu_2456_p3 = add_ln52_19_fu_2428_p2[32'd7];

assign tmp_302_fu_2510_p3 = layer14_out_dout[32'd587];

assign tmp_303_fu_2528_p3 = layer14_out_dout[32'd559];

assign tmp_304_fu_2536_p3 = layer14_out_dout[32'd558];

assign tmp_305_fu_2560_p3 = layer14_out_dout[32'd566];

assign tmp_306_fu_2612_p3 = add_ln52_20_fu_2584_p2[32'd7];

assign tmp_307_fu_2666_p3 = layer14_out_dout[32'd629];

assign tmp_308_fu_2684_p3 = layer14_out_dout[32'd601];

assign tmp_309_fu_2692_p3 = layer14_out_dout[32'd600];

assign tmp_30_fu_1654_p4 = {{layer14_out_dout[335:315]}};

assign tmp_310_fu_2716_p3 = layer14_out_dout[32'd608];

assign tmp_311_fu_2768_p3 = add_ln52_21_fu_2740_p2[32'd7];

assign tmp_312_fu_2822_p3 = layer14_out_dout[32'd671];

assign tmp_313_fu_2840_p3 = layer14_out_dout[32'd643];

assign tmp_314_fu_2848_p3 = layer14_out_dout[32'd642];

assign tmp_315_fu_2872_p3 = layer14_out_dout[32'd650];

assign tmp_316_fu_2924_p3 = add_ln52_22_fu_2896_p2[32'd7];

assign tmp_31_fu_1764_p4 = {{layer14_out_dout[347:336]}};

assign tmp_32_fu_1810_p4 = {{layer14_out_dout[377:357]}};

assign tmp_33_fu_1920_p4 = {{layer14_out_dout[389:378]}};

assign tmp_34_fu_1966_p4 = {{layer14_out_dout[419:399]}};

assign tmp_35_fu_2076_p4 = {{layer14_out_dout[431:420]}};

assign tmp_36_fu_2122_p4 = {{layer14_out_dout[461:441]}};

assign tmp_37_fu_2232_p4 = {{layer14_out_dout[473:462]}};

assign tmp_38_fu_2278_p4 = {{layer14_out_dout[503:483]}};

assign tmp_39_fu_2388_p4 = {{layer14_out_dout[515:504]}};

assign tmp_40_fu_2434_p4 = {{layer14_out_dout[545:525]}};

assign tmp_41_fu_2544_p4 = {{layer14_out_dout[557:546]}};

assign tmp_42_fu_2590_p4 = {{layer14_out_dout[587:567]}};

assign tmp_43_fu_2700_p4 = {{layer14_out_dout[599:588]}};

assign tmp_44_fu_2746_p4 = {{layer14_out_dout[629:609]}};

assign tmp_45_fu_2856_p4 = {{layer14_out_dout[641:630]}};

assign tmp_46_fu_2902_p4 = {{layer14_out_dout[671:651]}};

assign tmp_fu_488_p3 = layer14_out_dout[32'd41];

assign trunc_ln44_10_fu_352_p4 = {{layer14_out_dout[167:126]}};

assign trunc_ln44_11_fu_362_p4 = {{layer14_out_dout[209:168]}};

assign trunc_ln44_12_fu_372_p4 = {{layer14_out_dout[251:210]}};

assign trunc_ln44_13_fu_382_p4 = {{layer14_out_dout[293:252]}};

assign trunc_ln44_14_fu_392_p4 = {{layer14_out_dout[335:294]}};

assign trunc_ln44_15_fu_402_p4 = {{layer14_out_dout[377:336]}};

assign trunc_ln44_16_fu_412_p4 = {{layer14_out_dout[419:378]}};

assign trunc_ln44_17_fu_422_p4 = {{layer14_out_dout[461:420]}};

assign trunc_ln44_18_fu_432_p4 = {{layer14_out_dout[503:462]}};

assign trunc_ln44_19_fu_442_p4 = {{layer14_out_dout[545:504]}};

assign trunc_ln44_20_fu_452_p4 = {{layer14_out_dout[587:546]}};

assign trunc_ln44_21_fu_462_p4 = {{layer14_out_dout[629:588]}};

assign trunc_ln44_22_fu_472_p4 = {{layer14_out_dout[671:630]}};

assign trunc_ln44_8_fu_332_p4 = {{layer14_out_dout[83:42]}};

assign trunc_ln44_9_fu_342_p4 = {{layer14_out_dout[125:84]}};

assign trunc_ln44_fu_328_p1 = layer14_out_dout[41:0];

assign trunc_ln52_10_fu_958_p4 = {{layer14_out_dout[146:139]}};

assign trunc_ln52_11_fu_1114_p4 = {{layer14_out_dout[188:181]}};

assign trunc_ln52_12_fu_1270_p4 = {{layer14_out_dout[230:223]}};

assign trunc_ln52_13_fu_1426_p4 = {{layer14_out_dout[272:265]}};

assign trunc_ln52_14_fu_1582_p4 = {{layer14_out_dout[314:307]}};

assign trunc_ln52_15_fu_1738_p4 = {{layer14_out_dout[356:349]}};

assign trunc_ln52_16_fu_1894_p4 = {{layer14_out_dout[398:391]}};

assign trunc_ln52_17_fu_2050_p4 = {{layer14_out_dout[440:433]}};

assign trunc_ln52_18_fu_2206_p4 = {{layer14_out_dout[482:475]}};

assign trunc_ln52_19_fu_2362_p4 = {{layer14_out_dout[524:517]}};

assign trunc_ln52_20_fu_2518_p4 = {{layer14_out_dout[566:559]}};

assign trunc_ln52_21_fu_2674_p4 = {{layer14_out_dout[608:601]}};

assign trunc_ln52_22_fu_2830_p4 = {{layer14_out_dout[650:643]}};

assign trunc_ln52_63_fu_2972_p1 = add_ln52_reg_4023[6:0];

assign trunc_ln52_64_fu_3034_p1 = add_ln52_8_reg_4053[6:0];

assign trunc_ln52_65_fu_3096_p1 = add_ln52_9_reg_4083[6:0];

assign trunc_ln52_66_fu_3158_p1 = add_ln52_10_reg_4113[6:0];

assign trunc_ln52_67_fu_3220_p1 = add_ln52_11_reg_4143[6:0];

assign trunc_ln52_68_fu_3282_p1 = add_ln52_12_reg_4173[6:0];

assign trunc_ln52_69_fu_3344_p1 = add_ln52_13_reg_4203[6:0];

assign trunc_ln52_70_fu_3406_p1 = add_ln52_14_reg_4233[6:0];

assign trunc_ln52_71_fu_3468_p1 = add_ln52_15_reg_4263[6:0];

assign trunc_ln52_72_fu_3530_p1 = add_ln52_16_reg_4293[6:0];

assign trunc_ln52_73_fu_3592_p1 = add_ln52_17_reg_4323[6:0];

assign trunc_ln52_74_fu_3654_p1 = add_ln52_18_reg_4353[6:0];

assign trunc_ln52_75_fu_3716_p1 = add_ln52_19_reg_4383[6:0];

assign trunc_ln52_76_fu_3778_p1 = add_ln52_20_reg_4413[6:0];

assign trunc_ln52_77_fu_3840_p1 = add_ln52_21_reg_4443[6:0];

assign trunc_ln52_78_fu_3902_p1 = add_ln52_22_reg_4473[6:0];

assign trunc_ln52_8_fu_646_p4 = {{layer14_out_dout[62:55]}};

assign trunc_ln52_9_fu_802_p4 = {{layer14_out_dout[104:97]}};

assign trunc_ln52_fu_522_p1 = layer14_out_dout[11:0];

assign trunc_ln5_fu_496_p4 = {{layer14_out_dout[20:13]}};

assign xor_ln52_111_fu_592_p2 = (tmp_241_fu_584_p3 ^ 1'd1);

assign xor_ln52_112_fu_748_p2 = (tmp_246_fu_740_p3 ^ 1'd1);

assign xor_ln52_113_fu_904_p2 = (tmp_251_fu_896_p3 ^ 1'd1);

assign xor_ln52_114_fu_1060_p2 = (tmp_256_fu_1052_p3 ^ 1'd1);

assign xor_ln52_115_fu_1216_p2 = (tmp_261_fu_1208_p3 ^ 1'd1);

assign xor_ln52_116_fu_1372_p2 = (tmp_266_fu_1364_p3 ^ 1'd1);

assign xor_ln52_117_fu_1528_p2 = (tmp_271_fu_1520_p3 ^ 1'd1);

assign xor_ln52_118_fu_1684_p2 = (tmp_276_fu_1676_p3 ^ 1'd1);

assign xor_ln52_119_fu_1840_p2 = (tmp_281_fu_1832_p3 ^ 1'd1);

assign xor_ln52_120_fu_1996_p2 = (tmp_286_fu_1988_p3 ^ 1'd1);

assign xor_ln52_121_fu_2152_p2 = (tmp_291_fu_2144_p3 ^ 1'd1);

assign xor_ln52_122_fu_2308_p2 = (tmp_296_fu_2300_p3 ^ 1'd1);

assign xor_ln52_123_fu_2464_p2 = (tmp_301_fu_2456_p3 ^ 1'd1);

assign xor_ln52_124_fu_2620_p2 = (tmp_306_fu_2612_p3 ^ 1'd1);

assign xor_ln52_125_fu_2776_p2 = (tmp_311_fu_2768_p3 ^ 1'd1);

assign xor_ln52_126_fu_2932_p2 = (tmp_316_fu_2924_p3 ^ 1'd1);

assign xor_ln52_16_fu_2980_p2 = (1'd1 ^ and_ln52_16_reg_4036);

assign xor_ln52_17_fu_3037_p2 = (or_ln52_27_reg_4060 ^ 1'd1);

assign xor_ln52_18_fu_3042_p2 = (1'd1 ^ and_ln52_18_reg_4066);

assign xor_ln52_19_fu_3099_p2 = (or_ln52_30_reg_4090 ^ 1'd1);

assign xor_ln52_20_fu_3104_p2 = (1'd1 ^ and_ln52_20_reg_4096);

assign xor_ln52_21_fu_3161_p2 = (or_ln52_33_reg_4120 ^ 1'd1);

assign xor_ln52_22_fu_3166_p2 = (1'd1 ^ and_ln52_22_reg_4126);

assign xor_ln52_23_fu_3223_p2 = (or_ln52_36_reg_4150 ^ 1'd1);

assign xor_ln52_24_fu_3228_p2 = (1'd1 ^ and_ln52_24_reg_4156);

assign xor_ln52_25_fu_3285_p2 = (or_ln52_39_reg_4180 ^ 1'd1);

assign xor_ln52_26_fu_3290_p2 = (1'd1 ^ and_ln52_26_reg_4186);

assign xor_ln52_27_fu_3347_p2 = (or_ln52_42_reg_4210 ^ 1'd1);

assign xor_ln52_28_fu_3352_p2 = (1'd1 ^ and_ln52_28_reg_4216);

assign xor_ln52_29_fu_3409_p2 = (or_ln52_45_reg_4240 ^ 1'd1);

assign xor_ln52_30_fu_3414_p2 = (1'd1 ^ and_ln52_30_reg_4246);

assign xor_ln52_31_fu_3471_p2 = (or_ln52_48_reg_4270 ^ 1'd1);

assign xor_ln52_32_fu_3476_p2 = (1'd1 ^ and_ln52_32_reg_4276);

assign xor_ln52_33_fu_3533_p2 = (or_ln52_51_reg_4300 ^ 1'd1);

assign xor_ln52_34_fu_3538_p2 = (1'd1 ^ and_ln52_34_reg_4306);

assign xor_ln52_35_fu_3595_p2 = (or_ln52_54_reg_4330 ^ 1'd1);

assign xor_ln52_36_fu_3600_p2 = (1'd1 ^ and_ln52_36_reg_4336);

assign xor_ln52_37_fu_3657_p2 = (or_ln52_57_reg_4360 ^ 1'd1);

assign xor_ln52_38_fu_3662_p2 = (1'd1 ^ and_ln52_38_reg_4366);

assign xor_ln52_39_fu_3719_p2 = (or_ln52_60_reg_4390 ^ 1'd1);

assign xor_ln52_40_fu_3724_p2 = (1'd1 ^ and_ln52_40_reg_4396);

assign xor_ln52_41_fu_3781_p2 = (or_ln52_63_reg_4420 ^ 1'd1);

assign xor_ln52_42_fu_3786_p2 = (1'd1 ^ and_ln52_42_reg_4426);

assign xor_ln52_43_fu_3843_p2 = (or_ln52_66_reg_4450 ^ 1'd1);

assign xor_ln52_44_fu_3848_p2 = (1'd1 ^ and_ln52_44_reg_4456);

assign xor_ln52_45_fu_3905_p2 = (or_ln52_69_reg_4480 ^ 1'd1);

assign xor_ln52_46_fu_3910_p2 = (1'd1 ^ and_ln52_46_reg_4486);

assign xor_ln52_fu_2975_p2 = (or_ln52_24_reg_4030 ^ 1'd1);

assign zext_ln52_10_fu_1020_p1 = and_ln52_21_fu_1014_p2;

assign zext_ln52_11_fu_1176_p1 = and_ln52_23_fu_1170_p2;

assign zext_ln52_12_fu_1332_p1 = and_ln52_25_fu_1326_p2;

assign zext_ln52_13_fu_1488_p1 = and_ln52_27_fu_1482_p2;

assign zext_ln52_14_fu_1644_p1 = and_ln52_29_fu_1638_p2;

assign zext_ln52_15_fu_1800_p1 = and_ln52_31_fu_1794_p2;

assign zext_ln52_16_fu_1956_p1 = and_ln52_33_fu_1950_p2;

assign zext_ln52_17_fu_2112_p1 = and_ln52_35_fu_2106_p2;

assign zext_ln52_18_fu_2268_p1 = and_ln52_37_fu_2262_p2;

assign zext_ln52_19_fu_2424_p1 = and_ln52_39_fu_2418_p2;

assign zext_ln52_20_fu_2580_p1 = and_ln52_41_fu_2574_p2;

assign zext_ln52_21_fu_2736_p1 = and_ln52_43_fu_2730_p2;

assign zext_ln52_22_fu_2892_p1 = and_ln52_45_fu_2886_p2;

assign zext_ln52_23_fu_2992_p1 = select_ln52_32_fu_2985_p3;

assign zext_ln52_24_fu_3054_p1 = select_ln52_36_fu_3047_p3;

assign zext_ln52_25_fu_3116_p1 = select_ln52_40_fu_3109_p3;

assign zext_ln52_26_fu_3178_p1 = select_ln52_44_fu_3171_p3;

assign zext_ln52_27_fu_3240_p1 = select_ln52_48_fu_3233_p3;

assign zext_ln52_28_fu_3302_p1 = select_ln52_52_fu_3295_p3;

assign zext_ln52_29_fu_3364_p1 = select_ln52_56_fu_3357_p3;

assign zext_ln52_30_fu_3426_p1 = select_ln52_60_fu_3419_p3;

assign zext_ln52_31_fu_3488_p1 = select_ln52_64_fu_3481_p3;

assign zext_ln52_32_fu_3550_p1 = select_ln52_68_fu_3543_p3;

assign zext_ln52_33_fu_3612_p1 = select_ln52_72_fu_3605_p3;

assign zext_ln52_34_fu_3674_p1 = select_ln52_76_fu_3667_p3;

assign zext_ln52_35_fu_3736_p1 = select_ln52_80_fu_3729_p3;

assign zext_ln52_36_fu_3798_p1 = select_ln52_84_fu_3791_p3;

assign zext_ln52_37_fu_3860_p1 = select_ln52_88_fu_3853_p3;

assign zext_ln52_38_fu_3922_p1 = select_ln52_92_fu_3915_p3;

assign zext_ln52_8_fu_708_p1 = and_ln52_17_fu_702_p2;

assign zext_ln52_9_fu_864_p1 = and_ln52_19_fu_858_p2;

assign zext_ln52_fu_552_p1 = and_ln52_fu_546_p2;

endmodule //myproject_relu_array_ap_fixed_16u_array_ap_ufixed_8_4_4_0_0_16u_relu_config15_s
