-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_normalize_array_ap_fixed_16u_array_ap_fixed_33_21_5_3_0_16u_config9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer7_out_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    layer7_out_empty_n : IN STD_LOGIC;
    layer7_out_read : OUT STD_LOGIC;
    layer9_out_din : OUT STD_LOGIC_VECTOR (527 downto 0);
    layer9_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer9_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    layer9_out_full_n : IN STD_LOGIC;
    layer9_out_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of myproject_normalize_array_ap_fixed_16u_array_ap_fixed_33_21_5_3_0_16u_config9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv31_7A92 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000111101010010010";
    constant ap_const_lv31_7A7F : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000111101001111111";
    constant ap_const_lv26_294 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010010100";
    constant ap_const_lv26_291 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010010001";
    constant ap_const_lv27_759 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000011101011001";
    constant ap_const_lv27_723 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000011100100011";
    constant ap_const_lv26_33F : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001100111111";
    constant ap_const_lv27_503 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000010100000011";
    constant ap_const_lv27_4AA : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000010010101010";
    constant ap_const_lv31_74AA : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000111010010101010";
    constant ap_const_lv26_2B6 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010110110";
    constant ap_const_lv27_5D3 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000010111010011";
    constant ap_const_lv28_E2D : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000111000101101";
    constant ap_const_lv28_DC9 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000110111001001";
    constant ap_const_lv27_556 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000010101010110";
    constant ap_const_lv27_45D : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000010001011101";
    constant ap_const_lv10_2BC : STD_LOGIC_VECTOR (9 downto 0) := "1010111100";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv31_7FFFFD10 : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111110100010000";
    constant ap_const_lv26_3FFEE64 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111110111001100100";
    constant ap_const_lv27_7FFF2E0 : STD_LOGIC_VECTOR (26 downto 0) := "111111111111111001011100000";
    constant ap_const_lv26_160 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000101100000";
    constant ap_const_lv31_7FFFFE38 : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111000111000";
    constant ap_const_lv26_3FFE5C0 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111110010111000000";
    constant ap_const_lv27_A04 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000101000000100";
    constant ap_const_lv27_BA8 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000101110101000";
    constant ap_const_lv26_3FFEFF0 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111110111111110000";
    constant ap_const_lv27_458 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000010001011000";
    constant ap_const_lv31_7FFFFD98 : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111110110011000";
    constant ap_const_lv27_10D0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000001000011010000";
    constant ap_const_lv28_FFFFEFC : STD_LOGIC_VECTOR (27 downto 0) := "1111111111111111111011111100";
    constant ap_const_lv27_7FFEFCC : STD_LOGIC_VECTOR (26 downto 0) := "111111111111110111111001100";
    constant ap_const_lv28_DF0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000110111110000";
    constant ap_const_lv27_600 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000011000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln25_fu_728324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer7_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal layer9_out_blk_n : STD_LOGIC;
    signal mul_ln42_fu_3969_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln42_reg_728251 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal mul_ln42_22_fu_3250_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_22_reg_728255 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_23_fu_3861_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_23_reg_728259 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_24_fu_2528_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_24_reg_728263 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_25_fu_1264_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln42_25_reg_728267 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln42_26_fu_2554_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_26_reg_728271 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_27_fu_2608_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_27_reg_728275 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_28_fu_3711_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_28_reg_728279 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_29_fu_5174_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_29_reg_728283 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_30_fu_2566_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_30_reg_728287 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_31_fu_1914_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln42_31_reg_728291 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln42_32_fu_5353_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_32_reg_728295 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_33_fu_6465_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln42_33_reg_728299 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln42_34_fu_9435_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_34_reg_728303 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_35_fu_6285_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln42_35_reg_728307 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln42_36_fu_7875_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln42_36_reg_728311 : STD_LOGIC_VECTOR (26 downto 0);
    signal a_fu_728341_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_reg_728767 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_29_reg_728772 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_15_reg_728777 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_16_reg_728782 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_17_reg_728787 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_18_reg_728792 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_19_reg_728797 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_20_reg_728802 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_21_reg_728807 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_22_reg_728812 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_23_reg_728817 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_24_reg_728822 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_25_reg_728827 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_26_reg_728832 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_27_reg_728837 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_28_reg_728842 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_02_fu_170 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal i_11_fu_728330_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal mul_ln42_25_fu_1264_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_31_fu_1914_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_24_fu_2528_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_26_fu_2554_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_30_fu_2566_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln42_27_fu_2608_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln42_22_fu_3250_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_28_fu_3711_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln42_23_fu_3861_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln42_fu_3969_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_29_fu_5174_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_32_fu_5353_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln42_35_fu_6285_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_33_fu_6465_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln42_36_fu_7875_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln42_34_fu_9435_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln42_fu_728559_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln42_23_fu_728569_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_24_fu_728579_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln42_25_fu_728589_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_26_fu_728599_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln42_27_fu_728609_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_28_fu_728619_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln42_29_fu_728629_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln42_30_fu_728639_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln42_31_fu_728649_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln42_32_fu_728659_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln42_33_fu_728669_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln42_34_fu_728679_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln42_35_fu_728689_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln42_36_fu_728699_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln42_37_fu_728709_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln70_33_fu_728705_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_32_fu_728695_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_31_fu_728685_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_30_fu_728675_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_29_fu_728665_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_28_fu_728655_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_27_fu_728645_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_26_fu_728635_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_25_fu_728625_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_24_fu_728615_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_23_fu_728605_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_22_fu_728595_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_21_fu_728585_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_20_fu_728575_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln70_fu_728565_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal or_ln46_s_fu_728715_p17 : STD_LOGIC_VECTOR (521 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_182 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_16s_16ns_31_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component myproject_mul_16s_11ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_12ns_27_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;


    component myproject_mul_16s_13ns_28_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    mul_16s_16ns_31_1_1_U600 : component myproject_mul_16s_16ns_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 31)
    port map (
        din0 => a_17_reg_728787,
        din1 => mul_ln42_25_fu_1264_p1,
        dout => mul_ln42_25_fu_1264_p2);

    mul_16s_16ns_31_1_1_U601 : component myproject_mul_16s_16ns_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 31)
    port map (
        din0 => a_23_reg_728817,
        din1 => mul_ln42_31_fu_1914_p1,
        dout => mul_ln42_31_fu_1914_p2);

    mul_16s_11ns_26_1_1_U602 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => a_16_reg_728782,
        din1 => mul_ln42_24_fu_2528_p1,
        dout => mul_ln42_24_fu_2528_p2);

    mul_16s_11ns_26_1_1_U603 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => a_18_reg_728792,
        din1 => mul_ln42_26_fu_2554_p1,
        dout => mul_ln42_26_fu_2554_p2);

    mul_16s_12ns_27_1_1_U604 : component myproject_mul_16s_12ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 27)
    port map (
        din0 => a_22_reg_728812,
        din1 => mul_ln42_30_fu_2566_p1,
        dout => mul_ln42_30_fu_2566_p2);

    mul_16s_12ns_27_1_1_U605 : component myproject_mul_16s_12ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 27)
    port map (
        din0 => a_19_reg_728797,
        din1 => mul_ln42_27_fu_2608_p1,
        dout => mul_ln42_27_fu_2608_p2);

    mul_16s_11ns_26_1_1_U606 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => a_29_reg_728772,
        din1 => mul_ln42_22_fu_3250_p1,
        dout => mul_ln42_22_fu_3250_p2);

    mul_16s_12ns_27_1_1_U607 : component myproject_mul_16s_12ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 27)
    port map (
        din0 => a_20_reg_728802,
        din1 => mul_ln42_28_fu_3711_p1,
        dout => mul_ln42_28_fu_3711_p2);

    mul_16s_12ns_27_1_1_U608 : component myproject_mul_16s_12ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 27)
    port map (
        din0 => a_15_reg_728777,
        din1 => mul_ln42_23_fu_3861_p1,
        dout => mul_ln42_23_fu_3861_p2);

    mul_16s_16ns_31_1_1_U609 : component myproject_mul_16s_16ns_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 31)
    port map (
        din0 => a_reg_728767,
        din1 => mul_ln42_fu_3969_p1,
        dout => mul_ln42_fu_3969_p2);

    mul_16s_11ns_26_1_1_U610 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => a_21_reg_728807,
        din1 => mul_ln42_29_fu_5174_p1,
        dout => mul_ln42_29_fu_5174_p2);

    mul_16s_12ns_27_1_1_U611 : component myproject_mul_16s_12ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 27)
    port map (
        din0 => a_24_reg_728822,
        din1 => mul_ln42_32_fu_5353_p1,
        dout => mul_ln42_32_fu_5353_p2);

    mul_16s_13ns_28_1_1_U612 : component myproject_mul_16s_13ns_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 28)
    port map (
        din0 => a_27_reg_728837,
        din1 => mul_ln42_35_fu_6285_p1,
        dout => mul_ln42_35_fu_6285_p2);

    mul_16s_13ns_28_1_1_U613 : component myproject_mul_16s_13ns_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 28)
    port map (
        din0 => a_25_reg_728827,
        din1 => mul_ln42_33_fu_6465_p1,
        dout => mul_ln42_33_fu_6465_p2);

    mul_16s_12ns_27_1_1_U614 : component myproject_mul_16s_12ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 27)
    port map (
        din0 => a_28_reg_728842,
        din1 => mul_ln42_36_fu_7875_p1,
        dout => mul_ln42_36_fu_7875_p2);

    mul_16s_12ns_27_1_1_U615 : component myproject_mul_16s_12ns_27_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 27)
    port map (
        din0 => a_26_reg_728832,
        din1 => mul_ln42_34_fu_9435_p1,
        dout => mul_ln42_34_fu_9435_p2);

    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_02_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_182)) then
                if ((icmp_ln25_fu_728324_p2 = ap_const_lv1_0)) then 
                    i_02_fu_170 <= i_11_fu_728330_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_02_fu_170 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a_15_reg_728777 <= layer7_out_dout(47 downto 32);
                a_16_reg_728782 <= layer7_out_dout(63 downto 48);
                a_17_reg_728787 <= layer7_out_dout(79 downto 64);
                a_18_reg_728792 <= layer7_out_dout(95 downto 80);
                a_19_reg_728797 <= layer7_out_dout(111 downto 96);
                a_20_reg_728802 <= layer7_out_dout(127 downto 112);
                a_21_reg_728807 <= layer7_out_dout(143 downto 128);
                a_22_reg_728812 <= layer7_out_dout(159 downto 144);
                a_23_reg_728817 <= layer7_out_dout(175 downto 160);
                a_24_reg_728822 <= layer7_out_dout(191 downto 176);
                a_25_reg_728827 <= layer7_out_dout(207 downto 192);
                a_26_reg_728832 <= layer7_out_dout(223 downto 208);
                a_27_reg_728837 <= layer7_out_dout(239 downto 224);
                a_28_reg_728842 <= layer7_out_dout(255 downto 240);
                a_29_reg_728772 <= layer7_out_dout(31 downto 16);
                a_reg_728767 <= a_fu_728341_p1;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                mul_ln42_22_reg_728255 <= mul_ln42_22_fu_3250_p2;
                mul_ln42_23_reg_728259 <= mul_ln42_23_fu_3861_p2;
                mul_ln42_24_reg_728263 <= mul_ln42_24_fu_2528_p2;
                mul_ln42_25_reg_728267 <= mul_ln42_25_fu_1264_p2;
                mul_ln42_26_reg_728271 <= mul_ln42_26_fu_2554_p2;
                mul_ln42_27_reg_728275 <= mul_ln42_27_fu_2608_p2;
                mul_ln42_28_reg_728279 <= mul_ln42_28_fu_3711_p2;
                mul_ln42_29_reg_728283 <= mul_ln42_29_fu_5174_p2;
                mul_ln42_30_reg_728287 <= mul_ln42_30_fu_2566_p2;
                mul_ln42_31_reg_728291 <= mul_ln42_31_fu_1914_p2;
                mul_ln42_32_reg_728295 <= mul_ln42_32_fu_5353_p2;
                mul_ln42_33_reg_728299 <= mul_ln42_33_fu_6465_p2;
                mul_ln42_34_reg_728303 <= mul_ln42_34_fu_9435_p2;
                mul_ln42_35_reg_728307 <= mul_ln42_35_fu_6285_p2;
                mul_ln42_36_reg_728311 <= mul_ln42_36_fu_7875_p2;
                mul_ln42_reg_728251 <= mul_ln42_fu_3969_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_fu_728341_p1 <= layer7_out_dout(16 - 1 downto 0);
    add_ln42_23_fu_728569_p2 <= std_logic_vector(unsigned(mul_ln42_22_reg_728255) + unsigned(ap_const_lv26_3FFEE64));
    add_ln42_24_fu_728579_p2 <= std_logic_vector(unsigned(mul_ln42_23_reg_728259) + unsigned(ap_const_lv27_7FFF2E0));
    add_ln42_25_fu_728589_p2 <= std_logic_vector(unsigned(mul_ln42_24_reg_728263) + unsigned(ap_const_lv26_160));
    add_ln42_26_fu_728599_p2 <= std_logic_vector(unsigned(mul_ln42_25_reg_728267) + unsigned(ap_const_lv31_7FFFFE38));
    add_ln42_27_fu_728609_p2 <= std_logic_vector(unsigned(mul_ln42_26_reg_728271) + unsigned(ap_const_lv26_3FFE5C0));
    add_ln42_28_fu_728619_p2 <= std_logic_vector(unsigned(mul_ln42_27_reg_728275) + unsigned(ap_const_lv27_A04));
    add_ln42_29_fu_728629_p2 <= std_logic_vector(unsigned(mul_ln42_28_reg_728279) + unsigned(ap_const_lv27_BA8));
    add_ln42_30_fu_728639_p2 <= std_logic_vector(unsigned(mul_ln42_29_reg_728283) + unsigned(ap_const_lv26_3FFEFF0));
    add_ln42_31_fu_728649_p2 <= std_logic_vector(unsigned(mul_ln42_30_reg_728287) + unsigned(ap_const_lv27_458));
    add_ln42_32_fu_728659_p2 <= std_logic_vector(unsigned(mul_ln42_31_reg_728291) + unsigned(ap_const_lv31_7FFFFD98));
    add_ln42_33_fu_728669_p2 <= std_logic_vector(unsigned(mul_ln42_32_reg_728295) + unsigned(ap_const_lv27_10D0));
    add_ln42_34_fu_728679_p2 <= std_logic_vector(unsigned(mul_ln42_33_reg_728299) + unsigned(ap_const_lv28_FFFFEFC));
    add_ln42_35_fu_728689_p2 <= std_logic_vector(unsigned(mul_ln42_34_reg_728303) + unsigned(ap_const_lv27_7FFEFCC));
    add_ln42_36_fu_728699_p2 <= std_logic_vector(unsigned(mul_ln42_35_reg_728307) + unsigned(ap_const_lv28_DF0));
    add_ln42_37_fu_728709_p2 <= std_logic_vector(unsigned(mul_ln42_36_reg_728311) + unsigned(ap_const_lv27_600));
    add_ln42_fu_728559_p2 <= std_logic_vector(unsigned(mul_ln42_reg_728251) + unsigned(ap_const_lv31_7FFFFD10));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state4_pp0_stage0_iter3, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state4_pp0_stage0_iter3, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state4_pp0_stage0_iter3, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(layer7_out_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (layer7_out_empty_n = ap_const_logic_0);
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(layer9_out_full_n)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (layer9_out_full_n = ap_const_logic_0);
    end process;


    ap_condition_182_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_182 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln25_fu_728324_p2, ap_start_int)
    begin
        if (((icmp_ln25_fu_728324_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_02_fu_170, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i <= i_02_fu_170;
        end if; 
    end process;

    i_11_fu_728330_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv10_1));
    icmp_ln25_fu_728324_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv10_2BC) else "0";

    layer7_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer7_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer7_out_blk_n <= layer7_out_empty_n;
        else 
            layer7_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer7_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer7_out_read <= ap_const_logic_1;
        else 
            layer7_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer9_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, layer9_out_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer9_out_blk_n <= layer9_out_full_n;
        else 
            layer9_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        layer9_out_din <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln46_s_fu_728715_p17),528));


    layer9_out_write_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer9_out_write <= ap_const_logic_1;
        else 
            layer9_out_write <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln42_22_fu_3250_p1 <= ap_const_lv26_33F(11 - 1 downto 0);
    mul_ln42_23_fu_3861_p1 <= ap_const_lv27_4AA(12 - 1 downto 0);
    mul_ln42_24_fu_2528_p1 <= ap_const_lv26_294(11 - 1 downto 0);
    mul_ln42_25_fu_1264_p1 <= ap_const_lv31_7A92(16 - 1 downto 0);
    mul_ln42_26_fu_2554_p1 <= ap_const_lv26_291(11 - 1 downto 0);
    mul_ln42_27_fu_2608_p1 <= ap_const_lv27_723(12 - 1 downto 0);
    mul_ln42_28_fu_3711_p1 <= ap_const_lv27_503(12 - 1 downto 0);
    mul_ln42_29_fu_5174_p1 <= ap_const_lv26_2B6(11 - 1 downto 0);
    mul_ln42_30_fu_2566_p1 <= ap_const_lv27_759(12 - 1 downto 0);
    mul_ln42_31_fu_1914_p1 <= ap_const_lv31_7A7F(16 - 1 downto 0);
    mul_ln42_32_fu_5353_p1 <= ap_const_lv27_5D3(12 - 1 downto 0);
    mul_ln42_33_fu_6465_p1 <= ap_const_lv28_DC9(13 - 1 downto 0);
    mul_ln42_34_fu_9435_p1 <= ap_const_lv27_45D(12 - 1 downto 0);
    mul_ln42_35_fu_6285_p1 <= ap_const_lv28_E2D(13 - 1 downto 0);
    mul_ln42_36_fu_7875_p1 <= ap_const_lv27_556(12 - 1 downto 0);
    mul_ln42_fu_3969_p1 <= ap_const_lv31_74AA(16 - 1 downto 0);
    or_ln46_s_fu_728715_p17 <= (((((((((((((((add_ln42_37_fu_728709_p2 & sext_ln70_33_fu_728705_p1) & sext_ln70_32_fu_728695_p1) & sext_ln70_31_fu_728685_p1) & sext_ln70_30_fu_728675_p1) & sext_ln70_29_fu_728665_p1) & sext_ln70_28_fu_728655_p1) & sext_ln70_27_fu_728645_p1) & sext_ln70_26_fu_728635_p1) & sext_ln70_25_fu_728625_p1) & sext_ln70_24_fu_728615_p1) & sext_ln70_23_fu_728605_p1) & sext_ln70_22_fu_728595_p1) & sext_ln70_21_fu_728585_p1) & sext_ln70_20_fu_728575_p1) & sext_ln70_fu_728565_p1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

        sext_ln70_20_fu_728575_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_23_fu_728569_p2),33));

        sext_ln70_21_fu_728585_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_24_fu_728579_p2),33));

        sext_ln70_22_fu_728595_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_25_fu_728589_p2),33));

        sext_ln70_23_fu_728605_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_26_fu_728599_p2),33));

        sext_ln70_24_fu_728615_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_27_fu_728609_p2),33));

        sext_ln70_25_fu_728625_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_28_fu_728619_p2),33));

        sext_ln70_26_fu_728635_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_29_fu_728629_p2),33));

        sext_ln70_27_fu_728645_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_30_fu_728639_p2),33));

        sext_ln70_28_fu_728655_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_31_fu_728649_p2),33));

        sext_ln70_29_fu_728665_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_32_fu_728659_p2),33));

        sext_ln70_30_fu_728675_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_33_fu_728669_p2),33));

        sext_ln70_31_fu_728685_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_34_fu_728679_p2),33));

        sext_ln70_32_fu_728695_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_35_fu_728689_p2),33));

        sext_ln70_33_fu_728705_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_36_fu_728699_p2),33));

        sext_ln70_fu_728565_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln42_fu_728559_p2),33));

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
